### ISSUE TITLE
Does Not Work With Homebrew JACK

### ISSUE THREAD

**Issue by chimeworld** [jacktrip/jacktrip#104]
I got this error after using Homebrew JACK.

```➜  ~ jacktrip -s
dyld: Library not loaded: /Library/Frameworks/Jackmp.framework/Versions/A/Jackmp
  Referenced from: /usr/local/bin/jacktrip
  Reason: image not found
[1]    5665 abort      jacktrip -s```

**Comment by dyfer** [comment]
The same happens to me when trying to use JackTrip with jack from the ["new" jack2 installer](https://github.com/jackaudio/jack2-releases/releases/tag/untagged-3b805b67851f90f915e3). 
Just so it's clear - this issue applies to macOS.

**Comment by dvzrv** [comment]
Related, I think jacktrip for macOS should be built against jack from the [official upstream installer](https://jackaudio.org/downloads/).

What is the reason for providing the (very old) [custom jackOSX](https://ccrma.stanford.edu/software/jacktrip/osx/)?

**Comment by falkTX** [comment]
jackosx was the only available thing at some point.
1.9.15 was just released 1 day ago, so they need time to catch up now.

**Comment by ntonnaett** [comment]
If this is happening with Jack 1.9.17, please reopen!
