### ISSUE TITLE
Build Failing on Linux

### ISSUE THREAD

**Issue by driechers** [jacktrip/jacktrip#105]
Build fails with error: no matching function for call to ‘QHostAddress::toIPv4Address(bool*)’. See attached build log

Some versioning details of my system:

```
daniel@Stout:~/git/jacktrip/src$ uname -a
Linux Stout 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
daniel@Stout:~/git/jacktrip/src$ cat /etc/issue
Ubuntu 18.04 LTS \n \l
daniel@Stout:~/git/jacktrip/src$ g++ --version
g++ (Ubuntu 7.3.0-16ubuntu3) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

[build.log](https://github.com/jacktrip/jacktrip/files/4998330/build.log)

**Comment by dyfer** [comment]
Maybe [this](https://github.com/jacktrip/jacktrip/pull/101) is related? What's your QT version?

**Comment by driechers** [comment]
Ah yes. I have added a duplicate issue. I have qt4 and qt5 libraries installed but it is building against qt4. Ubuntu 18 LTS apt repos appear to only have libqt4-dev and no libqt5-dev so I'll have to look into upgrading as well. However, unlike the other ticket on this issue Ubuntu 18 is still very much supported by canonical.

**Comment by ntonnaett** [comment]
Ubuntu 18.04 has qt5 libraries.
apt install build-essential qtbase5-dev libjack-jackd2-dev
should be anything you need.

**Comment by driechers** [comment]
I appear to have those packages installed already but the build log shows it pulling includes from /usr/include/qt4. I have tried apt-get remove libqt4-dev and it still tries to pull headers from that location (unsuccessfully now) I'm a bit hesitant to remove libqt4 all together because it looks like I have some other packages that depend on libqt4. But I found what is going on.

the qmake in my path appears to be qt4 qmake. I have both qt4 and qt5-qmake installed.
dpkg -L qt5-qmake-bin shows me that the binary for qt5-qmake is in /usr/lib/qt5/bin/qmake I can successfully build by running the following:

/usr/lib/qt5/bin/qmake
make

So I guess the build script does not work properly if you have multiple versions of qmake installed.

**Comment by ntonnaett** [comment]
There is qtchooser for switching between versions.

**Comment by driechers** [comment]
Awesome good to know. I don’t ever use qt but it seems strange to me that it has its own build system and everything. Then again I don’t have full perspective on everything that qt does. 

Since there is a dependency on the newer qt5 and I have a machine reproducing the issue already, I’ll submit  a pull request in the next couple of days fixing the build script so that it matches the build instructions in the documentation for others in my situation with multiple versions of qt. Either that or a pull request to update the build instructions. Any preference?

**Comment by ntonnaett** [comment]
That would introduce a dependency to qtchooser. I thought qtchooser works like the alternatives system. Do we still support qt4? If not maybe we could just call qmake-qt5? Is there a qmake-qt5 in Debian?
Could you try to build jacktrip with meson? I'm curious about the magic it does in the background.

**Comment by driechers** [comment]
Discussion in the related issue #101 indicates that jacktrip cannot be build using qt4. Changing the build to meson seems to be a much larger effort. Ubuntu 18 does not seem to have qmake-qt5 in the path by default. The package qt5-qmake-bin installs the command to /usr/lib/qt5/bin/qmake for some reason. The pull request I have opened does rely on qtchooser but is that a problem? I didn't have to update the ci environment. Do typical distros install qtchooser with other qt development packages? I didn't have to install anything extra to get it to work, but it was probably installed for some other qt software I built at some point.

**Comment by ntonnaett** [comment]
For Fedora you have to install qtchooser separately. Maybe that's the cleanest solution. I just try to build.

**Comment by driechers** [comment]
Maybe we should update the CI to try different distros. I'm not exactly sure what is involved with that and what project access is required since I haven't done much with Travis.

**Comment by ntonnaett** [comment]
That's a good idea. Adding FreeBSD to the list would be nice too. But I don't know how those ports are working. Maybe @yurivict could tell us more.

**Comment by driechers** [comment]
@ntonnaett I realized after you commented on the pull request that there already is a meson build, and I'm just blind!  Haha this is is what I get for trying to do this stuff after a week at work. Anyway I tested it out on my machine and the meson build is smart enough to deal with my setup.
