### ISSUE TITLE
Building Chris Branch Binary?

### ISSUE THREAD

**Issue by jsl303** [jacktrip/jacktrip#107]
Is there a binary release for Chris branch?
I was able to built my own on Mac with qt from brew install qt.
However, if I give the binary to someone else, it complains it can't find dylib.
I assume because qt library is not incorporated into the binary?
If there's no released binary, Is there an instruction on how to build Chris branch as a standalone binary so I can give to someone else?
I'm very interested in Chris branch for hub function to let multiple clients to connect and distribute among the clients.

**Comment by wholenotes** [comment]
Chris did make a couple of significant changes to hub servers, but we merged those into master a while ago.  Run the build script in the src directory on master.

**Comment by jsl303** [comment]
Awesome, I built the latest master branch. However my binary doesn't seem to be static. If I give the built binary to someone else, it complains it can't find dylib.
I have my qt installed with brew install qt5.
Do I need to compile my own static qt to make this happen?
Any other method to make it distributable without them installing QT on their macs?

**Comment by wholenotes** [comment]
I've always asked people to build from source, which is why I've tried to give more detailed instructions to make it easier.

**Comment by psiborg112** [comment]
Yeah, the only way I've managed this in the past is to compile a static 
version of Qt. (It's been a while, but I'm pretty sure I used this guide 
here: https://retifrav.github.io/blog/2018/02/17/build-qt-statically/) 
You'll need to make sure the build script uses qmake from your own 
static build of qt, and add "CONFIG += static" to the jacktrip.pro file.
Aaron

**Comment by wholenotes** [comment]
Cool!  @jsl303, if you make one that works, do share it!

**Comment by chigkim** [comment]
I built the master branch on my win 10 (v2004) and MacOS 10.15.6.
I haven't tested on other machines, but hopefully they work!

[jacktrip-master-win.zip](https://github.com/jacktrip/jacktrip/files/5029259/jacktrip-master-win.zip)

[jacktrip-master-mac.zip](https://github.com/jacktrip/jacktrip/files/5029260/jacktrip-master-mac.zip)
