### ISSUE TITLE
source tarballs do not build

### ISSUE THREAD

**Issue by umlaeute** [jacktrip/jacktrip#1079]
as of Jacktrip-1.10.0, it is impossible to build from the released sources:

```
FAILED: jacktrip.p/meson-generated_moc_Analyzer.cpp.o 
ccache c++ -Ijacktrip.p -I. -I../../.. -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c++17 -g -O2 -ffile-prefix-map=/build/jacktrip-jqMWIe/jacktrip-1.10.0+ds=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DQT_NETWORK_LIB -isystem/usr/include/x86_64-linux-gnu/qt5/QtNetwork -DQT_CORE_LIB -isystem/usr/include/x86_64-linux-gnu/qt5/QtCore -isystem/usr/include/x86_64-linux-gnu/qt5 -fPIC -pthread -DWAIRTOHUB -DNO_GUI -DQT_OPENSOURCE -MD -MQ jacktrip.p/meson-generated_moc_Analyzer.cpp.o -MF jacktrip.p/meson-generated_moc_Analyzer.cpp.o.d -o jacktrip.p/meson-generated_moc_Analyzer.cpp.o -c jacktrip.p/moc_Analyzer.cpp
In file included from jacktrip.p/moc_Analyzer.cpp:10:
jacktrip.p/../../../../src/Analyzer.h:49:10: fatal error: externals/Simple-FFT/include/simple_fft/fft.h: No such file or directory
   49 | #include "externals/Simple-FFT/include/simple_fft/fft.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

that's obviously, because the `externals/Simple-FFT/` directory is empty (as it is a *git submodule*, and the automatically generated source tarballs that GitHub offers do not include any submodules).
it would be great if you could provide a way so we can compile JackTrip from the source tarballs (or some other downloadable artifact) associated with a release.

this is a common problem with *git submodule*s (and one of the reasons i dislike them).
- see https://github.com/obsproject/obs-studio/issues/7407
- see also `git subtree`

(note: i *might* consider packaging Simple-FFT for Debian; but if I do so, I would probably go with upstream (https://github.com/d1vanov/Simple-FFT), so any changes you do to it in your local copy, would be lost.)

**Comment by dvzrv** [comment]
Came here to say the same (for Arch Linux).
Given that [Simple-FFT](https://github.com/d1vanov/Simple-FFT) has never seen a release and has been last touched three years ago does not give me that fuzzy feeling in my belly though.

**Comment by ntonnaett** [comment]
@mikedickey @dhing1024 @mattahorton @nwang92 I didn't really look at Simple-FFT when the PR was made, but unmaintained and an API that is prone to memory bugs doesn't look good. Could we please switch to a mature and common FFT implementation?

**Comment by dvzrv** [comment]
Is there any decision being made on this? I think I'd rather abstain from packaging something like simple-fft. This currently blocks updating to anything > 1.9 though

**Comment by dvzrv** [comment]
Meanwhile no feedback on this topic blocks me further from upgrading rtaudio to 6 on Arch Linux, as https://github.com/jacktrip/jacktrip/pull/1118 does not apply cleanly on top of 1.9.0.

**Comment by psiborg112** [comment]
Seconding what @ntonnaett said. Especially since this isn't for a core feature: unless I've missed something it's still just being used for feedback loop detection in the Virtual Studio side of things, right? VS people, if we really must use this library, can there be a preprocessor option to disable the feedback loop detection so that it doesn't hold other things up?

**Comment by mikedickey** [comment]
Related https://github.com/jacktrip/jacktrip/issues/508

**Comment by dvzrv** [comment]
@mikedickey: The tarball for 1.10.1 actually still has this problem. Why was the change not included for that patch level release?
