### ISSUE TITLE
GUI weirdness

### ISSUE THREAD

**Issue by umlaeute** [jacktrip/jacktrip#1081]
sorry for the vague title, but that's the best I can come up with.

firing up the GUI doesn't look proper:

![jacktrip](https://github.com/jacktrip/jacktrip/assets/214034/8ea70fe9-873b-4dcc-88fe-74267a620d38)

- buttons are inverted (they look *sunken* rather than *raised*)
- elements are not shown completely
   - text at the bottom of the window (`JackTrip version 1.10.0` and `Auto queue: enable`)
   - buttons (e.g. text for `Virtual Studio Mode`)
   - tab (e.g. right side of `Scripting`)
   - virtually everything (pull downs, dials,...)

I've tested both with a self-compiled binary and your release asset [JackTrip-v1.10.0-Linux-x64-binary.zip](https://github.com/jacktrip/jacktrip/releases/download/v1.10.0/JackTrip-v1.10.0-Linux-x64-binary.zip) with basically the same result (some artifacts look slightly different, but overall they are the same).

since the binary from the release asset does not dylink to Qt, i think we can rule out a problem with my Qt installation (also: I haven't noticed anything weird with other applications)

**Comment by ntonnaett** [comment]
@psiborg112 Might this be related to your last change to qjacktrip.ui?

**Comment by psiborg112** [comment]
It seems super unlikely. There's nothing that looks untoward in the changes to the .ui file, especially nothing that should be causing the widgets to be misjudging the size of the window. I assume you're building on Debian @umlaeute? I'm definitely not seeing this on my main dev machine which is running Debian Sid. (Admittedly I'm building with cmake and Qt6. I'm away from home for the next few days and only have my macbook on me, but will see if I can recreate it when I get home. Will keep you posted.)

**Comment by psiborg112** [comment]
(Also in case it matters, I'm running KDE on X11. Also haven't noticed any issues on my other Debian machine running XFCE on X11.)

**Comment by psiborg112** [comment]
I guess if you wanted to test it out sooner, you could revert the .ui file to the previous version and comment out line 362-369 (inclusive) in qjacktrip.cpp.

**Comment by umlaeute** [comment]
just to add my data:
| key | value |
|---|---|
|OS | Debian/Sid
| window manager | X11/Xfce4
| buildsystem | meson
| toolkit | Qt5

as there is no

**Comment by OConnorStP** [comment]
This may be irrelevant (my typical cluelessness) but I just dropped the 1.10.0 binary from GitHub on a Deb12 Linode and the GUI looks fine.  

For fun, I also did an APT install of jacktrip-gui to see what would get installed on Deb12 and got version 1.7.0.  That seems a little out of date.  Also looks good, although the desktop icon didn't appear.

**Comment by umlaeute** [comment]
for what it is worth, on my laptop (again Debian/sid, X11/Xfce4,...) the Debian packages look fine. it's probably just that particular machine that has the problems (though i don't recall any other problems).
so i'm closing this.

@OConnorStP re "1.7.0 a little out of date": no not really. Debian12 went into freeze by the end of january 2023, and JackTrip-1.7.1 was released on Feb, 3. "freeze" means :ice_cube: freeze, and package updates are allowed.
eventually i will upload Jacktrip-1.10 to bookworm-backports (and the ubuntu ppas), but for the former the policy is that the same version must already be available in Debian/testing (and it will take another 3 days to migrate there), and for the latter my personal policy is the same.
