### ISSUE TITLE
`jackd` error: Cannot connect ports owned by inactive clients: "JackTrip" is not active

### ISSUE THREAD

**Issue by alexdewar** [jacktrip/jacktrip#1084]
For some reason, when I call `jack_connect` after starting `jackd2` and `jacktrip`, I get the following error:

```
Cannot connect ports owned by inactive clients: "JackTrip" is not active
```

Any ideas?

**Comment by SynthiaPayne** [comment]
Hi Alex,

I have an idea, and maybe you already know this: if you want to connect JackTrip, you call JackTrip, not Jack. They are two separate programs. The latest JackTrip manual is attached and has a list of commands. Let us know if that helps.

Synthia

[JackTrip Manual V.1.10.0.txt](https://github.com/jacktrip/jacktrip/files/11821991/JackTrip.Manual.V.1.10.0.txt)

**Comment by ntonnaett** [comment]
It seems more like jacktrip opened a jack client but didn't activated it yet. Maybe it's the audio setup jack client…

**Comment by psiborg112** [comment]
It would be useful to see what your connection graph window looks like.
