### ISSUE TITLE
both GUIs -- Audio Backend : JACK -- need to allow Buffer Size and Sampling Rate selection

### ISSUE THREAD

**Issue by cchafe** [jacktrip/jacktrip#1089]
When in JACK mode neither of these audio parameters are available 
With the CLI no problem, bufsize can be set, same for srate
but the GUIs only expose the drop-down menus when in RtAudio mode

Here's an example CLI incantation to adjust FPP (1.10.0 tested with JACK under Pipewire)
`./jacktrip -C <a server at FPP 128> --bufstrategy 3 -q auto3 --udprt  --bufsize 128`

**Comment by OConnorStP** [comment]
Isn't that because the GUI isn't touching Jack?  BecauseJack is being managed independently (probably with Qjackctl)?  It would be lovely if the GUI could manage Jack directly, as Qjackctl and Jack have gotten a little weird recently, but I wasn't aware that was an option.

**Comment by cchafe** [comment]
On Pipewire systems there's no need to start jack. And better yet, JackTrip now has the ability to set the environment variable "PIPEWIRE_LATENCY" which is the equivalent of using Qjackctl to set FPP. The issue here is that if JackTrip doesn't change that variable, then you have to do it manually otherwise you get the default of 1024. On Pipewire systems Qjackctl is still useful for patching (for example, firefox or zoom sound to JackTrip) and there are multiple applications out there for changing the graph, besides Qjackctl.

**Comment by OConnorStP** [comment]
so... if a fella isn't running on a Pipewire system, would those dropdown menus work with Jack?  or will JackTrip have to sense whether it's talking to Jack or Pipewire.  Deb12 doesn't load Pipewire by default, might those dropdowns be a bridge to nowhere for them?

**Comment by cchafe** [comment]
JackTrip's implementation uses calls which would be ignored by any backend other than Pipewire.  Give this a try on a non-Pipewire, JACK system 
`PIPEWIRE_LATENCY=128/48000 jacktrip -C <a server at FPP 128> --bufstrategy 3 -q auto3 --udprt`
That's the manual version of setting the environment variable and should be ignored in the non-Pipewire case
BTW, kudos to the Fedora JackTrip package maintainers -- 1.10.0 is now in updates and thus the different invocation from above (jacktrip instead of ./jacktrip)!

**Comment by cchafe** [comment]
2.0.0-beta1 fixes this using VS GUI, but not when using classic

**Comment by cchafe** [comment]
2.0.0-beta2 fixes this for classic, too
