### ISSUE TITLE
2.0.0-beta1 doesn't install man/man1/jacktrip.1.gz

### ISSUE THREAD

**Issue by yurivict** [jacktrip/jacktrip#1132]
1.x did install it, but it disappeared in 2.x

**Comment by ntonnaett** [comment]
Did you install help2man and are using Meson?

**Comment by yurivict** [comment]
```help2man``` is available:
```
$ which help2man
/usr/local/bin/help2man
```

meson is used.

man/man1/jacktrip.1.gz isn't installed.

**Comment by ntonnaett** [comment]
It seems we never compressed the manpage when building. We probably should. RPM does this automatically: https://docs.fedoraproject.org/en-US/packaging-guidelines/#_manpages

**Comment by yurivict** [comment]
It doesn't get installed either, even uncompressed.

**Comment by ntonnaett** [comment]
Does it show up in your build directory?

**Comment by yurivict** [comment]
> Does it show up in your build directory?

No.
