### ISSUE TITLE
2.0.0-beta2 doesn't always remember GUI setting after quitting

### ISSUE THREAD

**Issue by cchafe** [jacktrip/jacktrip#1161]
Seems to be an "every other time" occurrence. 
2.0.0-beta2 linux GUI asset tested on F38.
Run in classic mode, run then quit jacktrip. Relaunch.
Every other time, it will launch in VS mode instead of classic

**Comment by mikedickey** [comment]
It looks like this is a side-effect of running both interfaces in parallel, rather than having them cleanly separated. I'm working on a fix.

**Comment by cchafe** [comment]
Fixed, thanks!
