### ISSUE TITLE
fix to make network packet sizes and local buffersize agree

### ISSUE THREAD

**Issue by cchafe** [jacktrip/jacktrip#1174]
taking advantage of recent improvements in specifying rtaudio buffersize
(and currently running v2.0.0-beta2-47-g485799f7-485799f7)
on linux / pipewire

with a server running at FPP 64
client connects with -F64 --rtaudio
the network packet sizes match but local rtaudio buffersize is still at 128
 
inserting this after line 279 allows local audio buffersize to be set to 64
`   mRtAudio.reset(new RtAudio(RtAudio::getCompiledApiByName("alsa")));
`
this revisits #923 (but changes it to use the reset method)

**Comment by cchafe** [comment]
I'm not sure of the best way to do this without affecting other configurations, which is why it's not a PR

**Comment by cchafe** [comment]
bump
RtAudioInterface.cpp still requires this manual patch in
JackTrip VERSION: 2.0.1
Build Info: v2.0.0-beta2-63-g2bea5517-2bea5517
I'm still vague about the best way -- is there a better way than just surrounding it with a 
#ifndef _WIN32
(that would do the job for win, but how about other linices and macOS?)

**Comment by mikedickey** [comment]
I'm not sure that change is right either. I think that basically would only allow you to find devices available that use the alsa backend. By default, RtAudio is allowing you to use any of the device/backends that it supports.

I do suspect we have a build flag problem, though with CI. When I use a build created via GitHub CI, ``jacktrip --listdevices` shows:

```
RTAudio: scanning devices...
[Pulse - 129]: "Built-in Audio" (2 ins, 2 outs)
[Pulse - 130]: "AudioBox Go" (2 ins, 2 outs)
```

But when I use a build compiled locally on my machine, it shows:

```
RTAudio: scanning devices...
[Pulse - 0]: "Built-in Audio" (2 ins, 2 outs)
[Pulse - 1]: "AudioBox Go" (2 ins, 2 outs)
[ALSA - 0]: "default" (64 ins, 64 outs)
[ALSA - 1]: "hw:HDA Intel PCH,0" (2 ins, 2 outs)
[ALSA - 2]: "hw:HDA Intel PCH,3" (0 ins, 8 outs)
[ALSA - 3]: "hw:HDA Intel PCH,7" (0 ins, 8 outs)
[ALSA - 4]: "hw:HDA Intel PCH,8" (0 ins, 8 outs)
[ALSA - 5]: "hw:HDA Intel PCH,9" (0 ins, 8 outs)
[ALSA - 6]: "hw:AudioBox Go,0" (2 ins, 2 outs)
```

So if we're built with support for both Pulse and ALSA backends, it shows all the ALSA devices as "hw.*" and if I select that I get much better latency results than going through Pulse.

I imagine it's an easy fix. But it does make me wonder if we should even support the Pulse backend, considering it seems to perform so poorly? I don't know enough about Linux audio to have much of an opinion..

**Comment by mikedickey** [comment]
Not sure if this solves it, but I think it should help https://github.com/jacktrip/jacktrip/pull/1189

**Comment by cchafe** [comment]
I've been building from src (and have the ALSA libs locally). Looks like https://github.com/jacktrip/jacktrip/pull/1189 should create the same build environment as what I've got.
The manual patch to jacktrip/src/RtAudioInterface.cpp is still needed until we figure out the right way to add this alongside all the other OS targets.
Here's the patch file
[RtAudio-pipewire-ALSA.patch.zip](https://github.com/jacktrip/jacktrip/files/12499866/RtAudio-pipewire-ALSA.patch.zip)

**Comment by mikedickey** [comment]
@cchafe what does it show if you run `jacktrip --listdevices` ?

**Comment by cchafe** [comment]
[cc@fedora builddir]$ ./jacktrip --listdevices
RTAudio: scanning devices...
[Jack - 0]: "Built-in Audio Analog Stereo" (4 ins, 2 outs)
[Jack - 1]: "speech-dispatcher-dummy" (2 ins, 0 outs)
[Jack - 2]: "Built-in Audio Analog Stereo" (4 ins, 2 outs)
[Pulse - 0]: "Built-in Audio" (2 ins, 2 outs)
[ALSA - 0]: "default" (64 ins, 64 outs)
[ALSA - 1]: "hw:HDA Intel PCH,0" (2 ins, 4 outs)
[ALSA - 2]: "hw:HDA Intel PCH,3" (0 ins, 8 outs)
[ALSA - 3]: "hw:HDA Intel PCH,7" (0 ins, 8 outs)
[ALSA - 4]: "hw:HDA Intel PCH,8" (0 ins, 8 outs)
[ALSA - 5]: "hw:HDA NVidia,3" (0 ins, 8 outs)
[ALSA - 6]: "hw:HDA NVidia,7" (0 ins, 8 outs)
[ALSA - 7]: "hw:HDA NVidia,8" (0 ins, 8 outs)
[ALSA - 8]: "hw:HDA NVidia,9" (0 ins, 8 outs)
[cc@fedora builddir]$

**Comment by mikedickey** [comment]
Which device are you selecting inside of JackTrip? Unless I'm missing something, if you pick one of the ALSA devices it should be exactly the same thing because line 177 should already initialize it to use the ALSA backend.

I think your patch would break every other platform, or anyone trying to use a device outside of ALSA.

**Comment by cchafe** [comment]
That's the answer to this and it works with no mods.
For a desired FPP of **64** to show in pw-top I can get 
(FPP **64**)  by selecting [ALSA - 0]: "**default**" (64 ins, 64 outs)
(FPP **128**) results from using [Pulse - 0]: "**Built-in Audio**" (2 ins, 2 outs)
(FPP **64**) if patched as described [Pulse - 0]: "**Built-in Audio**" (2 ins, 2 outs)
(FPP **1024**) and do avoid [Jack - 0]: "**Built-in Audio Analog Stereo**" (4 ins, 2 outs)
