### ISSUE TITLE
cannot build project without git installed

### ISSUE THREAD

**Issue by umlaeute** [jacktrip/jacktrip#1184]
i downloaded the soources of the latest and greatest release of jacktrip, installed all the dependencies, but building fails:

```
$ meson setup ../../.. --wrap-mode=nodownload --buildtype=plain --prefix=/usr --sysconfdir=/etc --localstatedir=/var --libdir=lib/x86_64-linux-gnu -Dpython.bytecompile=-1 -Djack=enabled -Dqtversion=6 -Dnogui=true -Drtaudio=disabled
[...]
C++ compiler for the build machine: ccache c++ (gcc 13.2.0 "c++ (Debian 13.2.0-2) 13.2.0")
C++ linker for the build machine: c++ ld.bfd 2.41
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64

../../../meson.build:39:15: ERROR: Program or command 'git' not found or not executable
```

i'm aware that the [documentation](https://github.com/jacktrip/jacktrip/blob/main/docs/Build/Linux.md#ubuntu-and-debianraspbian-qt6) tells me to install `git`, but i don't really see a reason.

meson uses `git` to inject some very optional preprocessor flags https://github.com/jacktrip/jacktrip/blob/75df4267a3f5859c4824dca7d52cac8c10a76366/meson.build#L39-L45 *iff* it detects that we are building jacktrip from a git repository (if it detects that we are not building from a git repository, nothing happens).

since i am not building from a git-repository, there is little use in forcing a `git` installation.

i suggest to handle a missing `git` binary gracefully (the same as if there was a `git` binary that detects that we are not building from a git repository)

**Comment by umlaeute** [comment]
something like the following should do the trick:

```diff
Index: jacktrip-2.0.1+ds/meson.build
===================================================================
--- jacktrip-2.0.1+ds.orig/meson.build
+++ jacktrip-2.0.1+ds/meson.build
@@ -36,12 +36,15 @@ if get_option('buildtype') == 'release'
 	c_defines += ['-DNDEBUG']
 endif
 
-git_tags_cmd = run_command('git', 'describe', '--tags', check: false)
-git_hash_cmd = run_command('git', 'rev-parse', '--short', 'HEAD', check: false)
-if git_tags_cmd.returncode() == 0 and git_hash_cmd.returncode() == 0
+git = find_program('git', required: false)
+if git.found()
+  git_tags_cmd = run_command(git, 'describe', '--tags', check: false)
+  git_hash_cmd = run_command(git, 'rev-parse', '--short', 'HEAD', check: false)
+  if git_tags_cmd.returncode() == 0 and git_hash_cmd.returncode() == 0
 	git_tags = git_tags_cmd.stdout().strip()
 	git_hash = git_hash_cmd.stdout().strip()
 	defines += ['-DJACKTRIP_BUILD_INFO=' + git_tags + '-' + git_hash]
+  endif
 endif
 
 src = [	'src/DataProtocol.cpp',
```

it would probably *also* be nice to pass the JACK_BUILD_INFO manually, completely bypassing the `git` check.

**Comment by mikedickey** [comment]
Thanks for the patches @umlaeute! I'm fairly new to meson, and had assumed that `check: false` wouldn't fail if the command wasn't available.
