### ISSUE TITLE
GUI blank after enabling VirtualStudio

### ISSUE THREAD

**Issue by umlaeute** [jacktrip/jacktrip#1197]
this started with my Debian packages (of Jacktrip-2.0.1):
- start jacktrip (GUI) - everything looks nice
- click on the <kbd>Virtual Studio</kbd> button
- the GUI gets blank, like so:
![jacktrip](https://github.com/jacktrip/jacktrip/assets/214034/68c83070-6bad-44ab-9076-68ad65320a65)

the really bad thing is that i cannot revert this: closing jacktrip and starting anew gives me the same blank window.

this happened on two different machines running Debian/sid.

i've then downloaded [your Linux/amd64 binaries](https://github.com/jacktrip/jacktrip/releases/download/v2.0.2/JackTrip-v2.0.2-Linux-x64-binary.zip) but again, no GUI is displayed.

**Comment by umlaeute** [comment]
i've also removed the `~/.local/share/jacktrip/` and `~/.config/jacktrip/` folders, but to not avail.

**Comment by umlaeute** [comment]
in the end i've tried building the Jacktrip-2.0.2 Debian packages *without* Virtual Studio support (`-Dnovs=yes`), and lo and behold! the GUI is back.

i've then rebuild the Jacktrip-2.0.1 Debian packages without Virtual Studio support, and the GUI is back as well.


So it appears that the Virtual Studio mode is to blame.

btw, I also get the following on the stderr:


```sh
$ jacktrip
Listening for deep link requests
qrc:/vs/vs.qml:2:1: module "QtQuick.Controls" plugin "qtquickcontrols2plugin" not found 
     import QtQuick.Controls 
     ^
SSL Library:  "OpenSSL 3.0.10 1 Aug 2023"
Log file location: "/home/zmoelnig/.local/share/jacktrip/JackTrip/log.txt"
```

i don't get this when running the novs versions (that work):

```sh
$ jacktrip
RTAudio: scanning devices...
[Jack - 0]: "Tiger Lake-LP Smart Sound Technology Audio Controller Digital Microphone" (2 ins, 0 outs)
[Jack - 1]: "Tiger Lake-LP Smart Sound Technology Audio Controller Headphones Stereo Microphone" (2 ins, 0 outs)
[Jack - 2]: "speech-dispatcher-dummy" (2 ins, 0 outs)

RtApiJack::getDeviceInfo: error determining Jack input/output channels!

[Jack - 4]: "Tiger Lake-LP Smart Sound Technology Audio Controller HDMI / DisplayPort 1 Output" (2 ins, 2 outs)
[Jack - 5]: "Tiger Lake-LP Smart Sound Technology Audio Controller HDMI / DisplayPort 2 Output" (2 ins, 2 outs)
[Jack - 6]: "Tiger Lake-LP Smart Sound Technology Audio Controller HDMI / DisplayPort 3 Output" (2 ins, 2 outs)
[Pulse - 0]: "Tiger Lake-LP Smart Sound Technology Audio Controller" (2 ins, 2 outs)
[ALSA - 0]: "default" (64 ins, 64 outs)
[ALSA - 1]: "hw:sof-hda-dsp,0" (2 ins, 2 outs)
[ALSA - 2]: "hw:sof-hda-dsp,3" (0 ins, 2 outs)
[ALSA - 3]: "hw:sof-hda-dsp,4" (0 ins, 2 outs)
[ALSA - 4]: "hw:sof-hda-dsp,5" (0 ins, 2 outs)
[ALSA - 5]: "hw:sof-hda-dsp,6" (2 ins, 0 outs)
[ALSA - 6]: "hw:sof-hda-dsp,7" (2 ins, 0 outs)
[ALSA - 7]: "hw:sof-hda-dsp,31" (0 ins, 2 outs)
RTAudio: scanning devices...
[Jack - 0]: "Tiger Lake-LP Smart Sound Technology Audio Controller Digital Microphone" (2 ins, 0 outs)
[Jack - 1]: "Tiger Lake-LP Smart Sound Technology Audio Controller Headphones Stereo Microphone" (2 ins, 0 outs)
[Jack - 2]: "speech-dispatcher-dummy" (2 ins, 0 outs)

RtApiJack::getDeviceInfo: error determining Jack input/output channels!

[Jack - 4]: "Tiger Lake-LP Smart Sound Technology Audio Controller HDMI / DisplayPort 1 Output" (2 ins, 2 outs)
[Jack - 5]: "Tiger Lake-LP Smart Sound Technology Audio Controller HDMI / DisplayPort 2 Output" (2 ins, 2 outs)
[Jack - 6]: "Tiger Lake-LP Smart Sound Technology Audio Controller HDMI / DisplayPort 3 Output" (2 ins, 2 outs)
[Pulse - 0]: "Tiger Lake-LP Smart Sound Technology Audio Controller" (2 ins, 2 outs)
[ALSA - 0]: "default" (64 ins, 64 outs)
[ALSA - 1]: "hw:sof-hda-dsp,0" (2 ins, 2 outs)
[ALSA - 2]: "hw:sof-hda-dsp,3" (0 ins, 2 outs)
[ALSA - 3]: "hw:sof-hda-dsp,4" (0 ins, 2 outs)
[ALSA - 4]: "hw:sof-hda-dsp,5" (0 ins, 2 outs)
[ALSA - 5]: "hw:sof-hda-dsp,6" (2 ins, 0 outs)
[ALSA - 6]: "hw:sof-hda-dsp,7" (2 ins, 0 outs)
[ALSA - 7]: "hw:sof-hda-dsp,31" (0 ins, 2 outs)
```

**Comment by mikedickey** [comment]
Hi @umlaeute, I believe that is due to missing package requirements. Please see [README.md](https://github.com/jacktrip/jacktrip/blob/main/linux/README.md).

Here is the line I think you need for Debian dependencies:

```
apt install -y libqt6core6 libqt6gui6 libqt6network6 libqt6widgets6 libqt6qml6 libqt6qmlcore6 libqt6quick6 libqt6quickcontrols2-6 libqt6svg6  libqt6webchannel6 libqt6webengine6-data libqt6webenginecore6 libqt6webenginecore6-bin libqt6webenginequick6 libqt6websockets6 qt6-qpa-plugins qml6-module-qtquick-controls qml6-module-qtqml-workerscript qml6-module-qtquick-templates qml6-module-qtquick-layouts qml6-module-qt5compat-graphicaleffects qml6-module-qtwebchannel qml6-module-qtwebengine
```

**Comment by umlaeute** [comment]
So are you trying to say, that the official jacktrip binaries (as downloaded from the release page here on GitHub) are lacking these dependencies as well?

There probably needs to be a runtime check...

**Comment by mikedickey** [comment]
Yes, the "official binaries" rely upon Qt6, and these are all the packages that provide Qt6 on Debian. All software has external dependencies, and these are not always included by default on Linux since it lets you pick and choose which packages you want at installation time.

**Comment by umlaeute** [comment]
I'm currently afk, so I can only answer without actually trying out anything...

Typically Debian does a very good job at finding out runtime dependencies when creating binary packages (this obviously does not apply to the "official releases" as this information is embedded in the .deb file, but it should kick in for my Debian packages.) Any idea why it does not?

In any case I think that there ought to be some runtime guards in place if the screen cannot be rendered.
It's really breaking jacktrip *forever* on the user's machine if they accidentally hit a button once and then get a blank screen afterwards (even after wiping all the preferences and rebooting and whatnot).

It would *also* be nice to be able to select the mode of operation ("normal" vs " virtual studio") via cmdline flags

**Comment by umlaeute** [comment]
back at the keyboard, i've installed all dependencies as you suggested with

```sh
apt install libqt6core6 libqt6gui6 libqt6network6 libqt6widgets6 libqt6qml6 libqt6qmlcore6 libqt6quick6 libqt6quickcontrols2-6 libqt6svg6  libqt6webchannel6 libqt6webengine6-data libqt6webenginecore6 libqt6webenginecore6-bin libqt6webenginequick6 libqt6websockets6 qt6-qpa-plugins qml6-module-qtquick-controls qml6-module-qtqml-workerscript qml6-module-qtquick-templates qml6-module-qtquick-layouts qml6-module-qt5compat-graphicaleffects qml6-module-qtwebchannel qml6-module-qtwebengin
```

then downloaded the [Linux/x86_64 official release binary](https://github.com/jacktrip/jacktrip/releases/download/v2.0.2/JackTrip-v2.0.2-Linux-x64-binary.zip).

Starting the application i was greeted with this ![empty jacktrip window](https://user-images.githubusercontent.com/214034/265828334-68c83070-6bad-44ab-9076-68ad65320a65.png)

On the console, the following was printed:
```
Listening for deep link requests
qrc:/vs/vs.qml:179:5: Type Setup unavailable 
         Setup { 
         ^
qrc:/vs/Setup.qml:65:9: Type AudioSettings unavailable 
             AudioSettings { 
             ^
qrc:/vs/AudioSettings.qml:118:13: Type InfoTooltip unavailable 
                 InfoTooltip { 
                 ^
qrc:/vs/InfoTooltip.qml:55:31: Type Glow unavailable 
                     layer.effect: Glow { 
                                   ^
qrc:/qt-project.org/imports/Qt5Compat/GraphicalEffects/Glow.qml:35:5: Type DropShadowBase unavailable 
         DropShadowBase { 
         ^
qrc:/qt-project.org/imports/Qt5Compat/GraphicalEffects/private/DropShadowBase.qml:21:5: Type GaussianBlur unavailable 
         GaussianBlur { 
         ^
qrc:/qt-project.org/imports/Qt5Compat/GraphicalEffects/GaussianBlur.qml:6:1: module "QtQuick.Window" is not installed 
     import QtQuick.Window 
     ^
SSL Library:  "OpenSSL 3.0.11 19 Sep 2023"
Log file location: "/home/zmoelnig/.local/share/jacktrip/JackTrip/log.txt"
```

the file `/home/zmoelnig/.local/share/jacktrip/JackTrip/log.txt` is empty.


So the dependencies as listed  in the README, are **not** the solution to my problem.

**Comment by umlaeute** [comment]
it turns out that the missing dependency was `qml6-module-qtquick-window`.

probably this is a missing dependency of the `qml6-module-qt5compat-graphicaleffects` package, see  https://bugs.debian.org/1052612

~~you might want to~~ i think you should do all of the following:
- update your README
- check if it is possible to do a runtime detection of missing QMLs
- provide a cmdline flag to start jacktrip in "Classic" mode

**Comment by mikedickey** [comment]
All good suggestions, @umlaeute. Turned out to be a bit more work than I thought, but this should cover everything https://github.com/jacktrip/jacktrip/pull/1211
