### ISSUE TITLE
Invalid escape sequence in org.jacktrip.JackTrip.desktop

### ISSUE THREAD

**Issue by kjcole** [jacktrip/jacktrip#1202]
While installing the latest version of REAPER, I got two complaints about JackTrip:

```
kf.config.core: "KConfigIni: In file ~/.local/share/applications/org.jacktrip.JackTrip.desktop, line 6: " "Invalid escape sequence \"\\$\"."
kf.config.core: "KConfigIni: In file ~/.local/share/applications/org.jacktrip.JackTrip.desktop, line 6: " "Invalid escape sequence \"\\$\"."
```

one for each occurrence of `""\$"1"` in the line:

 ```
Exec=/bin/bash -c "if [ -z ""\$"1" ]; then jacktrip; else jacktrip --gui --deeplink ""\$"1"; fi" /bin/bash %u
```

**Comment by mikedickey** [comment]
Hi @kjcole , would you give this a try? https://github.com/jacktrip/jacktrip/pull/1203

I'm not sure why it is escaped the way it is. If this doesn't work, do you know of an easy way to repro those KConfigIni errors? IDK what that is.

**Comment by kjcole** [comment]
Your escape sequence looks considerably saner than what was there. However, in attempting to determine what produced the error by searching the web, I find several cases where the uglier escape sequence seems rather common. I am unable to determine what was run to produce the error in the first place.  When I check either version of the file using `desktop-file-validate` neither one produces an error. So, I'm going to write this off as a "false alarm" -- or at least it's not a JackTrip issue.

(I may try uninstalling and reinstalling the application that complained to see if it complains with the edited desktop file.)

**Comment by umlaeute** [comment]
see also #802: i have the gut feeling that the `Exec` entry in the desktop file is needlessly complicated

**Comment by mikedickey** [comment]
I updated parsing of deeplinks in https://github.com/jacktrip/jacktrip/pull/1203, eliminating the need for any of the bash stuff in the desktop file.
