### ISSUE TITLE
jacktrip's jack client name becomes garbage unicode in version 1.2.1, but worked on 1.2

### ISSUE THREAD

**Issue by ericfont** [jacktrip/jacktrip#121]
I'm on arch linux (5.6.17-rt10-1-rt x86-64 running jack 1.9.14).  The latest jacktrip release 1.2.1 (arch's official repo build) produces a glitchy jack port name when using client mode, for instance:

`jacktrip -n 1 -c subdomain.domain.org`

will result in a funny jack client name for the jacktrip instance, jack_lsp says it is: ` ���U:send_1`.

However, running previous release 1.2 (also on arch's official repo build) produces that name correctly: `subdomain.domain.org`

I've downloaded the git and am running the latest development build int the debuger, and what I find is that the JackAudioInterface.client_name is corrupt prior to executing the following line, at which point after the client_name becomes corrupted/garbage:

https://github.com/jacktrip/jacktrip/blob/7c56a083f601aeffceec9e1f390bf592a24d0200/src/JackAudioInterface.cpp#L118

I dug more deeper with the debugger into jack2's sourcecode and found the exact moment of erasure of client_name to happen with:

https://github.com/jackaudio/jack2/blob/34fb7b6963864380cf1ab48fe575faed62afd2f0/common/JackLibGlobals.h#L73

Here is the stack trace at that moment:

1  Jack::JackLibGlobals::JackLibGlobals JackLibGlobals.h       74  0x7ffff7fabb8c 
2  Jack::JackLibGlobals::Init           JackLibGlobals.h       65  0x7ffff7fabb8c 
3  jack_client_open_aux                 JackLibAPI.cpp         151 0x7ffff7fab072 
4  jack_client_open                     JackLibAPI.cpp         186 0x7ffff7fab072 
5  JackAudioInterface::setupClient      JackAudioInterface.cpp 118 0x555555576839 
6  JackAudioInterface::setup            JackAudioInterface.cpp 96  0x5555555769e9 
7  JackTrip::setupAudio                 JackTrip.cpp           172 0x55555556476c 
8  JackTrip::startProcess               JackTrip.cpp           347 0x55555556710d 
9  Settings::startJackTrip              Settings.cpp           598 0x55555556fbcc 
10 main                                 jacktrip_main.cpp      97  0x55555555f9b1

**Comment by ericfont** [comment]
Should be noted that the jacktrip instance still works, despite the garbage name of the jacktrip client instance.  The main problem  is that it is hard for me to connect ports to the jacktrip instance via catia (which crashes cause the garabe unicode messes it up!)

I would also note that the behavior with using ip address instead of domain name is not as bad than with using a domain name, but still less than ideal.  What happens with using `8.8.8.8` for instance is that the jacktrip instance is named very non-descriptively as `1` in 1.2.1, while in 1.2 the full ip address was provided in the name.

I consider this a regression, as I like the 1.2 behavior much better.

**Comment by ericfont** [comment]
The specific commit which seems to have broke this is https://github.com/jacktrip/jacktrip/commit/adf3d7b70a678db826792fabc9719e6f1973c75f

**Comment by ericfont** [comment]
I'm very confused, because that commit doesn't seem to make any changes to the compiled code.  Though the previous commit https://github.com/jacktrip/jacktrip/commit/3fec579658608d38da0588f748300e1c82cbe268 does work, so somehow it did mess it up.

**Comment by ericfont** [comment]
The commit that seems to have broken it is: https://github.com/jacktrip/jacktrip/commit/a21cae5cd08f1e558e33eac073a0243fc1ce22de

**Comment by ericfont** [comment]
That commit addressed issue #73, which also seems to be related to issue #102

**Comment by ericfont** [comment]
Somehow if I do the following:

@@ -158,9 +158,10 @@ void JackTrip::setupAudio(
 
 #ifdef WAIRTOHUB // WAIR
         //Set our Jack client name if we're a hub server or a custom name hasn't been set
+        QByteArray tmp = QString(mPeerAddress).replace(":", ".").toLatin1();
              if ( mPeerAddress.toStdString() != "" &&
                  (mJackClientName == gJackDefaultClientName || mJackTripMode == SERVERPINGSERVER)) {
-            mJackClientName = QString(mPeerAddress).replace(":", ".").toLatin1().constData();
+            mJackClientName = tmp.constData();


Then it works correctly...the name is preservered.

What I'm thinking the problem has to do with is because mJackClientName is a const char pointer.  And somehow in that moment when jack_client_open() gets called, there is something that changes with the shared memory that causes the data inside that const char pointer to be filled with random stuff.  But putting the tmp value as intermediary avoids having that memory where the string contents are stored get corrupted.

**Comment by ericfont** [comment]
and interesting that QByteArray tmp needs to be *outside* of that if statement, so that its memory contents are still available for when JackAudioInterface::setupClient() is called.

**Comment by ericfont** [comment]
My recommendation would be to make mJackClientName be a QString, instead of being a const char *.

**Comment by psiborg112** [comment]
I was just about to suggest the same fix that you did. At the time that I originally simplified that code I hadn't realised all of the implicit data sharing that happens within the QT classes and didn't realise that the validity of the constData() was dependent upon the continued existence of the QByteArray returned by toLatin1(). The code worked most of the time after that change because the time between that call and the setup call for the audio interface is pretty short. Generally you'd get lucky and the memory at that location wouldn't be used for anything else. Obviously you haven't been that lucky.

The easy fix is the one that you mentioned above. The better fix is changing mJackClientName to be a QString and only making the conversion when it's absolutely necessary (as you also suggested). This is implemented in the aaron and qjackctl branches already and I could probably isolate it and make a pull request on it.

**Comment by ericfont** [comment]
ok, thanks.  Sounds like you devs already know about this...the QString would be great.  I don't want to interfere with your development process...but if you could isolate that and make it a pull request, that would be nice.

**Comment by psiborg112** [comment]
No problem. Us devs (in particular this dev) screwed it up in the first place with a careless simplification. And I think it makes more sense to have it as a QString for consistency with other parts of the code that use QStrings alongside other Qt classes. (It's this lack of consistency that bit us here in the first place.)

**Comment by ntonnaett** [comment]
Is this considered fixed? If you know that a PR fixes an Issue you can just state that in a comment in the PR and github automatically closes the Issue.

**Comment by psiborg112** [comment]
Yes, it's fixed in dev. I did tag the issue in the PR. (Do I need to include a reference to it in a comment as well? I'll keep that in mind if that's the case.)

**Comment by ntonnaett** [comment]
I saw this earlier. It seems that this only works with the default branch. So when this gets into main it will close eventually. I personally like a small issue list. Should we cherry-pick the fix for main, just wait or close issues when they are fixed in dev?

**Comment by psiborg112** [comment]
Probably worth waiting until the fix makes it to main so that we don't get duplicates of issues from people not using the dev branch. And it might be good if there's a path for small, straight-forward fixes like this to make it to main in future.
