### ISSUE TITLE
build dependencies incomplete on ubuntu 22.04 qt6

### ISSUE THREAD

**Issue by allroys** [jacktrip/jacktrip#1251]
I tried to build the from source on Ubuntu 22.04, and the dependencies listed at https://jacktrip.github.io/jacktrip/Build/Linux/ weren't sufficient to fully build and run it. My QT6 install was still lacking some "qtquickcontrols2" packages/plugins. I went and downloaded the prebuilt binary, and the readme listed more dependencies, and installing them solved the problem. Suggest updating the build instructions with all the dependencies from the readme.

**Comment by mikedickey** [comment]
Is it just this package that is missing @allroys ? `libqt6quickcontrols2-6`

**Comment by allroys** [comment]
I can't be sure, but that's likely the culprit. The error I was getting was
related to quickcontrols2.
