### ISSUE TITLE
Missing error messages when calling jacktrip on commandline

### ISSUE THREAD

**Issue by mawe42** [jacktrip/jacktrip#1301]
When I run JackTrip 2.2.5 (without GUI support) on a Linux command-line, some useful error messages are not shown in the output. For example, failures to bind to a specific port in P2P server mode are signaled with this line in JackTrip.cpp:
```
        stop(QStringLiteral("Could not bind %1 UDP socket. It may already be binded by "
                            "another process on "
                            "your machine. Try using a different port number")
                 .arg(mReceiverBindPort));
```

`JackTrip::stop` then uses that error message in a `singalError` signal:
```
    emit signalError(errorMessage);
```

However... that signal is not connected to anything that outputs the error message. At least not in P2P server mode on the command-line.

I'm willing to provide a PR to fix this, but I'm unsure what the best way forward would be here. Should I add `std::cerr` outputs next to the `emit signalError(...)` in `JackTrip::stop`? Or should the `signalError` message get a better handler in `main.cpp`?

**Comment by mikedickey** [comment]
Hi @mawe42 , I agree this does seem to be handled poorly. I think it would be better to connect a signal handler to `signalError` that does nothing other than sending the message to `cerr` (maybe prefixed by "ERROR: "?). The two guis each do this with a `processError` method that displays dialog, so maybe we also need a `processError` connected inside JackTrip.cpp?

Note I found a few places that are both emitting `signalError` and sending the message to `cerr`, so we'd probably want to remove those `cerr` calls as part of this change:
* UDPDataProtocol.cpp:668 and 678
* UDPHubListener.cpp:150 and 219

**Comment by mawe42** [comment]
Great, thanks for the pointers. I will prepare a PR tomorrow with a proposed fix

**Comment by mawe42** [comment]
There is a PR in #1303 that fixes the problem for the most important startup errors, I think. I didn't touch `UdpDataProtocol`, as that hasn't got a signalError handler set up inside UdpHubListener yet. The error messaging / logging code in JackTrip seems a little inconsistent at the moment, so I thought it's best to touch as little as possible.
