### ISSUE TITLE
[P2P] only able to connect when using one channel, otherwise no reaction at all (Pipewire, Linux)

### ISSUE THREAD

**Issue by TheRedstoneDEV-DE** [jacktrip/jacktrip#1317]
Hello,
I tried to use this tool to simply send audio over my local network (without any NAT) and I have the following problem:
I am unable to connect client and server of jacktrip when using more than one channel, resulting in the server and client just waiting for each other, not establishing a network connection at all (I first thought it was an issue with my networking / firewall, but it was not, since it flawlessly works with one channel).
I don't really think, that it is a bandwidth problem, since both devices are connected through (wired) gigabit, which should be sufficient (they have a ping of around 0.3-0.4 ms).
I am using the same NixOS setup on both machines with jacktrip version 2.3.1.
Thanks in advance!

**Comment by cchafe** [comment]
Works ok with a 4 channel test using both server and client on the same host.
[setup here is fedora 40 w/ pipewire, JackTrip 2.3.1 main branch, release, RtAudio]

See if you can duplicate this, if not add '-V' to both and send the output

server:
PIPEWIRE_LATENCY=128/48000 ./jacktrip -s --udprt --bufstrategy 3 -q auto -n4
client:
PIPEWIRE_LATENCY=128/48000 ./jacktrip -c localhost -B 4465 --udprt --bufstrategy 3 -q auto -n4
