### ISSUE TITLE
Allow different number of input / output channels (hubpatch mode)

### ISSUE THREAD

**Issue by kltdwrds** [jacktrip/jacktrip#133]
Maybe this is already possible to do, but I'm unsure of how to accomplish - here's likely a common ensemble use case:

There's a jacktrip server running in hubpatch mode:
`jacktrip -S --hubpatch 2`

And multiple clients sending a single channel (to conserve bandwidth, let's say):
`jacktrip -C x.x.x.x -n1`

But how can the client to receive a stereo mix?  Is this possible today?  A small args change?  Or architecturally difficult for the current jacktrip implementation too support? 

Maybe it could work similar to `--bindport --peerport` options - ie `--sendchannels --receivechannels`

Cheers!

**Comment by ntonnaett** [comment]
Duplicate of #78
