### ISSUE TITLE
Cannot connect to jack server even though server running

### ISSUE THREAD

**Issue by afterlifenirvana** [jacktrip/jacktrip#134]
I have installed jacktrip on a ubuntu server. My jack server is running with server name jacktrip-mylocation. If the server name is set to default jacktrip is able to connect to jack server if i set it to anything else I cannot connect to it. I wanted to change name of the server for identification.

**Comment by ntonnaett** [comment]
I just stumbled upon something that might fix this. Could you test #156 ?

**Comment by ntonnaett** [comment]
Fixed in #156
