### ISSUE TITLE
Buzzing when disconnecting from host/client

### ISSUE THREAD

**Issue by ethansiegl** [jacktrip/jacktrip#162]
When you have a host/client connection setup and one party closes the connection, there is a loud buzzing sound that can happen. Would be nice if a connection could be closed gracefully by beeping or notifying in some way

**Comment by psiborg112** [comment]
This is already fixed in the dev branch. You can also work around this in main by using the -z switch on the command line. You won't get a notification, but it will stop the buzz from happening.

**Comment by ethansiegl** [comment]
oh great. thanks!
