### ISSUE TITLE
Problems with Kaspersky and Avast Antivirus?

### ISSUE THREAD

**Issue by petermall** [jacktrip/jacktrip#192]
Hello,
we now had twice the issue, that jacktrip with asio4all on windows 10 was not working with Kaspersky or Avast Antivirus on. In one case, switching off solved the problem, in the other case not. 

First (everything on), we only had outgoing signals, but connection was working. Trying to switch off every firewall and Kaspersky lead to the following output.

![IMG_6460edit](https://user-images.githubusercontent.com/49148501/99875091-34528980-2bed-11eb-831c-2e0e51abedc6.png)

The server was working with two other peers.

I am trying with network settings, but if you have any help, why samplerate seems to be totally wrong, I would be happy!

If this is the wrong place for this question, I would be happy if you can give me a hint to a forum to exchange practical issues... Thank you.

Jacktrip is just the perfect tool at this time!!

**Comment by wholenotes** [comment]
You may want to try changing your Printer and File Sharing settings in Windows: https://github.com/jacktrip/jacktrip/issues/139

**Comment by ntonnaett** [comment]
Reopen, if it's not fixed yet.

**Comment by ntonnaett** [comment]
Should we add an advise for windows users to add an exception for jacktrip in their antivirus software? Did somebody asked Kaspersky and Avast how we should fix this problem?

**Comment by ntonnaett** [comment]
https://www.avira.com/de/analysis/submit?utm_source=CS&utm_medium=KB
We can send Avira the false positive file.

**Comment by ntonnaett** [comment]
@dyfer Could we automate sending those false alarm messages to Avira and others?

**Comment by dyfer** [comment]
@ntonnaett No idea, do they have an API for this? I've never done this before.

**Comment by ntonnaett** [comment]
In our last meeting we came to the conclusion that this is actually the printer issue #139. Please open a new issue if you encounter a problem with your antivirus software.
