### ISSUE TITLE
JackTrip Jack clients can not be run in multithreaded environment (e.g. two-three clients in one app), they can run just as separate processes (apps).

### ISSUE THREAD

**Issue by stamat1** [jacktrip/jacktrip#195]

**Comment by stamat1** [comment]
note:
JackTrip runs as a blocking process and will block the main thread if it is used in an app... To do not block the main thread could be run in a thread, but then two JackTrip threads (server and client) conflict in the Jack server (daemon): it throws looping errors and the functionality between Jack clients and Jack server (daemon) is broken. If JackTrip can be run non-blocking, probably it will solve the problem, because then there is no need to use threads (according Jack community, Jack clients should not be used in threads in order to work properly):
JackWinSemaphore::TimedWait name = jack_pipe.default_system time_out
JackAudioDriver::ProcessGraphSync: SuspendRefNum error, engine may now behave abnormally!!
JackWinSemaphore::TimedWait name = jack_pipe.default_system time_out
JackAudioDriver::ProcessGraphSync: SuspendRefNum error, engine may now behave abnormally!!
JackWinSemaphore::TimedWait name = jack_pipe.default_system time_out
JackAudioDriver::ProcessGraphSync: SuspendRefNum error, engine may now behave abnormally!!
JackWinSemaphore::TimedWait name = jack_pipe.default_system time_out
JackAudioDriver::ProcessGraphSync: SuspendRefNum error, engine may now behave abnormally!!

**Comment by stamat1** [comment]
note:
As it has been discussed in Jack community, the reason is the linear graph... and the errors start throwing on connecting (bridging) clients or when they are autoconnecting.

**Comment by stamat1** [comment]
note:
tested:
1. it seems that JackTrip server is always active Jack client (no need to call: mAudioInterface->startProcess(); for it).
2. if JackTrip Jack clients are activated in JackTrip::startProcess(), and jack_connect(); JackTrip client ports in different thread - no errors are thrown, but on jack_connect(); JackTrip server ports in different thread - the above errors are thrown again.
(we could say that this observation confirming Jack community discussion)

**Comment by ntonnaett** [comment]
It sounds, that this is not an issue with the code of JackTrip. If you want to discuss JackTrip development, you may write to the mailing list.
