### ISSUE TITLE
DefaultHeader::checkPeerSettings doesn't provide correct sample rate via 'signalError'

### ISSUE THREAD

**Issue by tvr-gh** [jacktrip/jacktrip#196]
The error sent to **stderr** by **DefaultHeader::checkPeerSettings** pertaining to sample rate mismatch is correct
but message sent via **signalError** for **qjacktrip** contains the indices of the sample rate (a small integer) rather
than the actual sample rates.  So the terminal output is correct but the GUI error message comes out wrong.

It would be better to put the **bufferSize** and **samplingRate** into local variables and use them to create the error
messages.  A patch will be submitted _[once i figure out how to]_.

**Comment by psiborg112** [comment]
This should be fixed now.
