### ISSUE TITLE
Program crash without errors (Win)

### ISSUE THREAD

**Issue by Petapton** [jacktrip/jacktrip#201]
Hello, I'm experiencing this weird issue when running Jacktrip in Windows 10, here cmd log:
```
PS C:\Users\Ruptpipt\Downloads> .\jacktrip.exe -C 192.168.1.157 -n1 -V
Verbose mode
Settings:startJackTrip before new JackTrip
Settings:startJackTrip before mJackTrip->setBindPorts
Settings:startJackTrip before mJackTrip->setPeerPorts
Settings:startJackTrip before mJackTrip->startProcess
step 1
  JackTrip:startProcess before checkIfPortIsBinded(mReceiverBindPort)
  JackTrip:startProcess before checkIfPortIsBinded(mSenderBindPort)
  JackTrip:startProcess before setupAudio
  JackTrip:setupAudio before new JackAudioInterface
  JackTrip:setupAudio before mAudioInterface->setup
PS C:\Users\Ruptpipt\Downloads>
```
The former is relative to -s, -C and -c modes. The one for -S is:
```
PS C:\Users\Ruptpipt\Downloads> .\jacktrip.exe -S
mThreadPool default maxThreadCount = 1
mThreadPool maxThreadCount set to 16
JackTrip HUB SERVER: TCP Server Listening in Port = 4464
JackTrip HUB SERVER: Waiting for client connections...
JackTrip HUB SERVER: Hub auto audio patch setting = 0
=======================================================
JackTrip HUB SERVER: Client Connection Received!
JackTrip HUB SERVER: Client Connect Received from Address : ::ffff:192.168.1.6
JackTrip HUB SERVER: Reading UDP port from Client...
JackTrip HUB SERVER: Client UDP Port is = 4464
JackTrip HUB SERVER: Client TCP Connection Closed!
JackTrip HUB SERVER: Spawning JackTripWorker...
JackTrip HUB SERVER: Starting JackTripWorker...
--->JackTripWorker: PeerNumChannels = 2
PS C:\Users\Ruptpipt\Downloads>
``` 
This same behaviour came out on 4 different PCs (two "real" and two VMs, Parallels and VirtualBox), both with unprivileged and privileged cmd lines and PS. Nothing strange happening when run on linux machines.
Does anybody know what is this due to? Maybe there's something stupid that I'm missing, but I can't really figure out what's going on.

**Comment by cchafe** [comment]
JackTrip doesn't check that the version of Jack it was compiled with is what's there on the machine it's running on. Your symptoms suggest a mismatch. My working win10 pair is documented and available here [https://ccrma.stanford.edu/software/jacktrip/windows/index.html](url) 
That's v1.2.1 so there may be a more recent build elsewhere.

**Comment by ntonnaett** [comment]
Sounds like resolved to me.

Your link seems to be broken. Here might be a [working one](https://ccrma.stanford.edu/software/jacktrip/windows/index.html).
