### ISSUE TITLE
split dependencies into build dependencies and runtime dependencies

### ISSUE THREAD

**Issue by umlaeute** [jacktrip/jacktrip#211]
right now, the INSTALL.txt mentions that there is a dependency of jacktrip on `iperf`, `audacity` and `qjackctl`: https://github.com/jacktrip/jacktrip/blob/6458b8f997ad1a0299825efbc70efce73b550d74/INSTALL.txt#L25

however, i don't see any such *dependency*. both programs are doubtless nice tools and having them around when **using** `jacktrip` might solve a lot of headaches (at least `qjackctl`; i have no clue why `audacity` would be needed *at all*).

i think it would be great if you could split the dependencies into those that are required for *building*, and those that are required for *running* jacktrip.
something as simple as splitting the instructions into two lines would already satisfy me:

~~~sh
dnf install jack-audio-connection-kit-devel alsa-lib-devel git
dnf iperf qjackctl audacity
~~~

and while we are at it, you might also want to consider using the same dependencies for fedora and Debian.

**Comment by ntonnaett** [comment]
Fixed with #209
