### ISSUE TITLE
Remote client names not showing up in server mode

### ISSUE THREAD

**Issue by windows10luke** [jacktrip/jacktrip#224]
I successfully compiled jacktrip v1.3 on Linux, and for an audio transport over the network, it works fine. However, when trying to set the client name so that it shows up server side, it does nothing. I thought that the ability to set the client name was fixed in this version? 
The command I am using on the server is: jacktrip -S
The command for the client is: jacktrip -C 192.168.68.136 -z --clientname Audio_1 --remotename testname
When I run these commands, it shows up on the server as the client IP address and not the name that I set on the client.

**Comment by ntonnaett** [comment]
Does it work if you omit the clientname flag?

**Comment by windows10luke** [comment]
No, it is no different - it still shows up on the server as: __ffff_192.168.68.145

**Comment by ntonnaett** [comment]
Are both sides version 1.3? We use it in our seminar, but with the short -K flag.

**Comment by windows10luke** [comment]
Yes, I just double checked. I also tried the -K flag with no success either. Is there something else I need to add to the server or client commands to get it to work?

**Comment by windows10luke** [comment]
I just did some more testing with various different computers using the previously listed commands. Running Jacktrip between two different Windows 10 computers was successful and the title of the client showed up on the server. When running the Jacktrip client on a Linux computer and the Jacktrip server on a Windows 10 computer, the name of the Linux client also showed up on the server, which was running Windows 10. When switching the roles of these two computers (Linux computer as server and Windows 10 computer as client), the Linux computer failed to provide the name of the client and instead reported the IP address. I also tried compiling Jacktrip on a Raspberry Pi just to see if there was any difference and there was none. It seems like the Windows 10 version acting as a server works with Linux, but using Linux as the server doesn't work in terms of reporting the client name. Other than not reporting the client name, audio was transported with no errors in all tested scenarios.

**Comment by ntonnaett** [comment]
Interesting finding. Thank you for your investigation! Maybe we find some developer that's using Windows.

**Comment by psiborg112** [comment]
Has anyone been able to reproduce this? I can't using the qjacktrip branch (and there should be nothing in the relevant code that differs from the main branch). @windows10luke, are you able to rebuild your linux version adding the following code in UdpHubListener.cpp at line 351 (assuming you've checked out the main branch):

`cout << "REMAINING BYTES = " << clientConnection->bytesAvailable() << endl;`

And then check what that outputs on the console when connecting from your windows machine?

**Comment by windows10luke** [comment]
When running the server on Linux using the main branch and the debug code inserted, the remaining bytes output to the console is 66. This is when the Windows computer is acting as the client. However, I checked out and built the qjacktrip branch on Linux to see if there was any difference. I also added the same debugging code to line 404. When running the qjacktrip branch as a server on Linux, and connecting to it as a client from either the qjacktrip branch or the main branch on the Windows computer, the proper names show up on the Linux server and everything works as it should. Also, the remaining bytes output to the console is 64. 
I also misspoke in my previous comment about the branch of jacktrip I was using on the Windows computer. When I was creating a jacktrip server on the Windows computer (where the proper names showed up) and the Linux computer was a client , the version I was using on the Windows computer was the qjacktrip GUI version, not the jacktrip version from the main branch. When using the version from the main branch, it behaved exactly the same way as when the Linux version was the server - no client names showed up and only IP addresses. So, it appears that this is not an issue with the Linux version specifically. Instead, something is broken in the code between the main jacktrip branch and the qjacktrip branch.

**Comment by psiborg112** [comment]
Awesome, thanks so much for doing that. It is indeed a regression in main. The port number that precedes the client name request used to be read as a 32 bit integer but is now being read as a 16 bit integer. So we need to discard those two bytes for things to work as expected. Adding the following code at line 351 (in place of the previous debug line) should do the trick:

`clientConnection->read(port_buf, size);`

**Comment by psiborg112** [comment]
Have created a pull request (#225) for this.

**Comment by windows10luke** [comment]
I just finished compiling with the new code and it works great! Thanks for all your help with this!
