### ISSUE TITLE
add CAPI , TAPI  sport 

### ISSUE THREAD

**Issue by Reaper10** [jacktrip/jacktrip#24]
add sport for CAPI 
http://www.capi.org/
add sport for TAPI

**Comment by umlaeute** [comment]
http://www.capi.org says:
> This domain is now reserved. As of now, no content has been uploaded.

**Comment by ntonnaett** [comment]
That's not in the scope of jacktrip. But you can connect any jack capable (and even pulseaudio and alsa capable) program to jacktrip.
