### ISSUE TITLE
-K not working?

### ISSUE THREAD

**Issue by michaeldessen** [jacktrip/jacktrip#251]
Following up from report on jacktrip users list: The -K argument does not seem to work. I tried using it on a client machine connecting to a server, both in hub mode and p2p mode, and it had not effect in either one; in both cases the server listed the client by public IP as usual instead of the name added after the -K argument. Both machines were macOS running jacktrip 1.3.

**Comment by wholenotes** [comment]
Hi Michael,

-K has worked for me in the past and it worked again just now. This is what I saw on the server side QJackCtl:
[Screen Shot 2021-03-23 at 9.19.24 AM.png]

This was the command I used on the client side:
./jacktrip -C myserverIP -K bonnie

Bonnie
‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by wholenotes** [comment]
Could you paste the command you were trying to use, MIchael? I seem to recall there may have been a bug for client names of a certain length or format, but the bug may have been fixed on the main branch.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by psiborg112** [comment]
This is a known regression on the server end that was introduced by a 
hotfix early in the 1.3.0 release cycle. It's been fixed in main and 
dev, but I don't think the binaries have been recompiled.
Aaron

**Comment by michaeldessen** [comment]
Thanks, Aaron. So I assume we can just close this and it'll get sorted out the next time binaries are compiled. I'll report back on the jacktrip users list to let the poster know they can compile from main if they like. Thanks!
