### ISSUE TITLE
DeviceNotificationCallback kAudioDeviceProcessorOverload

### ISSUE THREAD

**Issue by fredguth** [jacktrip/jacktrip#253]
When I start jacktrip peer server it shows this error message:

-----------
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jackdmp 1.9.17
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
Copyright 2016-2021 Filipe Coelho.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
JACK server starting in realtime mode with priority 10
self-connect-mode is "Don't restrict self connect requests"
Default input and output devices are not the same !!
Cannot open default device in duplex mode, so aggregate default input and default output
Separated input = 'MacBook Pro Microphone' 
Separated output = 'MacBook Pro Speakers' 
Input channel = 0 ==> JACK input port = 0
JACK output port = 0 ==> output channel = 0
JACK output port = 1 ==> output channel = 1
DeviceNotificationCallback kAudioDeviceProcessorOverload
CoreAudio driver is running...
JACK server started
Setting JACK Process Callback...
SUCCESS
---------------------------------------------------------
The Sampling Rate is: 48000
---------------------------------------------------------
The Audio Buffer Size is: 16 samples
                      or: 64 bytes
---------------------------------------------------------
The Number of Channels is: 2
---------------------------------------------------------
Using UDP Protocol
---------------------------------------------------------
Using JitterBuffer strategy 1
Waiting for Connection From a Client...

----------------
and then... a lot of 
DeviceNotificationCallback kAudioDeviceProcessorOverload
DeviceNotificationCallback kAudioDeviceProcessorOverload
DeviceNotificationCallback kAudioDeviceProcessorOverload

No idea on how to fix this

**Comment by ntonnaett** [comment]
Try to start the Jack Server first and set the device correctly. Maybe qjackctl is already installed. Don't install qjackctl with brew right now because it installs an old version of Jack that collides with the installation from jackaudio.org.

**Comment by antonrunov** [comment]
> The Audio Buffer Size is: 16 samples
I believe it might be just too small for the buffer. Try 64 as a starting point.
