### ISSUE TITLE
JackTrip Quick Start Guide + Documentation Links

### ISSUE THREAD

**Issue by semicolon-madness** [jacktrip/jacktrip#259]
In the JackTrip installer, the Quick Start Guide and Documentation links both go to the WS02 API management website.

- is this deliberate, or did you mean to link something more specific to JackTrip here?

Here are the links I found in the installer:  [Quick Start Guide](https://docs.wso2.com/display/AM260/Quick+Start+Guide) [Documentation](https://docs.wso2.com/display/AM260/)

Please let me know if this is something to worry about or not.  I look forward to being more active in this community as I learn more about open source applications.

**Comment by wholenotes** [comment]
Sorry, this was a mistake. I'll take these links out of the next version of the installer.

Bonnie

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by ntonnaett** [comment]
Is this fixed?
