### ISSUE TITLE
Some builds in GHA are skipped

### ISSUE THREAD

**Issue by dyfer** [jacktrip/jacktrip#260]
It seems that after a PR is merged, the GitHub Actions build is skipped on the merge commit. IIUC, this means that the builds on the `dev` (and `main`?) branches are skipped.

Current list of builds:
https://github.com/jacktrip/jacktrip/actions/workflows/jacktrip.yml

Compare the regular build for PR #257: https://github.com/jacktrip/jacktrip/actions/runs/730865730 and then skipped build after merging it: https://github.com/jacktrip/jacktrip/actions/runs/748842041 

I think the builds should always be triggered on pushes to the `dev` and `main` branches.

**Comment by ntonnaett** [comment]
What is the advantage if they would be build again?

**Comment by dyfer** [comment]
For one, my PR was not built in `dev` so Qt cache was not stored. 
Also, if we ever did automatic deployment, we need to trigger builds from the main branch(es). I strongly believe `dev` and `main` should always build.

**Comment by ntonnaett** [comment]
The PR was build and the cache was stored. Everything works as expected. Changes to this behavior are not necessary before there are automatic deployments.

**Comment by dyfer** [comment]
> The PR was build and the cache was stored. 

If that's the case, then I guess it's fine for now. I didn't think the PR build from another fork would store cache in the main repo's space, but I'm unclear on how the cache action exactly works.

**Comment by ntonnaett** [comment]
PRs are build for the main repo. Caches usually have an ID. So the steps in your GHA where you load and store the cache must specify the same ID.
