### ISSUE TITLE
multichannel audio from JackTrip Hub server

### ISSUE THREAD

**Issue by columnnofive** [jacktrip/jacktrip#262]
I have been using multiple P2P sessions to connect 2 - 6 clients to different interface outputs for independent processing. It would be very useful for me to have a Hub server that allows me to route each client to separate channels and send me an 8 or 16-channel signal.

**Comment by ntonnaett** [comment]
There's already a hub server mode. Just use capital letters (-S or -C).

If I misunderstood your request, please reopen.
