### ISSUE TITLE
MULTI Channel audio FROM JackTrip Hub

### ISSUE THREAD

**Issue by columnnofive** [jacktrip/jacktrip#267]
I have been using multiple P2P sessions to connect 2 - 6 clients to different interface outputs for independent processing. It would be very useful for me to have a Hub server that allows me to route each client to separate channels and send me an 8 or 16-channel signal.

__Originally posted by @columnnofive in https://github.com/jacktrip/jacktrip/issues/262__

To be clear, what I can do now with multiple p2p sessions using -s and -o AND what I do daily using Netty-McNetface, is what I want to do with JackTrip Hub mode. Not mix in Hub mode, not mix with SC running in the background on the VS. 

For example: I have 5 clients, recording to 5 separate tracks in Pro Tools, with 5 separate sends to 5 different analog inputs in an outboard Kyma system for interactive processing, with 5 different returns into PT and a separate monitoring submix sent back to clients.

I do this now with p2p mode. It would be more elegant and convenient to do it in Hub mode.

**Comment by columnnofive** [comment]
> So jacktrip -S -p5. 

But this still delivers a stereo signal to me from the Hub server, not independent channels, correct? QJackctl routing only works on the dummy interface in the Hub, whereas I need the signals to be routable on my physical interface.

**Comment by psiborg112** [comment]
So you'll see each client connection as a separate jack client in the graph window. They don't get mixed down to a single stereo output. You can route the audio from each individual client wherever you want it to go.

**Comment by columnnofive** [comment]
But the routing occurs on the dummy interface on the Hub, not on my local machine. So individual processing of the signals can only happen on the virtual machine, not on my local machine.

I don't have any screenshots to share, but picture this: I have a 32 channel interface, and in QJackctl Connect, with 5 separate -n2 p2p connections offset to different ports, I have 5 different Output Ports in the left column, which I map to 10 different Input Ports of my physical interface. From there, I have 10 analog signals to do with as I will, independent of each other.

**Comment by psiborg112** [comment]
Then we're talking about different things - I'm talking about using the hub server as a drop in replacement for p2p mode on the machine that's doing the processing, not on a separate machine.

**Comment by columnnofive** [comment]
Yup. 
In that light, I would _love_ to be able to send/receive multichannel signals from the Hub.

**Comment by ntonnaett** [comment]
Right now the number of input and ouput channels must be the same (-n #). There's #223 for having different number of input and output channels. So a client could send you 2 channels but receives 5.

**Comment by psiborg112** [comment]
So this should be possible then, but you'll still need to disable auto patching and manage all of the audio routing yourself using something like jack-matchmaker on the server. You'll just need to set the number of channels to 5 on the machine doing the processing, which will give you 5 channels in and out of the hub server.

**Comment by psiborg112** [comment]
To clarify, running the client on the processing machine with -n 5 will get you that number of channels to and from the server. You don't need to specify the number of channels on the server side. But, the server won't know how you want to connect the other clients with fewer sends and receives to those 5 channels. That's where you need to step in and do it manually using other tools.

**Comment by columnnofive** [comment]
This'll take some fiddling, I'll give it a whirl and see how it shakes out.

**Comment by columnnofive** [comment]
btw what branch do I need in order to use this functionality (-n 5, etc)?

**Comment by ntonnaett** [comment]
That should be in every branch

**Comment by ntonnaett** [comment]
As all questions seem to be answered I'll close this.
