### ISSUE TITLE
QJackTrip for MacOS Mojave ?

### ISSUE THREAD

**Issue by newlaurent62** [jacktrip/jacktrip#272]
Hello, 

I would like to install QJackTrip (last version) on MacOS Mojave. The provided package can be installed but at runtime it complains that it needs Big Sur (MacOS 11) so it is unusable.

I tried to compile and create a PKG bundle but my understanding of the `assemble_app.sh` is that it needs signing parameters that i don't have.

So is it possible to create a PKG for Mojave please and provide a download link ? 

Kind Regards,
Laurent

**Comment by newlaurent62** [comment]
On an another open source project called Jamulus, i can generate a DMG file instead of a PKG and install from it ? Even if DMG seems less secure, it is easier to create ... (My knowledge is limited)

**Comment by psiborg112** [comment]
I'll take a look at the binary and see if I can fix it. (Might not have time for the next couple of days though.) It should have been compiled to work with anything from HIgh Sierra onwards, but there's probably some library that it's linked against that has the wrong target version. In the meantime, if you're just intending to use it on your own machine, you can just create an app bundle that you can then copy straight into your Applications directory. It won't be signed, and you'll have to go through the whole 'open anyway' thing in your security and privacy preferences but it should work. (Just make sure the first "exit 0" line in the assemble_app.sh script hasn't been commented out.)

**Comment by ntonnaett** [comment]
I assume our builds at https://github.com/jacktrip/jacktrip/releases obsolete this.
