### ISSUE TITLE
meson compiler flags

### ISSUE THREAD

**Issue by cchafe** [jacktrip/jacktrip#285]
In preparing the new experimental buffer scheme for merging to dev, qmake builds worked while meson builds compiled ok but didn't run correctly. Flags are different and adding these two flags fixes things for meson. A meson spiritual advisor is needed!
meson configure  -Doptimization=2 -Dcpp_args=-D_REENTRANT builddir

qmake is set up differently in a few more ways and it would be great to resolve any other differences that are meaningful
(for example) the qmake compile phase (linux) is
g++ -c -pipe -D__LINUX_ALSA__ -g -O2 -D__LINUX_ALSA__ -O2 -std=gnu++11 -D_REENTRANT -Wall -Wextra -fPIC -DWAIRTOHUB -D__LINUX__ -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB

**Comment by ntonnaett** [comment]
That's funny. Yesterday I asked Marcin if qmake sets this variable. Meson should set it with the threads dependency if needed. 
[](https://www.gnu.org/software/libc/manual/html_node/Feature-Test-Macros.html) says that the macro is actually obsolete.

```
QThread: Destroyed while thread is still running
Abgebrochen (Speicherabzug geschrieben)
```

That's what I'm getting. …Investigation… Buffersizes were different. Runs until killed by the operating system. That's with _REE NTRANT. Same with optimizations.

Why does it need QThread?

Could you rebase on dev? We fixed the qmake build with pipewire yesterday.

**Comment by cchafe** [comment]
Yup, meson now runs fine with the defaults. I tested PoolBuffer without QThread and then merged dev into my branch. All good.

The extra thread was for gathering stats and recording those for plotting -- I'll work on a different approach.
