### ISSUE TITLE
"Does not support the requested channel count" RtAudio errors prominent after asymmetric channel count merge

### ISSUE THREAD

**Issue by mattahorton** [jacktrip/jacktrip#289]
Logged back on this morning, saw there were a few big merges (congrats!) in to dev, and rebuilt. Started getting a lot of these.

> RtApiCore::probeDeviceOpen: the device (4) does not support the requested channel count.

I'm specifically working with a nojack RtAudio build here. I found that when I made my input channel count match my output channel count, I could occasionally get it to work, but not consistently.

FWIW, this is on Mac OS and I've tried it on both an Intel and an M1 machine with the exact same results on both.

**Comment by ntonnaett** [comment]
Thank you!
What did work before? What doesn't work anymore?
Right now only the default audio interface is supported. Do you use the default one?
I understand that if you use -n # everything works as expected but not consistently. What do you mean with not consistently?

**Comment by mattahorton** [comment]
Right. So previously on dev, I never had issues regarding channel count. I _am_ using the default audio device (I just change it in the global sound device settings if I want to use something else.) 

It seems to be that when my input device has a single channel, it throws the error.

I actually haven't been using -n. Instead, since my output device has 2 channels and my input has 1, I created a virtual device (using loopback) and just patched the single channel to 2 channels and used that as my system-wide input device. When I did that, things started to work. 

I just tried things again and am finding that it consistently breaks on devices with a single input channel. Here's an example.

> MattH@iMac builddir % ./jacktrip -C 3.239.165.166
> Warning: using non jack version, RtAudio will be used instead
> Settin Up Default RtAudio Interface
> ---------------------------------------------------------
> DEFAULT INPUT DEVICE  : 
> Audio Device  [6] : Apple Inc.: iMac Microphone
>   Output Channels : 0
>   Input Channels  : 1
>   Supported Sampling Rates: 44100 48000 88200 96000 
>   --Default Intput Device--
>   --Probed Successful--
> ---------------------------------------------------------
> DEFAULT OUTPUT DEVICE : 
> Audio Device  [5] : Apple Inc.: External Headphones
>   Output Channels : 2
>   Input Channels  : 0
>   Supported Sampling Rates: 44100 48000 88200 96000 
>   --Default Output Device--
>   --Probed Successful--
> ---------------------------------------------------------
> 
> RtApiCore::probeDeviceOpen: the device (6) does not support the requested channel count.

**Comment by ntonnaett** [comment]
If I remember correctly, the output showed if you used an aggregate device. Did you combine those two devices? I think that is what we tested.

**Comment by ntonnaett** [comment]
Could you try running `./jacktrip -C 3.239.165.166 --receivechannels 2 --sendchannels 1 `?

**Comment by mattahorton** [comment]
Hey thanks. That does work as expected. I understand the change a bit better now.

But, I originally found this via QJackTrip crashing with no errors when I connected (since I was using the packaged up Mac app). My primary goal right now is getting that to an extremely usable state. Is there a way to make that work?

It's probably work that needs to get done on the UI?

**Comment by psiborg112** [comment]
There are two things to be fixed here. The UI needs to have support added for different numbers of input and output channels, which I can probably do in the next couple of days. But more importantly, the backend needs to handle the RtAudio error rather than just quitting out. It needs to call JackTrip::stop with an error message as a parameter, or hook a signal to the JackTrip::slotStopProcessesDueToError slot. (Afraid I'm not at all familiar with the RtAudio changes.)

**Comment by psiborg112** [comment]
This will be getting compounded as well by a problem with how channels are currently being set in the UI. (Issue introduced with the recent merges.) This has been fixed in #290. (The changes mentioned above will still need to happen though.)

**Comment by mattahorton** [comment]
Thanks for the perspective and for taking care of that, Aaron. Fwiw, I'm happy to contribute. Just don't have the depth of Qt experience just yet.

**Comment by psiborg112** [comment]
Thanks @mattahorton, always good to know and I'll keep it in mind.

**Comment by psiborg112** [comment]
Once #291 is merged you'll be able to set different numbers of channels for input and output in the UI.

**Comment by mattahorton** [comment]
The GUI work is great, Aaron.

Sounds to me like there's 2 more things that could be done.

1. Handle the error.
2. Make sure the default send/receive channel count is supported by the device and modify it if not.

The 2nd one is interesting to me from an ease of use standpoint. I'm working on some other things right now, but I'll see if I can't figure something out. I'd like to dig into the codebase and start understanding it if I can get the time.

**Comment by ntonnaett** [comment]
Once #292 is merged jacktrip shouldn't exit anymore if you try to use more channels than physically available but just maxes out.

**Comment by ntonnaett** [comment]
@mattahorton  I just read your last message. Sorry that I took part of the task from you. I didn't add a general error handling for RtAudio. And the RtAudio support is very basic right now. I would be more than happy if you want to work on this.

There's meta issue #218 for RtAudio. Feel free to use it.

**Comment by mattahorton** [comment]
That's fine! It's important that it gets done! I'll check out your work @ntonnaett

**Comment by mattahorton** [comment]
Going to close this and add some detail about the error handling to #218 since I believe this issue shouldn't appear except for some really wild edge cases any longer.
