### ISSUE TITLE
can't build on Fedora 26

### ISSUE THREAD

**Issue by corebots** [jacktrip/jacktrip#29]
Installed qt5* and jack-audio-connection-kit-devel with dnf but when i try to build with ./build in the /scr directory i get: 

$ ./build
Building on Linux
./build: line 41: -spec: command not found
make: *** No rule to make target 'clean'.  Stop.
./build: line 43: -spec: command not found
make: *** No rule to make target 'release'.  Stop.

i've tried that on two separate machines. Am I doing something wrong or is it a bug?

**Comment by robwafle-devwrx** [comment]
I'm getting the same result on my rasberrypi.

pi@raspberrypi:~/jacktrip/src $ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

pi@raspberrypi:~/jacktrip/src $ ./build
Building on Linux
./build: line 41: -spec: command not found
make: *** No rule to make target 'clean'.  Stop.
./build: line 43: -spec: command not found
make: *** No rule to make target 'release'.  Stop.

**Comment by ntonnaett** [comment]
It looks like qmake doesn't work. Can you verify that it is installed?
