### ISSUE TITLE
jacktrip -S on osx ignores client's -K clientname

### ISSUE THREAD

**Issue by kaosbeat** [jacktrip/jacktrip#304]
All instances jacktrip 1.3.
Trying to run a multiclient setup with an OSX jacktrip server. I want to connect the clients using a -K clientname.
so on OSX  (ip 192.168.1.42) being I run:
`jacktrip -S -p 5`
and on the RPi clients I run:
`jacktrip -C 192.168.1.42 -K clientname1 -n 1 `
`jacktrip -C 192.168.1.42 -K clientname2 -n 1 `
etc..
on the OSX server the clients sho show up as  __ffff_192.168.1.68 and so on

![Screen Shot 2021-06-01 at 09 58 14](https://user-images.githubusercontent.com/204628/120287851-ed420100-c2bf-11eb-8b9c-f1ea635ae6ff.png)

I want to be able to create a complex patch of 20 clients, using jmess to save and recall presets. not IPs but the client names I use in my scripts...

When using a linux server, this problem is not present

**Comment by psiborg112** [comment]
Are you building JackTrip yourself, or are you using a binary from somewhere? There was a regression in the way the server handled custom client names after a hotfix to 1.3.0, which I've since addressed in another hotfix, but I'm not sure if all of the binaries have been updated.

**Comment by kaosbeat** [comment]
Ah, buiklt it on the linux clients, download the jacktrip binary I found here https://ccrma.stanford.edu/software/jacktrip/osx/jacktrip on osx.

I'll try building the OSX version first

**Comment by kaosbeat** [comment]
That was indeed the problem, building 1.3.0 from source solved the problem. It prints the exact same version string
```
./jacktrip --version
JackTrip VERSION: 1.3.0
```
