### ISSUE TITLE
Version issue with wix installer

### ISSUE THREAD

**Issue by dyfer** [jacktrip/jacktrip#335]
It seems that WIX doesn't like our "release candidate" version: https://github.com/jacktrip/jacktrip/runs/2798474419?check_suite_focus=true#step:17:42

Any idea what would be the best way to fix that?

**Comment by dyfer** [comment]
@psiborg112 I've "assigned" this to you just to get your input, as I don't have much experience with the wix installer. Please don't feel like you have to come up with a solution :) (Though if you know how to solve this, that would be absolutely fabulous!)

**Comment by psiborg112** [comment]
Yeah, it seems that wix only deals with version strings of the form x.x.x. I think the only way around this will be to discard the -rc part of the version string in the installer build script. As long as we're consistent with putting a hyphen between the version and the rc number, we should be fine. (Should get a chance to do this in the next  day or so.)

**Comment by psiborg112** [comment]
Or now even. Have implemented my proposed solution in #336.

**Comment by dyfer** [comment]
Fixed in #336. Thanks so much @psiborg112 !
