### ISSUE TITLE
jacktrip -v

### ISSUE THREAD

**Issue by SynthiaPayne** [jacktrip/jacktrip#347]
jacktrip -v is printing jacktrip VERSION: 1.4.0-rc.2 - should it be rc.3?

**Comment by SynthiaPayne** [comment]
^ such a tiny observation of this monumental work! win and mac terminal versions seem solid for initial connection testing. thank you!

**Comment by cchafe** [comment]
thanks! and thanks for testing -- there was a contest to see if anyone would notice that. 
It can be brought into line when there's rc.4

**Comment by SynthiaPayne** [comment]
I WON!!!
