### ISSUE TITLE
Other datas/metadatas available to jack for JACK based active crossover

### ISSUE THREAD

**Issue by spmp** [jacktrip/jacktrip#35]
Can the JackTrip protocol be modified such that metadata can be stored on the JackTrip client and be available to the JackTrip master.

For example the name of the device, the latency of the attached amplifiers, etc.

My thoughts are that a JSON type blob would be the most flexible.

My use case is using JackTrip clients in self powered speakers for completely analogue free audio setup where the crossovers/delays are handled on the Jack master/JackTrip master, and we want to store some useful information about the connected device without resorting to SSH or similar to retrieve it. If JackTrip had this information available to us in the Jack patch bay somehow this would keep the information together in the right place.

I have been experimenting with NetJack2, is there any reason why JackTrip would be better than NetJack for my use case. The most critical issue is audio arriving at the amplifiers at the same time.
NetJack has so far not been doing this well.

Cheers

**Comment by luzpaz** [comment]
@jcacerec care to respond ?

**Comment by jcacerec** [comment]
Yes, you can subclass https://github.com/jcacerec/jacktrip/blob/master/src/PacketHeader.h and use any header you want. If you take a look at that class, you can see that there are now three implementations, `DefaultHeader`, `JamLinkHeader`, and `EmptyHeader`. You can add a new subclass with your own header.

**Comment by ntonnaett** [comment]
Did you look into AVB for your use case? It's an open standard and they have _the time a signal comes out of your speaker_ integrated into the protocol AFAIK.
