### ISSUE TITLE
Default to Meson build for Linux in 1.4.0

### ISSUE THREAD

**Issue by ntonnaett** [jacktrip/jacktrip#361]
We should encourage the use of the meson build for Linux. 

The advantages for the end user right now are:
- Manpage
- Icons
- Metainfo / Appstream data
- maybe LTO on some distributions

**Comment by dyfer** [comment]
We've talked about this during the meeting on Jul 14.

I think this should be accompanied by the change to the CI, which should happen after qmake and meson builds are put into the same action (which I plan to work on). My preference would be to:
- release 1.4.0 first
- I plan to unify qmake and meson builds in CI after 1.4.0 (after we merge `dev` into `main`),
- then we merge this (possibly updating the changelog)
- In our - then unified - github actions script I'd switch our nightly Linux builds to use meson

**Comment by ntonnaett** [comment]
This would lead to bad user experience on Linux. You wouldn't find JackTrip in your Desktop Enviroment without a desktop file. There is no reason to make this depend on CI changes.

**Comment by dyfer** [comment]
I think the nightly/release builds should be built with the same instructions as the "default" in the instructions for consistency.

**Comment by ntonnaett** [comment]
Package maintainers wouldn't use meson and end up with a package that doesn't show up in software centers or your application launchers. The only way for the enduser then is to start jacktrip from the terminal. So this should really happen before we call it 1.4.0. Is the change in the CI really big? Why not do it before the release?

**Comment by ntonnaett** [comment]
Small Sidenote: Meson 0.59 sets up the visual studio environment automatically on Windows (for 64bit) now, if no other compiler toolchain is detected. So Windows use becomes easier now.

**Comment by dyfer** [comment]
> a package that doesn't show up in software centers or your application launchers.

Since we are supporting 3 build systems, we could (should?) make all of them create the necessary files to provide desktop environment integration. What's needed in order to have that with the qmake build?

> Is the change in the CI really big?

Not really big, but the main CI now runs on main/dev and PRs, and not on every push. I guess that's not really a big deal, and/or I could change it to make it run on every push until 1.4.0 release. All this is because the manual trigger for the builds (which we agreed to use instead of builds on every push) only appears when the CI changes are on the default branch (`main` in our case).

I see the following options:
1. we release 1.4.0 as is with suboptimal linux user experience
2. I make the CI changes before 1.4.0 and we change nightly builds to meson (I'd suggest that we again build on all pushes, until 1.4.0 release)
3. make qmake build create proper desktop environment integration files

Previously I was in favor of 1., but because of the issue with the user experience I'm not gravitating towards 2. I also want to make sure that everybody is on board with making meson the default build system on Linux. @cchafe @psiborg112 is that fine with you?

I think we could still investigate what's needed to address 3.

**Comment by ntonnaett** [comment]
Option 2 sounds good to me. IMHO we should deprecate qmake and concentrate on fixing problems that prevent developers from switching to meson. Maybe a workshop session would be a good idea. Especially to look into IDE integration.

The last time I've looked into the CMake file it seemed quite basic. What are the main benefits for you to use CMake for building JackTrip, @psiborg112 ?

**Comment by psiborg112** [comment]
I don't think we should deprecate qmake. If people have qt installed they'll have qmake available to them. It's one less dependency that's needed and I think we should maintain it as a universal fallback.

CMake, as it's currently set up, pretty much does everything that qmake does. (With the exception that I haven't managed to get pkgconfig working with any sort of success on windows. Hoping to get that done eventually, but it hasn't been a huge priority.) I use it because it's the default build system for KDevelop and has good integration with it. It's not something I'd recommend for others, and I've just made it available in case anyone else happens to find it of use. (If they do, then great. If they don't, then also great.) I'll continue to maintain it for my own needs, but don't think it's of much relevance beyond that.

**Comment by ntonnaett** [comment]
I want to be clear enough. I don't want to remove qmake yet. Just mark it as "You may not get all of the glory from using the qmake build". With qmake on Windows you might even need other dependencies because jacktrip uses getopts(). It's a unix function. So you need mingw or something similar. Meson gets wingetopts automatically when using msvc.

I'll try KDevelop. I didn't like QtCreator. Maybe this is nicer.

**Comment by ntonnaett** [comment]
KDevelop is much better. Meson backend works fine too.

**Comment by dyfer** [comment]
> With qmake on Windows you might even need other dependencies because jacktrip uses getopts()

Just to clarify - the current qmake build instructions on Windows suggest using MinGW, which can be installed together with Qt. If building without RtAudio, there are no other dependencies needed AFAIR (aside from Jack).

**Comment by dyfer** [comment]
It doesn't seem that meson build works with static qt in github actions, see https://github.com/dyfer/jacktrip/runs/3188792586?check_suite_focus=true#step:17:174. Is this an issue with meson or with the way we build qt in gha?

**Comment by ntonnaett** [comment]
I'm surprised that qmake doesn't error out. Let's first fix those linking warnings. We might have to update to Qt 5.14 for this.

**Comment by dyfer** [comment]
Sounds good. Do you have an idea what's the problem? Should we fix this before 1.4.0?
I also seem to have [problems linking with static rtaudio on macOS](https://github.com/dyfer/jacktrip/runs/3189143014?check_suite_focus=true#step:17:224).

> We might have to update to Qt 5.14 for this.

I would really prefer not no increase minimum Qt version. Static Linux build is now at 5.12.x (5.12.11?) and it would be great to keep it that way, so that it's compatible with more systems.

**Comment by ntonnaett** [comment]
We should fix this because it could lead to weird behavior/bugs. I'm wondering why there are multiple versions in the first place. I mean they both come from Qt. I found some reported issues about static linking Qt that looked similar and were bugs in 5.12 and got fixed with 5.14. But I'm not sure if they are identical to our problem. The other thing is that resource compilation was fixed with 5.14 for Meson. But that might not be a real problem because icons are retrieved from the filesystem on Linux.

The undefined references would probably resolved by https://github.com/mesonbuild/meson/pull/7733. And it looks that this won't be merged before JackTrip 1.4.0.

Don't install rtaudio with brew. Just set rtaudio=enabled with meson configure.

**Comment by dyfer** [comment]
> We should fix this because it could lead to weird behavior/bugs. 

Do you think we should delay 1.4.0 until this is fixed?

> Don't install rtaudio with brew. Just set rtaudio=enabled with meson configure.

IMO we should definitely support using packaged rtaudio. Is the issue because in GHA we have only static rtaudio lib?

**Comment by ntonnaett** [comment]
> > We should fix this because it could lead to weird behavior/bugs.
> 
> Do you think we should delay 1.4.0 until this is fixed?

If we deliver the static build, yes. We could release without static build and fix it afterwards.

> 
> > Don't install rtaudio with brew. Just set rtaudio=enabled with meson configure.
> 
> IMO we should definitely support using packaged rtaudio. Is the issue because in GHA we have only static rtaudio lib?

I saw that you removed the shared library. What was the reason for that? This must work with both available. But that's not the problem. It seems that it doesn't get the linking flags right. RtAudio should declare that it needs CoreAudio. So it's a packaging or upstream bug. Could you post the pkgconfig file for RtAudio that you get from brew?

---------------
I'm wondering if we need another option for static rtaudio. When using a subproject you have the rtaudio:default_library option that you can set to static. But if you get the dependency from somewhere else we would need to state that the dependency itself should be static. Probably we don't want to hardcode this but have another option for that. And I think default_library should be shared and not both. Have to check the implications for executables.

**Comment by dyfer** [comment]
> If we deliver the static build, yes. We could release without static build and fix it afterwards.

I'm in favor of delivering the static build.

> I saw that you removed the shared library. What was the reason for that? 

Yes... the reason was that I wanted to have the static rtaudio when building with static qt, and didn't add a switch to keep shared lib when using shared Qt. However, _static rtaudio + shared qt seemed to work fine with qmake_.

> RtAudio should declare that it needs CoreAudio. 

Maybe? but on windows with qmake I had to [manually specify linker flags](https://github.com/jacktrip/jacktrip/blob/dev/jacktrip.pro#L161) for jacktrip since they were not specified in pkgconfig file. With my limited experience with build systems and linking, I can't tell whether this is intended behavior or a bug... It seems that with QMake we [link with coreaudio](https://github.com/jacktrip/jacktrip/blob/dev/jacktrip.pro#L74) manually.

> Could you post the pkgconfig file for RtAudio that you get from brew?

<details>

```
prefix=/usr/local/Cellar/rt-audio/5.1.0_1
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include/rtaudio        

Name: librtaudio
Description: RtAudio - a set of C++ classes that provide a common API for realtime audio input/output
Version: 5.1.0
Requires:  
Libs: -L${libdir} -lrtaudio
Libs.private: -lpthread
Cflags: -pthread -I${includedir}  -D__MACOSX_CORE__
```
</details>

> But if you get the dependency from somewhere else we would need to state that the dependency itself should be static.

How does the qmake work with both static and shared library without specifying which one it is?

**Comment by ntonnaett** [comment]
This is an example of the pkgconf file that cmake produces for RtAudio on Fedora. 
```
prefix=/usr/local
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include/rtaudio        

Name: librtaudio
Description: RtAudio - a set of C++ classes that provide a common API for realtime audio input/output
Version: 5.1.0
Requires: jack alsa libpulse-simple 
Libs: -L${libdir} -lrtaudio
Libs.private: -lpthread
Cflags: -pthread -I${includedir} -D__UNIX_JACK__ -D__LINUX_ALSA__ -D__LINUX_PULSE__
```
On macOS I would expect something like `Requires: CoreAudio` or similar.

**Comment by ntonnaett** [comment]
> > If we deliver the static build, yes. We could release without static build and fix it afterwards.
> 
> I'm in favor of delivering the static build.

Me too.
 
> > RtAudio should declare that it needs CoreAudio.
> 
> Maybe? but on Windows with qmake I had to [manually specify linker flags](https://github.com/jacktrip/jacktrip/blob/dev/jacktrip.pro#L161) for jacktrip since they were not specified in pkgconfig file. With my limited experience with build systems and linking, I can't tell whether this is intended behavior or a bug... It seems that with QMake we [link JT with coreaudio](https://github.com/jacktrip/jacktrip/blob/dev/jacktrip.pro#L74) manually.
> 

Every part must declare their own dependencies. If not you would have nothing else to do than to add dependencies of dependencies. That's definitely a bug. 

> > Could you post the pkgconfig file for RtAudio that you get from brew?
> 
> ```
> prefix=/usr/local/Cellar/rt-audio/5.1.0_1
> exec_prefix=${prefix}
> libdir=${exec_prefix}/lib
> includedir=${prefix}/include/rtaudio        
> 
> Name: librtaudio
> Description: RtAudio - a set of C++ classes that provide a common API for realtime audio input/output
> Version: 5.1.0
> Requires:  
> Libs: -L${libdir} -lrtaudio
> Libs.private: -lpthread
> Cflags: -pthread -I${includedir}  -D__MACOSX_CORE__
> ```
> 
`-framework CoreAudio` seems to be missing from Libs:. I've just searched the web how frameworks should be added. But could probably be different... Could you try adding `meson configure -Dcpp_link_args="-framework CoreAudio"` Then we don't need to alter the build file.

> 
> How does the qmake work with both static and shared library without specifying which one it is?

I don't know. There's only one library you should use and that is Qt! :point_up:

**Comment by dyfer** [comment]
>  Could you try adding meson configure -Dcpp_link_args="-framework CoreAudio" Then we don't need to alter the build file.

I can, but we shouldn't require users to do that. Also, looking at your meson windows build, there's quite a bit of (rtaudio?) flags that are manually configured. IMO these should be part of our meson config (ASIO + WASAPI on Windows, no jack on macOS and Linux, etc).

>> How does the qmake work with both static and shared library without specifying which one it is?

> I don't know. There's only one library you should use and that is Qt! ☝️

Sure :) but it seems to be dealing with static/shared rtaudio as well.

**Comment by ntonnaett** [comment]
> > Could you try adding meson configure -Dcpp_link_args="-framework CoreAudio" Then we don't need to alter the build file.
> 
> I can, but we shouldn't require users to do that. Also, looking at your meson windows build, there's quite a bit of (rtaudio?) flags that are manually configured. IMO these should be part of our meson config (ASIO + WASAPI on Windows, no jack on macOS and Linux, etc).

I will open a PR with a change adding coreaudio as a jacktrip dependency as a workaround. I also added a comment to check frequently if [the issue](https://github.com/thestk/rtaudio/issues/302) is fixed in RtAudio.
The rtaudio flags that you set in the CI don't work if you aren't using the rtaudio subproject. So they do nothing right now. I totally agree that we should have a platform dependent default config system. I will open an issue for meson for that. We could just use native files with only the configuration in it for now. Then we would use these like cross files (--cross native_file.txt). I don't want to clutter the build file with that. Disregarding that, I think ASIO + WASAPI shouldn't be options and just be enabled for Windows.
This would be done upstream. No JACK on macOS and Linux would be a JackTrip thing. I'm not sure how to handle this right now. Probably with those native files. But remember that all the rtaudio config options are subproject options and are not used in the CI if we use package managers like brew.

> 
> > > How does the qmake work with both static and shared library without specifying which one it is?
> 
> > I don't know. There's only one library you should use and that is Qt! point_up
> 
> Sure :) but it seems to be dealing with static/shared rtaudio as well.

I just found the STATIC option for qmake. That's not really fine grained. Maybe removing the shared rtaudio is the only way for qmake to get a mixed shared/static setup...

**Comment by ntonnaett** [comment]
My idea how clean native platform configuration could look like: https://github.com/mesonbuild/meson/issues/9046

**Comment by dyfer** [comment]
> The rtaudio flags that you set in the CI don't work if you aren't using the rtaudio subproject.

Yes, I'm aware. However, my thinking now is that - particularly on Windows - we might want to support building RtAudio. (I'd actually do that in qmake as well, but that's a separate topic). In this case IMO we should configure RtAudio for our needs.

In CMake, you can define flags in your parent project that would be then picked up by the subproject, i.e. you override subproject default with flags defined in the parent project. Is this possible in meson?

> I just found the STATIC option for qmake. That's not really fine grained. Maybe removing the shared rtaudio is the only way for qmake to get a mixed shared/static setup...

Yes, it's not fine grained. But regardless whether qmake is set to static or shared, it picks up static rtaudio library just fine on macOS.

> My idea how clean native platform configuration could look like: mesonbuild/meson#9046

Maybe I'm not understanding the problem but isn't it possible to have in meson configuration something like `if platform == windows: option1 = true1`?

**Comment by ntonnaett** [comment]
With #373 merged, we can close this and have more time to improve the meson experience (even more).
