### ISSUE TITLE
Symbolic monochrome icon missing

### ISSUE THREAD

**Issue by ntonnaett** [jacktrip/jacktrip#365]
Gnome Shell shows a symbolic link of applications in the topbar. Right now JackTrip's icon gets converted to greyscale and this doesn't look right. We should add a black and white version of the logo. SVG should be sufficient.

**Comment by mikedickey** [comment]
@codedoser would be they guy for this. Not sure why it will not let me reassign?

**Comment by ntonnaett** [comment]
You can only assign members and collaborators of the jacktrip organization.

I realized that it's not black and white what we need but one color. But I don't know how the mapping works. In `/usr/share/icons/hicolor/symbolic` there are icons that seem to map grey to white in gnome shell.

**Comment by ntonnaett** [comment]
Found [this](https://developer.gnome.org/hig/stable/icons-and-artwork.html.en).

**Comment by codedoser** [comment]
@ntonnaett - Hi Nils, what type of icon are you searching for?  I can create whatever you need, just provide me the dimensions, file type, and what type of icon you are looking for?  White on black, black on white, color on black or white?  Thanks!  Doser

**Comment by ntonnaett** [comment]
Hi Doser, Thanks for helping!

This is how JackTrip's symbolic icon looks right now. It's automatically generated by Gnome Shell from the colored icon.
![JackTrip generated symbolic Icon](https://user-images.githubusercontent.com/8383722/126477630-bc29935b-3256-4207-acc8-4a1ecbff3179.png)

This is an example of Firefox's self provided symbolic icon. Much more contrast than JackTrip's.
![Firefox symbolic Icon](https://user-images.githubusercontent.com/8383722/126477643-037f127c-b48e-4ac4-920b-1a8c5e40e81e.png)

Symbolic icons are 16×16 px SVGs. Here is an example from the Epiphany Browser:
https://gitlab.gnome.org/GNOME/epiphany/-/blob/master/data/icons/hicolor/symbolic/apps/org.gnome.Epiphany-symbolic.svg

Maybe this chapter about symbolic icons is helpful:
https://developer.gnome.org/hig/stable/icon-design.html.en

**Comment by codedoser** [comment]
Hi Nils:

Try either one of these.  One has a transparent background, the other has a solid back background.  Let me know if they work.
[J_logo_gray.zip](https://github.com/jacktrip/jacktrip/files/6857486/J_logo_gray.zip)

Thanks,
Andrew

**Comment by ntonnaett** [comment]
Hi Andrew,

Thank you very much! I took the transparent one. That seems to be the standard. Look:
![JackTrip-symbolic-icon-self-provided](https://user-images.githubusercontent.com/8383722/126536252-89bf8c54-57a6-4629-b823-bf2b1eb7e2ab.png)

Actually in real life the rendering is slightly different. It looks thinner. What do you think about making it more bold and maybe emphasizing the ball ends? I think this would make it more similar to other symbolic icons and you could recognize more of the iconic/symbolic parts. Just a suggestion. I'm not a graphic designer.

**Comment by codedoser** [comment]
Hi Nils:

Let's try using a white logo first.  Being the graphic is so thin, the black visually bleeds into the design and will make it look slightly gray (in theory).  Let me know how this looks. 
[jt_J_logo_white_transperent.svg.zip](https://github.com/jacktrip/jacktrip/files/6858143/jt_J_logo_white_transperent.svg.zip)

**Comment by ntonnaett** [comment]
I might not really want to show you this because screenshot rendering seems to take another path, but here it is:
![white_sym_icon](https://user-images.githubusercontent.com/8383722/126546501-03623ba9-6100-4b4f-b092-a5efb5bae308.png)
On my desktop I didn't see a difference. It seems as if the screenshot did some antialiasing (or different hinting).

**Comment by codedoser** [comment]
So I made the logo thicker, but now it's a slight bit smaller.  Let's see how this looks.

[jt_J_logo_white_transperent_v2.svg.zip](https://github.com/jacktrip/jacktrip/files/6858600/jt_J_logo_white_transperent_v2.svg.zip)

**Comment by ntonnaett** [comment]
![thick-symbolic-icon](https://user-images.githubusercontent.com/8383722/126559675-9df66469-8f98-4d97-a700-6e7bbc1ac8eb.png)

I'm very happy with the result. If you like it too, I will make a PR with the changes.

**Comment by codedoser** [comment]
Yes, the bolder logo looks much better.  I say let's use it.  Thanks!
