### ISSUE TITLE
corrupted size vs. prev_size on exit with pipewire

### ISSUE THREAD

**Issue by cchafe** [jacktrip/jacktrip#371]
I'm getting a core dump running under pipewire (latest, fc34) with latest dev branch 
e27319ccc1bf692ed47232c6de58e65e4cfe3dc5
when exiting either cli or gui

here's the session and the backtrace

[cc@localhost builddir]$ pw-jack -p 256  ./jacktrip -C jackloop256.stanford.edu
Setting JACK Process Callback...
SUCCESS
---------------------------------------------------------
The Sampling Rate is: 48000
---------------------------------------------------------
The Audio Buffer Size is: 256 samples
                      or: 1024 bytes
---------------------------------------------------------
The Number of Channels is: 2
---------------------------------------------------------
Using UDP Protocol
---------------------------------------------------------
Using JitterBuffer strategy 1
Server Address set to: jackloop256.stanford.edu Port: 61002
---------------------------------------------------------
UDP Socket Receiving in Port: 4464
---------------------------------------------------------
Waiting for Peer...
Received Connection from Peer!
^C
Shutting Down...
sending exit packet
Stopping JackTrip...
corrupted size vs. prev_size
Aborted (core dumped)

coredumpctl debug

#0  0x00007f634e9162a2 in raise () from /lib64/libc.so.6
#1  0x00007f634e8ff8a4 in abort () from /lib64/libc.so.6
#2  0x00007f634e958a97 in __libc_message () from /lib64/libc.so.6
#3  0x00007f634e96070c in malloc_printerr () from /lib64/libc.so.6
#4  0x00007f634e961606 in unlink_chunk.constprop () from /lib64/libc.so.6
#5  0x00007f634e961790 in malloc_consolidate () from /lib64/libc.so.6
#6  0x00007f634e961fc0 in _int_free () from /lib64/libc.so.6
#7  0x00007f634e9657c8 in free () from /lib64/libc.so.6
#8  0x00007f633d8e0ff9 in pw_protocol_native_connection_destroy ()
   from /usr/lib64/pipewire-0.3/libpipewire-module-protocol-native.so
#9  0x00007f633d8cab95 in impl_disconnect () from /usr/lib64/pipewire-0.3/libpipewire-module-protocol-native.so
#10 0x00007f634e8518f8 in proxy_core_destroy () from /lib64/libpipewire-0.3.so.0
#11 0x00007f634e882348 in pw_proxy_destroy () from /lib64/libpipewire-0.3.so.0
#12 0x00007f634e851784 in pw_core_disconnect () from /lib64/libpipewire-0.3.so.0
#13 0x00007f635038b5d8 in jack_client_close () from /usr/lib64/pipewire-0.3/jack/libjack.so.0
#14 0x0000000000456f24 in JackAudioInterface::stopProcess (this=0x115d370) at ../src/JackAudioInterface.cpp:260
#15 0x00000000004176b3 in JackTrip::closeAudio (this=this@entry=0x11236d0) at ../src/JackTrip.cpp:284
#16 0x0000000000419252 in JackTrip::stop (this=0x11236d0, errorMessage=...) at ../src/JackTrip.cpp:955
#17 0x000000000047b5cd in JackTrip::slotStopProcessesDueToError (this=<optimized out>, errorMessage=...)
    at release/../../src/JackTrip.h:526
#18 0x00007f634f17d809 in QObject::event(QEvent*) () from /lib64/libQt5Core.so.5
#19 0x00007f634f15307b in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib64/libQt5Core.so.5
#20 0x00007f634f156606 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()

**Comment by ntonnaett** [comment]
It's the buffersize. When running with asan I'm getting this:
```
=================================================================
==6360==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61900005b380 at pc 0x0000004e76f0 bp 0x7fe2d54fa770 sp 0x7fe2d54fa768
READ of size 2 at 0x61900005b380 thread T1
    #0 0x4e76ef in AudioInterface::fromBitToSampleConversion(signed char const*, float*, AudioInterface::audioBitResolutionT) ../src/AudioInterface.cpp:586
    #1 0x4e6603 in AudioInterface::computeProcessFromNetwork(QVarLengthArray<float*, 256>&, unsigned int) ../src/AudioInterface.cpp:436
    #2 0x4e5ab1 in AudioInterface::callback(QVarLengthArray<float*, 256>&, QVarLengthArray<float*, 256>&, unsigned int) ../src/AudioInterface.cpp:216
    #3 0x4fb5d2 in JackAudioInterface::processCallback(unsigned int) ../src/JackAudioInterface.cpp:307
    #4 0x4fb749 in JackAudioInterface::wrapperProcessCallback(unsigned int, void*) ../src/JackAudioInterface.cpp:323
    #5 0x7fe2eb25c21f in on_rtsocket_condition (/usr/lib64/pipewire-0.3/jack/libjack.so.0+0x1721f)
    #6 0x7fe2e39ee70a in loop_iterate (/usr/lib64/spa-0.2/support/libspa-support.so+0x870a)
    #7 0x7fe2e97af512 in do_loop (/lib64/libpipewire-0.3.so.0+0x3d512)
    #8 0x7fe2e9a22298 in start_thread (/lib64/libpthread.so.0+0x9298)
    #9 0x7fe2e994a352 in clone (/lib64/libc.so.6+0x100352)

0x61900005b380 is located 0 bytes to the right of 1024-byte region [0x61900005af80,0x61900005b380)
allocated by thread T0 here:
    #0 0x7fe2eb327207 in operator new[](unsigned long) (/lib64/libasan.so.6+0xb0207)
    #1 0x4e563b in AudioInterface::setup() ../src/AudioInterface.cpp:135
    #2 0x4f9683 in JackAudioInterface::setup() ../src/JackAudioInterface.cpp:98
    #3 0x41e8a7 in JackTrip::setupAudio(int) ../src/JackTrip.cpp:209
    #4 0x4214d8 in JackTrip::startProcess(int) ../src/JackTrip.cpp:451
    #5 0x4eefdd in main ../src/main.cpp:224
    #6 0x7fe2e9871b74 in __libc_start_main (/lib64/libc.so.6+0x27b74)

Thread T1 created by T0 here:
    #0 0x7fe2eb2cd8d6 in pthread_create (/lib64/libasan.so.6+0x568d6)
    #1 0x7fe2e97af653 in pw_data_loop_start (/lib64/libpipewire-0.3.so.0+0x3d653)

SUMMARY: AddressSanitizer: heap-buffer-overflow ../src/AudioInterface.cpp:586 in AudioInterface::fromBitToSampleConversion(signed char const*, float*, AudioInterface::audioBitResolutionT)
Shadow bytes around the buggy address:
  0x0c3280003620: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3280003630: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3280003640: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3280003650: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3280003660: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c3280003670:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3280003680: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3280003690: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c32800036a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c32800036b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c32800036c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==6360==ABORTING
```

Mentioning this:
```
tmp_16     = *(reinterpret_cast<const int16_t*>(input));  // *((int16_t*) input);
```

Omitting -p 256 or pw-jack entirely because I have pipewire running by default, I don't get a core dump.
Only this:
```
=================================================================
==6349==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 2176 byte(s) in 1 object(s) allocated from:
    #0 0x7f2c02325af7 in calloc (/lib64/libasan.so.6+0xaeaf7)
    #1 0x7f2c0224f4f1 in ensure_mix (/usr/lib64/pipewire-0.3/jack/libjack.so.0+0xa4f1)

Indirect leak of 530432 byte(s) in 2 object(s) allocated from:
    #0 0x7f2c02325af7 in calloc (/lib64/libasan.so.6+0xaeaf7)
    #1 0x7f2c022648d8 in jack_port_register (/usr/lib64/pipewire-0.3/jack/libjack.so.0+0x1f8d8)

Indirect leak of 57856 byte(s) in 4 object(s) allocated from:
    #0 0x7f2c02325af7 in calloc (/lib64/libasan.so.6+0xaeaf7)
    #1 0x7f2c022545d6 in alloc_object.lto_priv.0 (/usr/lib64/pipewire-0.3/jack/libjack.so.0+0xf5d6)

SUMMARY: AddressSanitizer: 590464 byte(s) leaked in 7 allocation(s).
```

**Comment by cchafe** [comment]
Started it with the pipewire environment variable instead of pw-jack and core dump happens that way, too.
PIPEWIRE_LATENCY=256/48000  ./jacktrip -C jackloop256.stanford.edu

**Comment by cchafe** [comment]
re: the above, pw-jack is just a script that sets the ENVIRONMENT (so it's the same thing either way...)
But! problem disappeared after fedora upgrade and rebuild of jacktrip. Not sure which fixed it. 
Tested from FPP 32 to 1024 -- all good. FPP 16 still problematic so see next issue...
