### ISSUE TITLE
Meson Linux instructions for older systems

### ISSUE THREAD

**Issue by dyfer** [jacktrip/jacktrip#376]
I've finally tried meson on Ubuntu 20.04 LTS and it seems that `meson build` and `meson install` doesn't work. You need to call `ninja install`. I haven't investigated further, but it seems to be related to [older version of meson](https://github.com/jarcode-foss/glava/commit/f1284a68351733699f3337bc483608bf7a5f5ac0). It's probably something to document - Ubuntu 20.04 is the "most current" LTS version of the system.

**Comment by ntonnaett** [comment]
We should advice for the ninja commands even for new versions. Maybe I wrote this when I wasn't aware of the "problems" with the meson equivalents.

**Comment by dyfer** [comment]
Closed in #378
