### ISSUE TITLE
pipewire hub mode badness with client on same host -- rare edge case (both 1.3.0 and dev)

### ISSUE THREAD

**Issue by cchafe** [jacktrip/jacktrip#379]
pipewire only -- jackd is fine

jacktrip crashes or hangs in this very particular edge case of a hub server under pipewire with -p > 0 and FPP != 1024 with the
client running on the same host and the client's audio connected  -- unfortunate for automatic testing (and some server scenarios) but it does not happen with client audio not connected (-D) so that's at least a workaround

the problem occurs when the client disconnects from server 
it occurs with both 1.3.0 and dev r.c.1.4.0

this will crash or hang (-p > 0) && (FPP < 1024)
PIPEWIRE_LATENCY=256/48000 ./jacktrip -S -p5
but _not_ this
PIPEWIRE_LATENCY=256/48000 ./jacktrip -S **-p0**
and _not_ this
PIPEWIRE_LATENCY=**1024**/48000 ./jacktrip -S -p5

and only with client  on same host and default audio
PIPEWIRE_LATENCY=256/48000 jacktrip -C **localhost** -B4466
but _not_ this
PIPEWIRE_LATENCY=256/48000 jacktrip -C localhost -B4466 **-D**

**Comment by wholenotes** [comment]
-p < 0 and FPP != 1024? Is it possible to have -p < 0?

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by ntonnaett** [comment]
Isn't it `-(p) < 0` => `p > 0`?

**Comment by cchafe** [comment]
Fixed that first line... thanks!

**Comment by cchafe** [comment]
Another clue? The problem disappears when running without any USB soundcards plugged in so that jacktrip connects to the pipewire Dummy-Driver instead. (which can be observed with pw-top)

**Comment by ntonnaett** [comment]
Did you try with the pipewire revision update from yesterday? 0.33-2 I think. It fixed my RtAudio backend with JACK.

**Comment by cchafe** [comment]
I've updated to 0.3.33-3 and the same tests fail when connected to a USB audio interface (and again works fine if not connected to one).

**Comment by ntonnaett** [comment]
This doesn't crash for me anymore on Fedora 35.

```bash
$ pw-cli --version
pw-cli
Compiled with libpipewire 0.3.40
Linked with libpipewire 0.3.40
```
