### ISSUE TITLE
does jacktrip implement zero copy?

### ISSUE THREAD

**Issue by michaelpalumbo** [jacktrip/jacktrip#38]
Does jacktrip implement zero-copy protocol? 

iperf3 has a zero copy flag, so knowing whether or not jacktrip uses zero-copy would help inform the test parameters

thanks!

**Comment by michaelpalumbo** [comment]
bump?

**Comment by jcacerec** [comment]
No, it doesn't implement it. There's a lot of copying in the ring buffers :)

**Comment by dyfer** [comment]
I think the question has been answered. Feel free to reopen if this requires further discussion.
