### ISSUE TITLE
Flatpak builds

### ISSUE THREAD

**Issue by dyfer** [jacktrip/jacktrip#386]
Currently our GitHub Actions flatpak builds are not operating properly, AFAICT. Particularly, they do not check out the exact branch/commit that they are triggered from. I also don't think these builds were widely tested.

Since FlatPak distribution doesn't seem fully tested/finished, I'd suggest to not include those in the 1.4.0 release and keep their GHA yaml files on a separate branch, but remove them from `dev` for now, so that they don't make it into `main` when we release 1.4.0. @ntonnaett what do you think about that?

If we want to use FlatPak for the release, we should further test it/fix it IMO. I'm not sure how much effort we want to put into that before 1.4.0 release though.

**Comment by ntonnaett** [comment]
That there are only builds for main and dev is known. But we shouldn't trigger at all for PRs. That should be changed.

Did you try to run the flatpak builds?

Flatpaks should be delivered by flathub in the end. So they shouldn't end up on the Release page. But I think those GHAs should stay as a CI Check.

**Comment by dyfer** [comment]
I think I've tried a flatpak build but I couldn't run it on Ubuntu since it expected PipeWire. I was able to install it though.

My main reservation is that the github branch is specified directly in the flatpak's yaml file, so it has no connection to what branch/commit/tag the CI is triggered from. I'd really like to see this being dynamically set by GHA runner to the current commit SHA, maybe in a similar way to how we update `org.jacktrip....desktop.in` when building.

As for when they are triggered - if FlatPak is viable to be installed directly, we could consider triggering that on PRs, similarly to what we do with regular builds, to make testing easier. 

I also think that if we want to provide FlatPak, it would be nice to also provide Snap, the latter being more ubuntu-oriented. But maybe that's not a good idea?

**Comment by ntonnaett** [comment]
We would need to write a script then that generates the flatpak yaml file. There would be this scripted flatpak generator for PRs and the deployment flatpaks that automatically upload to flathub for stable and dev. Sounds good.

For the Pipewire requirement we should add a note in the metainfo description for flatpaks only. I have to think about how to detect that we build as flatpak.

**Comment by dyfer** [comment]
Here are more comments I have on flatpak:
- Looking at how seamless the experience with flatpak is on Fedora, I would really like to also offer Snap (or something) for Ubuntu users
- When I opened the dev flatpak in GNOME software, the description was in German (my system language/localization setting is English)
- As discussed in https://github.com/jacktrip/jacktrip/pull/398#issuecomment-914604949 I think it would be good to figure out how to specify the tag for the "release" flatpak before closing this

**Comment by ntonnaett** [comment]
You probably mean the summary in the metainfo file:
```
  <summary>Connect and Play with other Musicians</summary>
  <summary lang="de_DE">Verbinde dich und spiele mit anderen Musikern</summary>
```

I assumed that the first summary is the C locale one. Maybe this must be explicit.

**Comment by ntonnaett** [comment]
I actually can't find anything about that syntax anymore... I propably just gonna remove this.

**Comment by ntonnaett** [comment]
#401 Fixes the summary.
