### ISSUE TITLE
Version setting for Linux desktop integration files

### ISSUE THREAD

**Issue by dyfer** [jacktrip/jacktrip#387]
Since we already set a number of fields dynamically in https://github.com/jacktrip/jacktrip/blob/dev/linux/org.jacktrip.JackTrip.metainfo.xml.in, maybe we could parse the version name from the c++ source and replace it in this file when building as well?

I'd also prefer to handle changelog differently so that we don't have to update it in multiple places: either just link to https://github.com/jacktrip/jacktrip/blob/dev/docs/About/CHANGELOG.md in the xml file, or automate populating the xml file from CHANGELOG.md (tricky...?).

**Comment by ntonnaett** [comment]
We might be able to remove the branch tag from the flatpak yml file: https://github.com/bilelmoussaoui/flatpak-github-actions/issues/14
I think I ran into some problems when I tried to figure this out. Maybe it works now.

I aggree that hardcode the changelog there is going to make too much work. This should be automated. Perhaps even the deployment to flathub.

**Comment by ntonnaett** [comment]
Nope: That's the brach for exporting.

**Comment by dyfer** [comment]
Could we just drop the `<releases>` section for now? I've read it is optional and it's tedious to maintain it.

**Comment by ntonnaett** [comment]
It seems you are right. I thought this was required.

**Comment by dyfer** [comment]
fixed in #397
