### ISSUE TITLE
Waiting for Peer and VPN tunnels (utun) on Mac OS X 

### ISSUE THREAD

**Issue by wholenotes** [jacktrip/jacktrip#388]
@columnnofive and I seem to have resolved a "Waiting for peer" issue related to to VPN tunnels (utun) on Mac OS X.  @columnnofive was running the server and my client was getting "waiting for peer" on JackTrip.  When he ran an iperf3 server on port 4464 and I initiated an iperf3 client on the same port udp, he saw on the server side a message registering a "successful" (not really) a connection back to my IP at a port on my side other than 4464, initiated from an IP that did not match his machine's IP, i.e. the IP he would've seen on the site whatismyip.  On the iperf3 client side, I did not see any success messages.  Upon running ifconfig on the server side command line, we saw a utun entry like the ones in this post: https://developer.apple.com/forums/thread/682767

The utun entry was associated with the IP we had seen as having a established "successful" iperf3 connection from his machine back to mine.  @columnnofive tried disabling his VPN, but it wasn't until he completely uninstalled it and restarted his machine that our JackTrip and iperf3 experiments succeeded.  @columnnofive and I may supplement this post with more detailed output and error messages if we dig for them.  Can't guarantee this is going to work for other setups, but things are looking promising for this case.

**Comment by ntonnaett** [comment]
Can this be closed?

**Comment by columnnofive** [comment]
I think so
