### ISSUE TITLE
Possible AVB Support

### ISSUE THREAD

**Issue by brandflake11** [jacktrip/jacktrip#39]
Hello all,

I was wondering how feasible it would be for jacktrip to support AVB, or if anyone knows if there is any currently being worked on AVB software, especially for Linux? 

I currently have access to a Digiface AVB device, and a MOTU AVB switch if there is anything I could do to facilitate this?

**Comment by ericfont** [comment]
Seems that jack needs to support AVB well and be able to operate in sync with the AVB clock to get the timing befit that AVB offers. Googling https://www.google.com/search?q=jack+avb doesn't seem to show much good news...there is a thread on Ardour...one comment says "AVB streams can be connected to jack. However, the process is very much manual and command line oriented" (https://discourse.ardour.org/t/linux-avb-support/89168/3).

I am getting an Motu AVB interface myself...been debating investigating AVB with jack.  One question is in what way would you want to add AVB to jack trip, beyond simply allowing jack to have AVB recognized as a device.

**Comment by ethancastro** [comment]
I was looking into this myself a bit ago, trying to share 16 channels of live audio between two MacBook pros (for redundancy) over ethernet (thunderbolt bridge), ended up not being able to do so entirely, and finally broke down and bought loopback (formerly Soundflower). Seems like that might work until we can get Jack to work more smoothly.

**Comment by ntonnaett** [comment]
AVB support is a too streched goal for jacktrip in my opinion. The formerly known AVB working group expanded their work to other time sensitive use cases. I didn't look into it but there is a lot of code directly from avnu: [OpenAvnu](https://github.com/AVnu/OpenAvnu)

I hope AVB gets easier with pipewire. There are gstreamer-avb-plugins in the OpenAvnu repository. Using those in pipewire should be straightforward. Maybe with some fiddling in NetworkManager.

So I'm closing this for now.
