### ISSUE TITLE
GHA: ODR violation in Linux build

### ISSUE THREAD

**Issue by ntonnaett** [jacktrip/jacktrip#391]
See: https://github.com/jacktrip/jacktrip/runs/3438184706?check_suite_focus=true#step:14:104

**Comment by dyfer** [comment]
Is this about Qt itself build configuration? Do we need to care about this?

**Comment by ntonnaett** [comment]
There are two sources of the same symbols. There is thirdparty in the path, maybe Qt has its own?! Private maybe should be private. Could be leaking because of wrong compile/linker flags.

We should care about that. Those warnings say that you don't know what you end up with. So this might be unproblematic but you can't know.

**Comment by ntonnaett** [comment]
It's fixed. Isn't it?

**Comment by dyfer** [comment]
> It's fixed. Isn't it?

I think so.
