### ISSUE TITLE
running -r 2, can't connect with more than -n 2

### ISSUE THREAD

**Issue by michaelpalumbo** [jacktrip/jacktrip#41]
Hi there! While we are able to connect client>server with 3 channels of audio, and with redundancy set at its default value. But when we tried a redundancy value of 2 the connection couldn't be established using 3 channels (but redundancy of 2 and 2 channels did work)

One machine running OSX Sierra (client), the other running El Capitan (sierra).

Tagging my colleague @kieranmaraj in this to follow along and add insight

**Comment by dyfer** [comment]
I've just started using JackTrip recently. What I've observed is that increasing redundancy increases packet size, which creates interesting dependency between buffer size, number of channels, and redundancy, as increasing redundancy helps only as long as one doesn't exceed the default network packet size (~1500 bytes), at least on certain networks.
On my connections I've observed that going beyond the standard packet size dramatically increases packet loss. For JackTrip single packet size is (`bit depth` / 8) * `buffer size` * `number of channels` * `redundancy`. In my case we are using 128 frames buffer and 16 bit depth, in which case we can reliably get 2 channels with redundancy 2 or 4 channels with redundancy 1 (`2 * 128 * 4 * 1` or `2 * 128 * 4 * 1` so the total packet size being 1024 in both cases).
On some networks larger packets are supported well, but over the regular internet connections it's hard to tell I believe.

I'm still learning about this so please correct me if I'm wrong :)

**Comment by ntonnaett** [comment]
Is this also happening with version 1.3.0?

**Comment by ntonnaett** [comment]
Closing because there was no response. Maybe just a bandwidth problem.
