### ISSUE TITLE
1.4.0-rc5 - Rt Audio not recognizing USB Mic

### ISSUE THREAD

**Issue by SynthiaPayne** [jacktrip/jacktrip#413]
I had written earlier about the USB mic (Aokeo) and Volume Controls not being recognized by Rt Audio on a OSX install, but it seems that the USB mic is not being recognized at all by Rt Audio, and it is an issue with Windows too.

There is no problem connecting, but there is no audio sent or received by the USB mic. 

In OSX: the USB mic was enabled in Audio-Midi, and selected for input and output in the JT interface. 
We also tried to use an Aggregate Device and enabled/selected it. Neither worked.

On Win10: the USB mic was activated in ASIO4All, selected in Windows Sound, and ASIO4All was selected in JT.
No dice with any of that. 

The Aokeo USB mic is a very popular and decent mic for $30 being used by a large number of choristers on the JackTrip Bridge without issue. When one chorister's JT would not power up we set them up with the application temporarily until they can get another Bridge. What more can I tell you about this?

Thank you!

**Comment by SynthiaPayne** [comment]
Further testing on OSX with the Aokeo USB mic using JACK: if I select the Mic's output as the Interface in Jack I get audio, but JACK will not start when selecting the Mic's input, or using an Aggregate Device created in Audio-Midi that has the input and the output selected for use.

**Comment by dyfer** [comment]
Some questions that come to mind:
- Does that mic work with other software to record and play back at the same time? 
- Does it work (with other software presumably) at the same configuration, i.e. sampling rate and buffer size?
- Synthia, do you have this mic physically for testing?

**Comment by SynthiaPayne** [comment]
Thank you for your inquiries. My apologies, I did not receive a notification and lost track - didn't mean to abandon this issue. Yes, I do have this mic and will look into these inquiries and report back.

**Comment by SynthiaPayne** [comment]
I am no longer using the Aokeo USB mic referred to in this issue, so will close it for now. Thanks.

**Comment by SynthiaPayne** [comment]
Following up on this issue I found that the USB cable was bad. I switched it out and the mic began working fine. It was a brand new mic, so I did not think to check the cable. It could have shipped defective. Lesson I have re-learned is to always, even if it is a new device, CHECK THE CABLE!
