### ISSUE TITLE
jacktrip 1.4.0 broadcast ports are broken

### ISSUE THREAD

**Issue by mikedickey** [jacktrip/jacktrip#417]
This appears to be a 1.4.0 regression, which current exists still in the latest dev branch and 1.4.0 rc5

When running in server mode, jacktrip's broadcast ports are no longer registered as jack "output" ports, so they cannot be connected to anything:

```
jacktrip_client:send_1
        properties: input,terminal,
jacktrip_client:send_2
        properties: input,terminal,
jacktrip_client:receive_1
        properties: output,terminal,
jacktrip_client:broadcast_1
        properties: terminal,
```

Server started with command line:

```
jacktrip -S -t -z --bindport 4464 --nojackportsconnect --broadcast 1024 -q auto
```

**Comment by ntonnaett** [comment]
Fixed in #418
