### ISSUE TITLE
1.4.0 windows start menu icon

### ISSUE THREAD

**Issue by mikedickey** [jacktrip/jacktrip#423]
This is very minor, but just for the record..

Using Installer on Windows 10 x64, the JackTrip icon doesn't seem to be used in the start menu.

Strangely, when you open JackTrip, it does show the icon in the task bar.

See attached images.

![jacktrip_taskbar](https://user-images.githubusercontent.com/1159596/139717735-3424e66b-293f-409f-b577-50f0d274d4a0.png)
![jacktrip_start_menu](https://user-images.githubusercontent.com/1159596/139717739-10bf6199-7ec4-4588-8837-155d93a443f0.png)

**Comment by psiborg112** [comment]
I don't have this issue. But my build is using cmake so I think that's where the difference lies. For qmake it should hopefully be sufficient to add the following line to the jacktrip.pro file:
`RC_FILE = win/qjacktrip.rc`

(If someone using qmake on windows can test that that would be great.)

**Comment by psiborg112** [comment]
(And I have no idea what is needed for meson.)

**Comment by ntonnaett** [comment]
There's a module for this in meson: https://mesonbuild.com/Windows-module.html

**Comment by ntonnaett** [comment]
Reopen if it's not fixed with 1.5.1 (or dev right now).
