### ISSUE TITLE
Display vumeters in GUI for input and output channels

### ISSUE THREAD

**Issue by mikedickey** [jacktrip/jacktrip#425]
I've found that a ton of troubleshooting can be easily resolved by just having vumeters displayed for the input and output channels: no audio, clipping, levels too low, etc. I think it would be incredibly beneficial to display this near the "# of channels" selectors in the "Basic options" tab.

**Comment by forsythac** [comment]
@psiborg112 is this something we're still planning on? Still very very valuable and desired

**Comment by psiborg112** [comment]
It is. I've just been very time poor at the moment, but it's the next thing on my todo list.

**Comment by ntonnaett** [comment]
This seems to be implemented.
