### ISSUE TITLE
Automatically connect all inputs to output channels?

### ISSUE THREAD

**Issue by mnrsmith** [jacktrip/jacktrip#449]
Hi,
I've recently started use jacktrip and noticed that the server only connected one channel if only one channel was received (as it the default on the Pi image). This left one of the output channels unconnected. I have seen this can be addressed by manually making the connections in Jack or using a software mixer on the server.

I thought it 'should' be possible to do this in the existing code in the patcher class and I have done a version of this for my own server. I attach some terrible code and have posted about this issue in google groups: [https://groups.google.com/g/jacktrip-users/c/HXVC5noYufA/m/O_3jOEqwDAAJ](url)

Would it be possible to add this functionality to the official product? Perhaps an additional command line option could be added to enable. Then the client image could be updated to use both channels of the stereo (or even better allow users to choose to allow the two channels to be sent).

Anyway, thanks for all the authors work - I think this project is amazing work!
[npatcher.txt](https://github.com/jacktrip/jacktrip/files/7798357/npatcher.txt)

**Comment by psiborg112** [comment]
I'm not sure that a round robin solution for connections makes sense in the vast majority of cases. I think that maybe there should just be a special configurable case for mono to be upmixed to stereo.

**Comment by ntonnaett** [comment]
Added in version 1.5.0
