### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by dvzrv** [jacktrip/jacktrip#48]
Hi! I'm packaging jacktrip for Arch Linux.

Given that jacktrip 1.1 doesn't work without dangerously high realtime settings applied, it would be great to tag a new release so a working version of this software can be packaged by downstreams again.

**Comment by dvzrv** [comment]
@cchafe @Foaly ping

**Comment by Foaly** [comment]
@dvzrv Hi there! Yes sure we can do that! What do you need from us in order to package another release? Just a git tag?

**Comment by dvzrv** [comment]
Hey! :)
Yes, a git tag of the [same form as the last one](https://github.com/jacktrip/jacktrip/tags) (e.g. v1.2).
Bonus points for establishing a trust chain by doing signed commits and tags! :)

**Comment by cchafe** [comment]
I'm still several days away for testing the aaron branch and we need
that in V1.2

**Comment by lindsayschm** [comment]
Any idea when the branch merge will happen and a new package can be released?

**Comment by cchafe** [comment]
I'm slogging it out with a windows build and test before tagging
V1.2(no ETA)

**Comment by lindsayschm** [comment]
awesome, thanks for the info. good luck with the windows build!

**Comment by umlaeute** [comment]
Debian packager here: we'd also love to see a new release in Debian/Ubuntu/...

just telling :-)

**Comment by cchafe** [comment]
Thanks for your packaging! We await resolution of a rather elusive bug
on the win10 build. After that green light all the way -- sorry for the
delay.

**Comment by ntonnaett** [comment]
Resolved by #65

**Comment by ntonnaett** [comment]
https://github.com/jacktrip/jacktrip/releases/tag/v1.2

**Comment by lindsayschm** [comment]
> Debian packager here: we'd also love to see a new release in Debian/Ubuntu/...
> 
> just telling :-)

Any idea when the new release will be pushed into the repos? And, will this be main repos or a special repo?

**Comment by cchafe** [comment]
The current release is 
https://github.com/jacktrip/jacktrip/tree/v1.2but there's a 1.2.1 that
would be a nice to have. Let me know what you think.
Chris

**Comment by umlaeute** [comment]
i guess "repos" here means "ubuntu package repositories", rather than "source code repository".

so the answer @lindsayschm's question: it's already in the ubuntu repositories, starting with Ubuntu/groovy https://packages.ubuntu.com/groovy/jacktrip

**Comment by lindsayschm** [comment]
> i guess "repos" here means "ubuntu package repositories", rather than "source code repository".
> 
> so the answer @lindsayschm's question: it's already in the ubuntu repositories, starting with Ubuntu/groovy https://packages.ubuntu.com/groovy/jacktrip

yeh! thank you! awesome, greatly appreciated!
