### ISSUE TITLE
1.5.1: error: unknown type name 'BOOL'

### ISSUE THREAD

**Issue by yurivict** [jacktrip/jacktrip#484]
```
/disk-samsung/freebsd-ports/audio/jacktrip/work/jacktrip-1.5.1/src/main.cpp:150:1: error: unknown type name 'BOOL'
BOOL WINAPI windowsCtrlHandler(DWORD fdwCtrlType)
^
/disk-samsung/freebsd-ports/audio/jacktrip/work/jacktrip-1.5.1/src/main.cpp:150:12: error: expected ';' after top level declarator
BOOL WINAPI windowsCtrlHandler(DWORD fdwCtrlType)
           ^
           ;
2 errors generated.
```

FreeBSD 13

**Comment by psiborg112** [comment]
There are definitely going to be more errors than just that. There are quite a number of platform checks that check to see if we're running on MacOS or Linux, but not FreeBSD. So the #else part of that preprocessor branch is meant to be just for Windows. Will try to find some time to fix in the next couple of days if no one else gets to it first.

Files that will need updating are:
main.cpp
UdpDataProtocol.cpp
jacktrip_globals.cpp (might not be needed depending on use of setRealtimeProcessPriority in UdpDataProtocol.cpp)

**Comment by ntonnaett** [comment]
You might want to change your macro from `__LINUX__` to `__linux__`.

**Comment by psiborg112** [comment]
I'm not sure it's quite as simple as that. In UdpDataProtocol it's the APPLE branches that we want to be executed because BSD uses kqueue rather than epoll.

**Comment by ntonnaett** [comment]
How much do the BSDs differ? Can we just use the `BSD` macro? We would need to add this to all other places where we ifdef for `__linux__`.

**Comment by yurivict** [comment]
```__linux__``` doesn't work because it conflicts in system headers.

**Comment by ntonnaett** [comment]
Would you be capable and willing to add the `BSD` macro accordingly in the source code and open a PR?

```bash
$ git grep -n __linux__
src/JackTrip.cpp:1244:#if defined ( __linux__ )
src/PacketHeader.cpp:40:#if defined(__linux__) || defined(__APPLE__)
src/UdpDataProtocol.cpp:55:#if defined(__linux__) || defined(__APPLE__)
src/UdpDataProtocol.cpp:62:#elif defined(__linux__) && !defined(MANUAL_POLL)
src/UdpDataProtocol.cpp:126:#if defined(__linux__) || defined(__APPLE__)
src/UdpDataProtocol.cpp:138:#if defined(__linux__) || defined(__APPLE__)
src/UdpDataProtocol.cpp:237:#if defined(__linux__) || defined(__APPLE__)
src/UdpDataProtocol.cpp:265:#if defined(__linux__)
src/jacktrip_globals.cpp:40:#if defined(__linux__)
src/jacktrip_globals.cpp:44:#endif  //__linux__
src/jacktrip_globals.cpp:154:#if defined(__linux__)
src/jacktrip_globals.cpp:171:#endif  //__linux__
src/main.cpp:100:#ifdef __linux__
src/main.cpp:111:#endif  // __linux__
src/main.cpp:126:#if defined(__linux__) || defined(__APPLE__)
src/main.cpp:262:#if defined(__linux__) || defined(__APPLE__)
src/main.cpp:279:#if defined(__linux__) || defined(__APPLE__)
```

**Comment by ntonnaett** [comment]
You could also look into `linux/meson.build`, if it would be applicable to add `or host_machine.system() == 'freebsd'`.

**Comment by psiborg112** [comment]
I have a draft fix (at least for the preprocessor directives) in #486.
