### ISSUE TITLE
UDP receive problem on windows

### ISSUE THREAD

**Issue by kgokalp** [jacktrip/jacktrip#487]
after fix on issue #474, I experienced some issues on windows side. I am running server app on linux machine, client app on windows machine. receive & send processes run smoothly on linux side, but udp receive process could not receive any packet from server on windows side. 

I tried changing ::recv functions to ::recvfrom functions, in this configuration client app can receive packets, but I hear audio distortions. @psiborg112 can you also check this configuration?

**Comment by psiborg112** [comment]
I'm having a bit of trouble with my windows set up at the moment, so can't reliably test it. Does the problem disappear if you use the 1.5.1 release?

**Comment by psiborg112** [comment]
Any updates on this @kgokalp? I haven't been able to recreate the issue and want to check that we're not introducing a problem with the previous fix. Have you had a chance to compare IPv4 vs IPv6, or to check the updated version against the stock 1.5.1 release?
