### ISSUE TITLE
Support for multiple JACK servers

### ISSUE THREAD

**Issue by vrslev** [jacktrip/jacktrip#491]
Currently JackTrip assumes that JACK server that user chooses is named “default”. This is standard behavior when custom name is not specified. It would be nice to be able to _choose_ which server to use: `jacktrip --jack-server-name myfancyname ...`.

My use case is one server to many clients. I’m working on an app on top of JackTrip and JACK. The thing is, that I can’t _isolate_ client from server in tests on one machine.

If you guys decide it is decent feature to add, I’m happy to contribute 👋

**Comment by ntonnaett** [comment]
There's an environment variable for that. So it's working already. But you are not the first one asking about that feature. Maybe it would be a good idea to expose the feature. Let's see what others think about it!

**Comment by vrslev** [comment]
Yeah, that would be cool. Just checked if environment variable works for me — it does! So you helped me already anyway 😊

**Comment by ntonnaett** [comment]
We might just want to add a page to the user documentation about this. If you are in the urge to use a second jack server, you usually know how to change an environment variable. I'm also not too keen about cluttering the gui more.

**Comment by vrslev** [comment]
@ntonnaett As I understand, you don't have proper user documentation for now. Where should we put info about this?

**Comment by ntonnaett** [comment]
Our documentation uses MkDocs. [How to write Documentation](https://jacktrip.github.io/jacktrip/Documentation/MkDocs/). There's a `requirements.txt` in the [docs directory](https://github.com/jacktrip/jacktrip/tree/main/docs). `pip install -r requirements.txt` installs all dependencies.

The User Guide in our documentation is really sparse right now. I would suggest adding another page (markdown file) there for special use cases. I would really appreciate somebody taking care of the user documentation.

**Comment by ntonnaett** [comment]
Thank you for documenting this!
