### ISSUE TITLE
Some failed builds don't show as failed in the CI

### ISSUE THREAD

**Issue by dyfer** [jacktrip/jacktrip#494]
As observed by @ntonnaett in https://github.com/jacktrip/jacktrip/pull/493#issuecomment-1046006532

At first glance it seems that failed qmake buids exit with status `0` - TBC

Logging this for myself (@dyfer) to check back later

**Comment by ntonnaett** [comment]
It's probably the ./build script that doesn't exit with the exit code of its commands like qmake. Can we use qmake directly?

**Comment by dyfer** [comment]
The script is doing a few things currently, like setting names of qmake commands based on OS, also checking for rtaudio libs presence (if rtaudio is requested). Since this has been a way to build JT for a while I wouldn't want to remove if altogether, and if it's there, I'd prefer to use that in CI - precisely for testing. There shouldn't be a problem making the script return the proper code but I can't look right now.

**Comment by dyfer** [comment]
Just to clarify: I'm not completely opposed of removing the build script if others want to do it, but I think it's useful - I use it :)

**Comment by psiborg112** [comment]
I think it's a useful script to have, and I think a lot of people who make their own builds are probably in the habit of using it.

**Comment by dyfer** [comment]
(fixed in #497)
