### ISSUE TITLE
Linux release artifacts include debug info

### ISSUE THREAD

**Issue by ntonnaett** [jacktrip/jacktrip#502]
It looks like our Linux release builds are debug builds. ~~We should deliver release builds and check that this is also the case for macOS and Windows.~~

```
$ file jacktrip
jacktrip: ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=4b583187cc16ad08d53067d25d345d5fe4c0dd73, with debug_info, not stripped
```

**Comment by ntonnaett** [comment]
Okay, it's a -g -O2 build. Do we need debug info? Stripping the binary shrinks the binary size from 16M to 794K on my system.

**Comment by ntonnaett** [comment]
Thinking about this more… it's not a real life problem. People with really small systems will build jacktrip themselves.

**Comment by dyfer** [comment]
I wouldn't mind making a smaller release build. Do I understand correctly that in order to do that `-g` should only be specified for the debug build?

**Comment by ntonnaett** [comment]
The size that ends up in memory is the same. Debug info won't get loaded. But when jacktrip crashes this debug info is useful to get meaningful error messages. The debug info can be split beforehand. That's what debug packages in Linux distributions are about. But all platforms handle this differently.

If we want to deliver smaller release builds, we should also deliver debug builds. Then people can use this to give us more information if they encounter any issues.

AFAIK the `-g` is implicit if you do a debug build. So removing this from the release build should remove the debug info.

**Comment by dyfer** [comment]
Keeping in mind that maybe this is not worth changing ATM...

> If we want to deliver smaller release builds, we should also deliver debug builds. Then people can use this to give us more information if they encounter any issues.

I'd argue that people who need and know how to use a debug build are also more likely to be able to build JT themselves. OTOH, lowering binary size saves everyone space/bandwidth, if only negligibly...

QMake .pro file [adds `-g` for all Linux builds](https://github.com/jacktrip/jacktrip/blob/main/jacktrip.pro#L131), which I guess is conceptually inaccurate. Unless we really want to keep debug info in the Linux release builds, I'd consider removing that. What do you think?
