### ISSUE TITLE
Do we need "binary" macOS release on top of the application and the installer?

### ISSUE THREAD

**Issue by dyfer** [jacktrip/jacktrip#512]
We currently offer three macOS release files: a single binary (e.g. to be manually placed in `/usr/local/bin` or similar and run from terminal), an application bundle (to be manually dragged to the `Applications` folder) and an installer, which copies the application bundle to Applications and then adds a link to `/usr/local/bin`).

I'm thinking that we probably don't really need the single binary on macOS, as one is much more likely to use the installer (or the application bundle when testing) and this extra file might be confusing to new users. What do you think?

**Comment by ntonnaett** [comment]
Sounds redundant to me. Except… what about installing different versions side by side?

**Comment by dyfer** [comment]
> what about ~installing~ using different versions side by side?

That's totally doable with multiple application bundles.

**Comment by ntonnaett** [comment]
Can you use application bundles from the terminal? I'm not a mac user.

**Comment by dyfer** [comment]
> Can you use application bundles from the terminal? I'm not a mac user.

Yes. Application bundle is just a folder with a certain structure. The binary is located in `<JackTrip>/Contents/MacOS/jacktrip`.

**Comment by ntonnaett** [comment]
Thanks! :)

**Comment by mattahorton** [comment]
Wish I had seen this ahead of time. Over on jacktriplabs/jacktrip, we pull the binary file to recreate and sign the bundle and installer (which is how it must be done according to Apple).

**Comment by mattahorton** [comment]
Realized I didn't finish my thought. I will keep the binary in the fork. There's no need to add it back.

**Comment by dyfer** [comment]
I think we could consider making JT labs signing steps added to the main build matrix and make them run conditionally if the secrets are available. What that, the same build matrix would produce unsigned binaries on the jacktrip repo (current behavior) and signed binaries on jacktriblabs repo, with no need to keep divergent repos updated.
