### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by reynolds087** [jacktrip/jacktrip#52]
Is Jacktrip supported for Windows? If so, where can I get information about building or finding a pre-compiled version for Windows 10 x64?

**Comment by cchafe** [comment]
You can follow the links at
http://chrischafe.net/jacktrip-loopback-server/
The loopback server is running and available for testing.
Chris

**Comment by Foaly** [comment]
Hey @reynolds087,
yes building/running on the windows platform is supported by jacktrip. There is no pre-compiled version right now and the build instructions for windown in `INSTALL.txt` are unfortunatelly a bit outdated, but it should be fairly straight forward to follow them, if you have ever build any other software from source. Also feel free to improve the instructions, if you got it working :)
