### ISSUE TITLE
Server stops clients randomly

### ISSUE THREAD

**Issue by ntonnaett** [jacktrip/jacktrip#521]
I have a weird jacktrip problem with my simulation setup: https://github.com/ntonnaett/dockemu-ansible

With 5 connecting clients everything seems normal. But when I connect e.g. 20 clients, the server seems to just stops some of the clients. But there is no message about timeouts. The client just says `Peer stopped!` and stops.

So I commented out the part in the source code where jacktrip reacts to the exit signal. And the clients stay alive but are getting nothing from the server.

I'm confused. In beginning I thought it would be the docker setup that just kills it because of OOM or similar. But as I said, the jacktrip clients keep running.

Server side (verbose):
```
[...]
AutoQueue: 7
AutoQueue: 7
AutoQueue: 7
AutoQueue: 6
AutoQueue: 6
AutoQueue: 6
AutoQueue: 6
AutoQueue: 6
AutoQueue: 6
AutoQueue: 7
AutoQueue: 33
AutoQueue: 6
AutoQueue: 30
AutoQueue: 8
AutoQueue: 62
AutoQueue: 24
AutoQueue: 14
Stopping JackTrip...
sending exit packet
AutoQueue: 59
JackTrip Processes STOPPED!
---------------------------------------------------------
releasing jacktripWorker so change patch
AutoQueue: 29
AutoQueue: 37
AutoQueue: 30
AutoQueue: 12
AutoQueue: 49
Stopping JackTrip...
sending exit packet
JackTrip Processes STOPPED!
---------------------------------------------------------
releasing jacktripWorker so change patch
AutoQueue: 38
AutoQueue: 6
AutoQueue: 53
AutoQueue: 7
AutoQueue: 26
AutoQueue: 61
[...]
```

**Comment by ntonnaett** [comment]
![jacktrip_server_recv_underruns](https://user-images.githubusercontent.com/8383722/160483060-7b1c20b4-9c3c-4289-bd03-3b0d80220088.png)
Graph of receive underruns.

**Comment by cchafe** [comment]
I can run a non-docker test to check -- is this 1.5.3 and is it server and client on same host?

**Comment by ntonnaett** [comment]
It's 1.5.3, all on one host, through a ns3 network simulation. Thanks for testing :)

BTW do you know why those io statistic numbers are resetting now and then?

**Comment by cchafe** [comment]
Depends on which stats output. Copy me the server and client commands you're using...

**Comment by ntonnaett** [comment]
serverCommand:
`jacktrip -V -S -z -p4 --udprt -q auto -I 1 -G /var/log/dockemu/jacktrip-io.log > /var/log/dockemu/jacktrip-server.log &`
clientCommand: 
`jacktrip -V -C 10.12.0.240 -z --udprt -q auto -x 1 -I 1 -G /var/log/dockemu/jacktrip-io.log > /var/log/dockemu/jacktrip-client.log &`

**Comment by ntonnaett** [comment]
I changed the io stats output `-I` to a csv style to be able to parse it. Aand… I didn't test buffer strategy 3 yet.

**Comment by cchafe** [comment]
Running a bunch of clients on my laptop I don't see a problem -- all start and stop normally. Here's the testing script. I did modify the client command a bit including --nojackportsconnect. I write the start and stop status of the ensemble in a file with
/loop.sh > /tmp/xxx.dat

If this is useful, we can put it in jacktrip/scripts/hubMode
/////////////////////////////////////////////
loop.sh
/////////////////////////////////////////////
#!/bin/bash
#from jacktrip/scripts/hubMode
#./loop.sh > /tmp/xxx.dat
startPort=4464
nClients=32
secs=256
for (( i=$startPort; i<$startPort+$nClients; i++ ))
do
	cp -p ../../jacktrip /tmp/jacktripClone$i
	/tmp/jacktripClone$i -C localhost --udprt -q 12 -B $i --nojackportsconnect &
done

for (( i=0; i<$secs; i++ ))
do
	echo $i
	sleep 1
done

for (( i=$startPort; i<$startPort+$nClients; i++ ))
do
	killall /tmp/jacktripClone$i
done
sleep 1
echo "done"

**Comment by psiborg112** [comment]
Given this hasn't come up as an issue elsewhere, it does seem like something about the docker set up is causing this. 

You'll need to find out what is triggering the sending of the exit packet. (See line 666 of UdpDataProtocol.cpp) It's unlikely to be a change to JackTrip::sigInt because this shouldn't be hooked up to our interrupt handler in hub server mode (That's taken care of in UdpHubListener). So most likely something will have set mStopped to true by either directly calling JackTrip::slotStopProcesses or JackTrip::slotStopProcessesDueToError, or (and this is more likely) by emitting a signal that has been connected to one of these slots. There are a few places in the code where this happens, so you might need to add some debug output to find out which one is the culprit.

**Comment by ntonnaett** [comment]
It's gone now. Maybe it's the latency histogram. Have to investigate more.
