### ISSUE TITLE
Cannot connect other than port 4464

### ISSUE THREAD

**Issue by upretyrohan** [jacktrip/jacktrip#522]
Start a server ./jacktrip -S -B 4461
Start a client ,/jacktrip -C 192.168.2.3 -P 4461

No other port except 4464  default works 

what is the soln

**Comment by psiborg112** [comment]
I can't reproduce this. It works (almost) as expected here. (For some reason changing -B is also affecting the udp base port.) But the server listens on 4461 and the client is able to connect.

**Comment by psiborg112** [comment]
Seems like that the change to the udp base port is deliberate (line 100 in UdpHubListener.cpp).  I get the rationale behind it, but it's not currently documented in the help screen, and I don't know that it's ultimately all that useful. Other devs, thoughts? Should we get rid of this or just document it better?

**Comment by cchafe** [comment]
I couldn't reproduce the problem either, works fine with the calls posted originally:
-S -B 4461 / -C <host_ip> -P 4461

The current code allows multiple servers on the same host, for example on localhost run
-S -U 60999 /  -C localhost -B 4461
plus this pair at the same time
-S -B 4465 / -C  localhost  -P 4465

**Comment by upretyrohan** [comment]
problem due to port blocking

**Comment by psiborg112** [comment]
@cchafe yeah, I totally get the rationale behind why it the base udp port is automatically changed, but it did seem like a bug until I looked at the code. (Especially since the GUI handles it differently.) Maybe we just need better documentation?
