### ISSUE TITLE
Ubuntu 20.04 / Qt 5.15 static build compatibility

### ISSUE THREAD

**Issue by ntonnaett** [jacktrip/jacktrip#546]
This is _extremely_ fresh 20.04 (booted off usb) attempting to run the static build with rtaudio. I had to install `libxcb-xinerama0-dev` and it still loads to a blank screen for 5.12/5.15 incompatibility reasons (see last screenshot).

![Screenshot from 2022-05-05 22-29-53](https://user-images.githubusercontent.com/5567285/167035667-da06972b-c23e-44bf-9940-19d76c139b85.png)
![Screenshot from 2022-05-05 22-29-21](https://user-images.githubusercontent.com/5567285/167035672-2d63efd7-76ec-467e-96ac-d882cd706023.png)
![Screenshot from 2022-05-05 22-35-03](https://user-images.githubusercontent.com/5567285/167036070-10006a6f-c944-4f2b-bb3a-23e85ee04dca.png)

_Originally posted by @mattahorton in https://github.com/jacktrip/jacktrip/pull/545#discussion_r866362639_

**Comment by mattahorton** [comment]
Thanks for doing this @ntonnaett. Going to try my hand at getting things to work on 5.15 with xcb before doing anything else.

**Comment by dyfer** [comment]
I think we can close this with the fix in #559 
Thanks for testing @ntonnaett !
