### ISSUE TITLE
Lambdas: Capture by reference?

### ISSUE THREAD

**Issue by ntonnaett** [jacktrip/jacktrip#547]
There are several new lambdas introduced with the virtual studio mode. Some of them capture by value. That could lead to performance problems or unwanted copies.

I've got following with scan-build. Maybe that's related too.
```
[68/71] Compiling C++ object jacktrip.p/src_gui_virtualstudio.cpp.o
../../../src/gui/virtualstudio.cpp:840:33: warning: Access to field 'm_refreshInProgress' results in a dereference of a null pointer [core.NullDereference]
            m_refreshInProgress = false;
            ~~~~~~~~~~~~~~~~~~~~^~~~~~~
../../../src/gui/virtualstudio.cpp:920:14: warning: Access to field 'm_allowRefresh' results in a dereference of a null pointer [core.NullDereference]
        if (!m_allowRefresh) {
             ^~~~~~~~~~~~~~
2 warnings generated.
```

_Originally posted by @ntonnaett in https://github.com/jacktrip/jacktrip/pull/545#discussion_r866212351_

**Comment by psiborg112** [comment]
It made sense for those to be by value when the code started out, but should have checked that when the scope increased. Have changed to capture by reference where it makes sense. (Will upload soon.)

**Comment by ntonnaett** [comment]
I think this is resolved. I'll create a new issue about the scan-build warnings that we can forget about then.
