### ISSUE TITLE
Missing properties

### ISSUE THREAD

**Issue by ntonnaett** [jacktrip/jacktrip#548]
With the meson build I get these:
```
qrc:/vs/Connected.qml:36: TypeError: Cannot read property 'canConnect' of undefined
qrc:/vs/Connected.qml:35: TypeError: Cannot read property 'isManageable' of undefined
qrc:/vs/Connected.qml:34: TypeError: Cannot read property 'isPublic' of undefined
qrc:/vs/Connected.qml:33: TypeError: Cannot read property 'name' of undefined
qrc:/vs/Connected.qml:32: TypeError: Cannot read property 'flag' of undefined
qrc:/vs/Connected.qml:31: TypeError: Cannot read property 'location' of undefined
```

~~The ./build build doesn't quit cleanly.~~ Can't replicate on dev anymore.

_Originally posted by @ntonnaett in https://github.com/jacktrip/jacktrip/issues/545#issuecomment-1118924414_

**Comment by psiborg112** [comment]
These aren't problematic and don't affect the functioning of the program at all. But I do have a workaround to silence them. The ./build build not quitting cleanly is something that will be unrelated to this.

**Comment by psiborg112** [comment]
(also, what platform is that on?)

**Comment by ntonnaett** [comment]
That's Fedora 35, Gnome, Wayland.

Is it just random that I didn't get those Errors when using the qmake build?

**Comment by psiborg112** [comment]
As mentioned, this isn't actually a real problem for how the program operates. But I have written a fix so that this will be silenced. It's in #551.

**Comment by psiborg112** [comment]
So if the build not quitting cleanly is no longer an issue, then I think this is resolved.
