### ISSUE TITLE
Please add FreeBSD to the list of systems where jacktrip works

### ISSUE THREAD

**Issue by yurivict** [jacktrip/jacktrip#55]
```Linux, Mac OSX, or Windows multi-machine audio system```

The FreeBSD port exists: https://www.freshports.org/audio/jacktrip/

**Comment by Foaly** [comment]
Hey @yurivict 
thanks for your input! I don't run FreeBSD, so can't check if jacktrip runs there. Have you done some tests?
If thats the case please feel free to send a PR, so we can incorporate the information :)
Thank you!
