### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by dvzrv** [jacktrip/jacktrip#57]
Judging from the [documentation](https://github.com/jacktrip/jacktrip/blob/aaron/documentation/documentation.cpp#L6-L28), I assume, that jacktrip is MIT licensed.
For packaging and contribution purposes it would be very helpful if you would state under what license the code is released under.
Usually the license is added in a `LICENSE` file and any additional/ further clarifications should be done either in the `README.md` or in a separate `COPYING` file.

**Comment by dvzrv** [comment]
FYI: I currently have to extract those lines from that file to get a license file that I can package.

**Comment by MmmMDF** [comment]
Please add a license

**Comment by ntonnaett** [comment]
@cchafe Can you confirm that everything in jacktrip's repository is MIT licensed?

**Comment by cchafe** [comment]
Yes, confirmed. And a separate file at the top-level (LICENSE.md) would
be nice to add.Copyright should be updated to 2020 and show the same
copyright statement found inthe individual source files.
