### ISSUE TITLE
Remove setupScreen multiplier

### ISSUE THREAD

**Issue by mattahorton** [jacktrip/jacktrip#572]
This merged too soon. The way to fix those fly through issues is not to add arbitrary multipliers to the position, but to ensure that the zorder is correct. The Setup window needs to be created under the login and browse windows.

_Originally posted by @psiborg112 in https://github.com/jacktrip/jacktrip/issues/569#issuecomment-1129338525_

**Comment by psiborg112** [comment]
I've taken care of this in the dark mode fixes that are about to be committed.
