### ISSUE TITLE
1.6.0-rc.1 -- switching GUI modes  doesn't release UDP port

### ISSUE THREAD

**Issue by cchafe** [jacktrip/jacktrip#584]
(at least in Windows)
run a connection from VS mode, disconnect, switch to classic and try a new connection

**Comment by mattahorton** [comment]
I've run into this and didn't know what to do about it or call it. 

@psiborg112 I would love your help on this, but I'm happy to do the work.

**Comment by psiborg112** [comment]
Thankfully a one line fix
