### ISSUE TITLE
questions about INSTALL.txt

### ISSUE THREAD

**Issue by michaeldessen** [jacktrip/jacktrip#60]
I am very grateful to all of you working on the new version, thank you! I use jacktrip a lot and have some suggestions for the install.txt file. Let me know if I should do a pull request instead but in case I'm misunderstanding something, I wanted to ask here first:

1. line 14-15 ("$ sudo cp jacktrip /usr/local/bin/"): this sudo commands no longer works on Macs (since 10.11) due to System Integrity Protection, and on 10.15 it doesn't even work if you disable SIP because that OS runs from a read-only partition. I have instead been instructing people  to cd to jacktrip/src whenever using jacktrip, which is simple and works fine, so maybe that could be explained here, unless someone knows a simple way to get around the read-only partition problem in Catalina.

2. lines 67: "http://www.jackosx.com/" no longer exists. I'd suggest something like:
"If you want to build on MacOS X, you need the JACK2 for OSX, available as a binary (version 0.92_b3) here: <https://jackaudio.org/downloads/>.

3. The sudo commands on line 95ff are repeated from the ones on line 15ff and in general the flow of sections in this document is very confusing. (It also omits Windows in the title at the very top, but then has a section on Windows further down.)

4. Lines 149-157 repeat the same link with 2 different texts.

5. This is probably my ignorance but I find the build instructions very confusing. I've tried to build the new master branch using Qt but have not been successful. If anyone could share further tips on how to build it (I'm on a Mac 10.14) I'd be grateful, since I'd love to try out the new version.

Thanks!

Michael Dessen

**Comment by omarcostahamido** [comment]
+1
I would even suggest splitting that doc into two:
- INSTALL.md
- BUILD.md

**Comment by ntonnaett** [comment]
I would appreciate if you could do a pull request. The first two points look legit to me. Point 3 shows the confusing overall structure of the document. There is a lot of redundancy because it repeats itself for every OS. I don't think splitting it into INSTALL and BUILD helps here. But maybe splitting it into:
- INSTALL_linux.md
- INSTALL_mac.md
- INSTALL_windows.md

If nobody disagrees, maybe you could rip out everything related to MacOS and put it in a new file. 

Point 5: Could you open jacktrip.pro with QtCreator? I don't know why but actually the build script is prepared for Mac. Could you try to just ./build in the src directory?

**Comment by michaeldessen** [comment]
Thank you. I could start a INSTALL_mac.md file, or if people prefer I could create a single INSTALL.md file for all 3 platforms and try to organize it more clearly. I'll wait a few days to see if anyone objects and will get to this soon.

About the build: I just tried again using Qt Creator 4.12.2 on macOS 10.14 and was now able to successfully open jacktrip.pro and configure then build with the kit Desktop Qt 5.15.0 clang 64bit. I can "run" from Qt Creator and see the new v 1.2 help page, so the build must have worked. However, I don't know how to actually use the 1.2 version because even if I'm in /src it finds my previous 1.1 version and displays that one whenever I input jacktrip. If anyone has a moment to tell me what I'm doing wrong, thanks in advance.

Michael

**Comment by ntonnaett** [comment]
Sounds like a good plan.

You have to type ./jacktrip to use the binary in the current directory. I'm working also on a meson.build file right now. Maybe that will make the build process more convenient for everybody.

**Comment by michaeldessen** [comment]
Thank you! I can now test it out with people (as long as there are no problems with me running 1.2 and clients running 1.1).

**Comment by daveccrma** [comment]
Hi Folks, I've been building the Mac binaries during the 1.2 cycle at CCRMA and will write something up later today.

**Comment by michaeldessen** [comment]
Dave, that would be fantastic, thanks. FYI in case this could be addressed in the instructions (?) although I can build w/ Qt Creator as I wrote above, the error I get when trying to build in the /src directory is:

~/Desktop/jacktrip-builds/jacktrip-1.2/src $ ./build
Building on Mac OS X
./build: line 41: qmake: command not found
make: *** No rule to make target `clean'.  Stop.
./build: line 43: qmake: command not found
make: *** No rule to make target `release'.  Stop.

**Comment by michaeldessen** [comment]
Also, I see that there is not yet a binary in the 1.2 release that Chris put up last night. Are you planning to add one? Thanks!

**Comment by daveccrma** [comment]
Hi Michael - working on all these things today and tomorrow.

**Comment by michaeldessen** [comment]
Thanks Dave! FYI I just edited my comment above to make sure it was clear that I already submitted a pull request with a new INSTALL_mac.md file, in case you hadn't seen that. But the build instructions there are minimal and you will probably see other things to improve as well.

**Comment by ProfJanetDavis** [comment]
I haven't read this thread carefully, but I also found the Mac installation instructions incomplete. Here's what I did. You can tell me if any steps were unnecessary:

1. Install JackAudio v2 from https://jackaudio.org/downloads/.
2. Install Ardour from https://community.ardour.org/download
3. Install XCode from App Store
4. Install XCode Command-Line tools: see https://developer.apple.com/library/archive/technotes/tn2339/_index.html
5. Install Homebrew (I did this a while ago.)
6. `brew install qt` (I also installed from Qt from a manually downloaded installer, but don't actually know if that was necessary)
7. `git clone https://github.com/jacktrip/jacktrip.git`
8. `cd jacktrip/src`
9. `./build`
10. sudo cp jacktrip /usr/local/bin/

**Comment by ProfJanetDavis** [comment]
**Updated instructions with [Homebrew](https://brew.sh/)!**

<pre>
brew install rtmidi
brew install jack
brew install qt
git clone https://github.com/jacktrip/jacktrip.git
cd jacktrip/src
./build
sudo cp jacktrip /usr/local/bin/
</pre>

I would be thrilled if someone else would try these instruction and see if they work!

**Comment by ntonnaett** [comment]
With #76 we would have a separate build directory (builddir in the root directory). Your instructions look like what's travis is doing.

**Comment by professorbeautiful** [comment]
Hi, I'm just an ordinary musician, ... hope you don't mind my question here...
On High Sierra 10.13.6, running the installer jack2-osx-1.9.14_v4
"Installation Failed.  The installer can't locate the data it needs to install the software."
Any hints what I should do to solve it?
Thank you.

**Comment by SynthiaPayne** [comment]
Hi Roger. Welcome to the Jacktrip list. A lot of people think that JACK and Jacktrip are the same app but they’re different. Your question is about JACK so it would be best asked in the JACK support. I would start over and try installing again and carefully follow the instructions. Good luck! Synth

**Comment by professorbeautiful** [comment]
Thanks!   I (roughly) know the difference, but desperation is as desperation does!   
😁
Grateful for all the work you've done!

**Comment by michaeldessen** [comment]
Hi Roger,

That version you mention (jack2-osx-1.9.14_v4) may not work. You should use the Jack version linked here (in the first section "Installing Jack"):

https://ccrma.stanford.edu/software/jacktrip/osx/index.html

That installer should work with High Sierra, and you should also use the JackTrip installer listed in step 1 of the section on that same page "Installing JackTrip"), as well as the other instructions on that page. 

The Mac instructions in the "INSTALL.txt" file here on Gitub is not as up to date as that page linked above. Best,

Michael

**Comment by professorbeautiful** [comment]
Thanks!   I followed your advice & it worked!

**Comment by wholenotes** [comment]
INSTALL.txt is now up-to-date on the main branch.
