### ISSUE TITLE
add -S -C commands to help page

### ISSUE THREAD

**Issue by michaeldessen** [jacktrip/jacktrip#62]
In the new version help page I see the -p command explained but isn't it also necessary to add something under Required Arguments like this, below the 2 lines there now? Otherwise it won't be clear to people how to start Hub mode:

-S, --Server                                                  Run in Server Hub Mode
-C, --Client <peer_hostname_or_IP_num>   Run in Client Hub Mode

Michael

**Comment by ntonnaett** [comment]
Yes. Good point. The --queue and --redundancy are redundant therefor.

**Comment by ntonnaett** [comment]
Fixed by #65
