### ISSUE TITLE
1.6.0 doesn't timeout

### ISSUE THREAD

**Issue by cchafe** [jacktrip/jacktrip#627]
if a hub client disappears (just stops sending audio, rather than with an exit packet) the hub server doesn't kick it out like it used to up through 1.5.3

adding -t to the server args doesn't help

**Comment by psiborg112** [comment]
#624 is the culprit. Someone commented out the "emit signalWaitingTooLong(waitTime)" call on line 675. (Was there a reason for this?) It totally disables the timeout code.

**Comment by psiborg112** [comment]
Fixed in #628. This should probably be rolled into a 1.6.1 bug fix release ASAP.

**Comment by psiborg112** [comment]
Also, seems I incorrectly assigned blame for this. It was merged somewhere before #624.

**Comment by psiborg112** [comment]
Found it! It was a regulator test that wasn't removed prior to merge.

**Comment by cchafe** [comment]
thanks! -- I saw that but failed to grok why it was commented out (and I'm the probable culprit)
