### ISSUE TITLE
build scripts: macOS 10.15 environment is deprecated by Github

### ISSUE THREAD

**Issue by mattahorton** [jacktrip/jacktrip#655]
<img width="882" alt="Screen Shot 2022-07-15 at 1 42 55 PM" src="https://user-images.githubusercontent.com/5567285/179290714-6e16b154-ae2a-4e5c-b62d-568b0300ea41.png">

Our macOS builds run on 10.15. 

We need to update to macOS 11.

**Comment by ntonnaett** [comment]
Should we switch to macos-latest, because it isn't the latest and we wouldn't need to think about this in the future?

**Comment by mattahorton** [comment]
yep good point. I've updated to `macOS-11` in my current working branch but will change to `-latest`.

**Comment by dyfer** [comment]
> Should we switch to macos-latest, because it isn't the latest and we wouldn't need to think about this in the future?

The downside of this is that it will switch on us, eventually. But if we don't care about exact versions of toolchains for release builds, that's maybe okay.

As we're currently using macos-11, I think it's okay to close this?
