### ISSUE TITLE
win 11: audio degradation when interface not in front

### ISSUE THREAD

**Issue by SynthiaPayne** [jacktrip/jacktrip#663]
On Windows 11 - JackTrip version 1.6.1 with or without external interface, JACK or RT Audio

When in an active JackTrip session audio becomes fuzzy and unrecognizable when another app is in front of the JackTrip interface or when the JackTrip interface is minimized. 

Upon returning the JackTrip interface to the frontmost position, the audio clears again. 

Weird huh?

**Comment by ntonnaett** [comment]
Interesting. There is a discussion about throttling background applications in windows11 [on reddit](https://www.reddit.com/r/Windows11/comments/q8r5fg/is_windows_11_purposefully_throttling_background/) and [on the microsoft forum](https://answers.microsoft.com/en-us/windows/forum/all/disabling-under-prioritization-of-background-tasks/c4749a47-76f0-4c5c-bb30-b9d319f610fc). Maybe you could look into performance settings in the Advanced System Settings…

Maybe we have to change how we set the process priority on Windows.

**Comment by SynthiaPayne** [comment]
Thanks much for your suggestion and just went through a number of 
settings changes discussed on those forums, one by one, and nothing 
changed.

Following is what I tried one by one then tested but with no change: 
switched Process Scheduling Priority from Program to Background Apps; in 
Task Manager - JackTrip - set Priority from Normal to "Realtime"; 
switched to 'best performance" from 'best appearance'; switched off MS 
updates delivery optimizations; uninstalled OneDrive; disabled email 
bridge app.

Happy to keep trying stuff.

synth

**Comment by forsythac** [comment]
This is really interesting- I feel like I may have experienced this also without knowing the cause. Any chance we can get an audio recording of the issue? I'll try to do so as well

**Comment by SynthiaPayne** [comment]
Quick and dirty video shows when JackTrip interface is in the background 
behind a webpage, the audio degrades.

https://youtu.be/09P1x5gGHeo

**Comment by OConnorStP** [comment]
Excellent!  More later. I ran out of time this AM but there’s a lot to explore in your demo.

**Comment by psiborg112** [comment]
It's the mac issue all over again. If this is anything like that, then there may be more to it than simply setting the process priority. (In that case, it was a separate, poorly documented API call that was only available in Objective-C.) It's annoying that all of these power saving/foreground prioritising mechanisms are being made opt-out when there's no clear, readily available information about them.

**Comment by OConnorStP** [comment]
Yep. That’s sure what it reminds me of too. 

And old friend. :-)

**Comment by forsythac** [comment]
Hey team, have we still been experiencing this issue? Just doing some cleanup :)

**Comment by SynthiaPayne** [comment]
as of this morning, still happening with version 1.6.4 for Windows

**Comment by SynthiaPayne** [comment]
I'm on a roll closing tickets here! Decided to test out this bug with 1.8.0, and no longer hearing the audio degrade when the interface is behind other windows. It's like magic! Thanks all.
