### ISSUE TITLE
qmake build doesn't generate metainfo file

### ISSUE THREAD

**Issue by ntonnaett** [jacktrip/jacktrip#724]
The qmake build produces an empty metainfo file, because there is no metainfo.xml.in file anymore. This file has to be generated with add_changelog_to_metainfo.py out of metainfo.xml.in.in. It introduces dependencies from python3, the jinja2 and yaml modules.

**Comment by mikedickey** [comment]
Especially with the move to Qt6 (which doesn't even use qmake anymore), perhaps it is time to retire qmake in favor of meson?

**Comment by ntonnaett** [comment]
Yes. All Linux distributions actually use Meson for a long time now. We can close this.

Maybe we should also make the deprecation clear in the documentation and decide when to remove qmake eventually.
