### ISSUE TITLE
JackTrip Hub Server ignores specified bit resolution

### ISSUE THREAD

**Issue by ATell-SoundTheory** [jacktrip/jacktrip#742]
Independent of the platform, starting JackTrip with
`jacktrip -S -b24`
or any other bit-depth other than the default 16 will result in the hub server declining client connections that are not 16 bit. This makes it impossible to create a high resolution hub server.

Possible cause: mJackTrip instantiated in JackTripWorker is never set to the proper bit depth from the command line arguments. Interestingly, *sampling rates* set from jackd are properly detected. In my setup, this is with jackd running with the following settings:
`jackd -R -t500 -ddummy -r96000 -p256`
Specifying the *bit resolution* on jack's side for a dummy device is not possible. So the problem may be related to not receiving a bit-depth from jackd.

Possible workaround: Patch JackTrip.cpp to change the default value for the bit resolution constructor argument.

**Comment by psiborg112** [comment]
This is fixed in #749 and should make it into the next release.
