### ISSUE TITLE
Virtual Studio gui doesn't build with Qt 6

### ISSUE THREAD

**Issue by dyfer** [jacktrip/jacktrip#767]
It seems that JackTrip `novs` can be built with Qt 6 and it runs fine.

Unfortunately, the Virtual Studio configuration does not...

Virtual Studio would build with fixes from @ntonnaett (https://github.com/jacktrip/jacktrip/pull/557/files#diff-9d598cad48c3c07dae12f45542ac57b3e871278c47e95b1143d6b92043a8906fL795-L798 and a similar one [further down](https://github.com/jacktrip/jacktrip/blob/main/src/gui/virtualstudio.cpp#L1240-L1244)), but the VS interface is blank once the application runs.

One issue I believe is that Qt6 doesn't include `QtGraphicalEffects`.

To build jacktrip with qt6, you can use the qmake build script the same way as usual. Just make sure that qmake from qt6 is first in PATH, e.g on macOS. 
```sh
PATH=`brew --prefix qt6`/bin:$PATH ./build rtaudio weakjack
```

**Comment by ntonnaett** [comment]
Does #557 behave the same for you? Because on Fedora the application renders fine (better than Qt5).

**Comment by dyfer** [comment]
@ntonnaett thanks for chiming in.
Indeed, #557 behaves differently. I _initially_ get the VS screen, but it reverts to blank window once resized.

**Comment by ntonnaett** [comment]
Yeah, but maybe this would be fixed if I rebased it. I saw several qt6 fixes lately that are not included in that branch. It's great seeing people working on qt6 support. I would like to switch sooner than later.

Regarding `QtGraphicalEffects`, there's `Qt5Compat.GraphicalEffects` in qt6. But that's only a temporary fix.

**Comment by dyfer** [comment]
> Regarding `QtGraphicalEffects`, there's `Qt5Compat.GraphicalEffects` in qt6. But that's only a temporary fix.

Yeah... maybe that's an okay solution for now? I don't know.

**Comment by mattahorton** [comment]
If that's the only change, we can find a replacement for the GraphicalEffects needs.

**Comment by mattahorton** [comment]
it sounds like qt5compat will have to be the way for now. everything else I can find is a commercial license.

**Comment by dyfer** [comment]
It seems that one can't conditionally import a different library in qml based on Qt version. I know very little about QtQuick/qml, but looking online and trying things out it seems that supporting both qt5 and qt6 is somewhat complicated... is that really the case?

**Comment by psiborg112** [comment]
From what I've been able to work out, it doesn't seem possible. The easiest way unfortunately seems to be having different qml files for qt5 and qt6, and different qrc files to include the right version of the qml file. There's an alias attribute in qrc files so that whichever version of the qml file is included, internally it can be referenced using the same name. (You can see an example of this in the CMakeLists.txt file of my branch: it edits the qrc file at configure time to point to the right image and icon files.)
