### ISSUE TITLE
Option for client to send mono, receive stereo

### ISSUE THREAD

**Issue by mikedickey** [jacktrip/jacktrip#78]
Currently, one can use the -n parameter to specify mono or stereo, but this applies to both directions. I would like to be able to specify a different number of send versus receive channels.

Justification: Most Internet connections have significantly better downstream versus upstream performance. Furthermore, most musicians likely are only sending a mono audio signal to JackTrip. However, there is great value to mixing a stereo signal on the server (adding panning, reverb, etc) and returning stereo back to these clients. Today, this requires using twice as much upstream bandwidth as necessary (sending same signal twice, or sending on empty channel), which may be too much for some Internet connections. Even if they have "enough" bandwidth, more utilization may contribute to more jitter, and lead to a poorer experience overall.

Desired behavior is to split this into two parameters: one for send channels, and one for receive channels. This would allow clients to send mono sound, and receive a stereo mix back from a hubpatch server.

**Comment by kltdwrds** [comment]
Any pointers for how this would best be accomplished?  I'm new to the code base, but interested to contribute. Thanks!

**Comment by mikedickey** [comment]
Another example use case for this is if I have 4 audio channels that I want to send (say 4 instruments or microphones in different locations), mix on the server with other streams coming from other locations/musicians, and then receive back the stereo mix.

You could also flip it and say I just want to send 1 channel (my microphone), but receive 4 channels back from an ambisonic mix on the server of a larger, combined group. Receiving stereo makes most sense for headphones, but the potential applications for JackTrip are much broader.
