### ISSUE TITLE
1.6.5 deleted?!

### ISSUE THREAD

**Issue by dvzrv** [jacktrip/jacktrip#785]
Hi, I'm packaging jacktrip for Arch Linux.

Yesterday there was still a 1.6.5 release and tarball and I have packaged using that: https://github.com/archlinux/svntogit-community/commit/b5a2fc2f96fb4f09102f8cd491e6969048d31046

What happened to that tag? Please don't delete tags! It breaks downstream trust and (reproducible) builds!

**Comment by dvzrv** [comment]
ping @psiborg112 @mattahorton @ntonnaett @cchafe

**Comment by dvzrv** [comment]
This is the source tarball that was generated by github, from which I built:
[jacktrip-1.6.5.tar.gz](https://github.com/jacktrip/jacktrip/files/9895495/jacktrip-1.6.5.tar.gz)

The diffoscope diff to 1.6.5-rc1 is:
[jacktrip-diffoscope.log](https://github.com/jacktrip/jacktrip/files/9895497/jacktrip-diffoscope.log)

**Comment by dvzrv** [comment]
While the diff does not seem harmful I will force downgrade the package now.
A heads up or even response to this ticket would have been nice...

**Comment by psiborg112** [comment]
Releases are handled by the JackTrip Labs crew because of binary signing on mac and windows, and not by the open source contributors. (@mattahorton is probably the person to contact for these things.) In this case they pulled the release because of an issue with with notarization on mac. (I updated a script because apple have changed their notarization workflow. It works fine on my local machine, but not in github actions, and we need to find out why.) I suspect nothing will change in the code between the release being pulled and made available again. But don't quote me on that.

**Comment by dvzrv** [comment]
> In this case they pulled the release because of an issue with with notarization on mac.

Why pull the release that others already rely upon (without notice) in that case though? It is just the notarization for macOS failing, not the build.
For introducing post-release artifact fixup releases for macOS you can e.g. rely upon [build metadata](https://semver.org/#spec-item-10), as you seem to closely follow semver. They order properly after e.g. 1.6.5 but before 1.6.6. This is e.g. how SuperCollider deals with the mess that is notarization in case it fails for the respective release (there is no and never will be a guarantee that this brittle service will always work out of the box).

> I suspect nothing will change in the code between the release being pulled and made available again. But don't quote me on that.

From a downstream perspective this doesn't really matter, as the release tarball has changed once you tag 1.6.5 again and breaks the build (the checksum is locked).
What changed how when 1.6.5 disappeared was in this case up for downstreams to figure out, and that is IMHO really not a great move, as a release like this could have meant a [supply chain attack](https://en.wikipedia.org/wiki/Supply_chain_attack) potentially affecting many users.

What will you do to mitigate these situations in the future?

**Comment by ntonnaett** [comment]
I totally agree. As I already said in #784, we should elect a maintainer and write (or find) guidelines.

Thanks for your point about locked checksums. Do you think it's better to skip 1.6.5?

**Comment by mattahorton** [comment]
Hey @dvzrv that's my fault. Apologies. I wasn't aware of the implications, and it won't happen again.

**Comment by dvzrv** [comment]
> Thanks for your point about locked checksums. Do you think it's better to skip 1.6.5?

I don't know. So far the only downstream that picked this up was Manjaro in their testing repo, which just blindly reuses what I package for Arch Linux (in a snapshot) and I don't think they care much about reproducibility as they don't do reproducible builds. Otherwise the jacktrip versions seem all older: https://repology.org/project/jacktrip/versions

> Apologies. I wasn't aware of the implications, and it won't happen again.

Thanks!
