### ISSUE TITLE
Option to enable lossless compression for audio streams

### ISSUE THREAD

**Issue by mikedickey** [jacktrip/jacktrip#79]
If I understand correctly, audio streams currently have no compression applied. If we could get even as little as 2x compression from using a lossless codec like FLAC, it would be WELL worthwhile and improve the experience for a broader range of users.

**Comment by npostavs** [comment]
Is there a lossless codec that is also low-latency? From what I've read, the (lossy) Opus code is specially designed for low-latency and adds 2.5ms delay at minimum. I would guess FLAC is not designed for that use-case so it would probably require a lot more delay than that.

**Comment by mikedickey** [comment]
2.5ms latency would be a perfectly acceptable tradeoff. The idea being this is an option, which is disabled by default.

As an end-user having an Internet connection with bandwidth of less than 2.0 Mbps (download or upload), I would like to be able to use JackTrip to perform live with other musicians.

Downgrading to mono or 8-bit (not yet supported in main) are other options, but these have a much more severe degradation in quality and experience. Also they both still have a pretty high bandwidth requirements.

**Comment by mikedickey** [comment]
For the record, #80 (using lossy like Opus) is very similar and would likely be a better investment than this one.

**Comment by npostavs** [comment]
> 2.5ms latency would be a perfectly acceptable tradeoff.

Right, the question is whether there is a lossless code which has such a low latency. https://en.wikipedia.org/wiki/Opus_(audio_format) says:

> Its delay is exceptionally low compared to competing codecs, which require well over 100 ms

I'm not sure FLAC counts as a competing codec for Opus, nor what exactly FLAC's delay is (I guess not very small since otherwise it would be listed as a feature). But 100ms is not such a good tradeoff...

**Comment by mikedickey** [comment]
Agreed; if that is the case, this definitely isn't worthwhile pursuing. Going to close it in favor of lossy.
