### ISSUE TITLE
Meter in Audio settings covers jack information text

### ISSUE THREAD

**Issue by ntonnaett** [jacktrip/jacktrip#793]
![JackTrip_1 6 6_meter_ui_bug](https://user-images.githubusercontent.com/8383722/199957527-c69981ed-d967-41aa-b4eb-d052fd60a173.png)

The meter ui seems broken for jack. Also, the test audio button does nothing. What is supposed to happen?

Version: 1.6.6 Flatpak / Xwayland
OS: Fedora 36
Environment: Gnome

**Comment by mattahorton** [comment]
gotcha. it shouldn't be displayed here
