### ISSUE TITLE
I Connect to my server and it immediately crashes 

### ISSUE THREAD

**Issue by LeLogon** [jacktrip/jacktrip#807]
I am Hosting a server on a dedicated machine. I have the default 4464 port open and ports 61000-610012 open. all settings are default. I have asio4 all downloaded on the server and a version of jack. Could one of them be outdated?

**Comment by LeLogon** [comment]
I get this feed in the debug menu 
![image](https://user-images.githubusercontent.com/15256855/202345026-a1fc0289-f10b-4a1a-a91b-9167f17baf6a.png)

**Comment by SynthiaPayne** [comment]
There is a JackTrip users google group list you can join and maybe get some answers. Your question pertains to user issues and this depot here is primarily for developers and code issues.

**Comment by SynthiaPayne** [comment]
I do see that the TCP connection is closed. Are UDP and TCP ports open?

**Comment by ntonnaett** [comment]
Can this be closed?

**Comment by SynthiaPayne** [comment]
Never heard back from the requester. If no one else has suggestions, 
it's probably safe to call it. Thanks.
