### ISSUE TITLE
MacOS: 1.6.7 UI hangs (spinning-ball) in long sessions

### ISSUE THREAD

**Issue by OConnorStP** [jacktrip/jacktrip#829]
I'm hoping this is an old issue that's already been fixed once.  When I run a 1.6.7 session for a while and return to it, Jacktrip's Classic UI is hung (spinning ball).  The session is still up and sounds fine.  But the VU meters freeze at the point that I touch the UI (they work fine until then).

I also noticed this happening with another player yesterday.

We **LOVE** the VU meters!!!!

**Comment by psiborg112** [comment]
Any specific ways to recreate this, or is this just something that happens after a long time?

**Comment by psiborg112** [comment]
Any updates on how to recreate this? Also, the meter code has been updated in #936 so it will probably be worth seeing if this persists into newer versions. (Once we have a release.)

**Comment by OConnorStP** [comment]
Hi Aaron.  I've been using the latest releases in hopes that the behavior would go away, but so far it hasn't.  It's really hard to recreate because it only happens after a long run.  Jumping in and out works fine, but if I'm in a session for an hour or so and return, I almost always have to force-quit. I forgot about this conversation because I've kinda gotten used to it.  Sorry not to bring more-helpful ideas.

**Comment by OConnorStP** [comment]
Ah, the recent conversation about Windows reminded me of this one.  Aaron, the spinning ball of death vanished with the switch to your build.  I've been running it for a week or so and haven't seen it since then.

**Comment by psiborg112** [comment]
Thanks Mike. I don't want to celebrate too soon, but hopefully that's done the trick. (And that code change is in version 1.8.0 of the official builds, so it should be fixed there as well.)

**Comment by mikedickey** [comment]
Closing issue, as I believe this was fixed a long time ago.
