### ISSUE TITLE
Underrun Mode Undefined on Starting Jacktrip Client -C

### ISSUE THREAD

**Issue by wholenotes** [jacktrip/jacktrip#83]
This message has appeared a few times when the jacktrip client starts with -C on the chris_plus_hub_servers branch:

Using UDP Protocol
---------------------------------------------------------
ERROR:
Underrun Mode undefined
Exiting JackTrip...

**Comment by ntonnaett** [comment]
I remember some compilation warnings regarding underrun mode.

**Comment by wholenotes** [comment]
Thanks for popping in.  This commit on the chris_plus_hub_servers branch may have fixed it: 882a464b459c67cbc7d6835bb9c743c2c7232a56.  Since there was never a discernible pattern for the occurrence of the error, I left this issue open for a while.  I've done further testing on the branch and haven't seen the error since, so I'm going to close this issue.  Feel free to message me directly if you'd like to discuss this further.  Looking forward to checking out your feature, btw.
