### ISSUE TITLE
Improve handling of client disconnect from hubpatch server

### ISSUE THREAD

**Issue by mikedickey** [jacktrip/jacktrip#84]
When a client disconnects from hubpatch server, the server prints the following error repeatedly (many times per second):

Jul 19 22:53:39 ip-172-30-0-35 jacktrip[2783]: UDP waiting too long (more than 30ms)...

This is a bit strange, because client disconnect should be a "normal" occurrence. Expected behavior would be a single disconnect notification.

Eventually, the following is logged:

Jul 19 22:53:39 ip-172-30-0-35 jacktrip[2783]: UDP WAITED MORE THAN 10 seconds.
Jul 19 22:53:39 ip-172-30-0-35 jacktrip[2783]: Stopping JackTrip...
Jul 19 22:53:39 ip-172-30-0-35 jacktrip[2783]: JackTrip Processes STOPPED!
Jul 19 22:53:39 ip-172-30-0-35 jacktrip[2783]: ---------------------------------------------------------
Jul 19 22:53:39 ip-172-30-0-35 jacktrip[2783]: releasing jacktripWorker so change patch
...

This seems to indicate that the client is being cleanly removed when no signal is detected for 10 seconds.

I think all of these logs are great for verbose/debugging mode, but having JackTrip log a single "client disconnected" event would otherwise be preferred.

A more serious problem is that this 10 seconds of UDP waiting generates a buzzing signal that is sent to every other participant on the server. It's sometimes not terrible, but it's always there, and more than once I've experieced a LOAD buzzing noise that caused everyone to cry out in pain.

**Comment by psiborg112** [comment]
Because UDP is a stateless protocol, there's no inherent way to tell the difference between a dropout and a deliberate termination of the client without a change to the way that the client and server communicate. (For the other devs, we could potentially implement the sending of a packet with a 'magic header' that would signal a shutdown. It's probably the easiest way to manage it, and something I'd be happy to look into when I have a bit of time.)

In the meantime, the buzzing is caused by a repetition of the last audio information received from the server by the client. You can get rid of it by using the -z option on the hub server, which zeros the output in case of dropped packets.

**Comment by psiborg112** [comment]
Meant to add that such a magic packet approach would also be a more long term fix to #77 than just a simple timeout.

**Comment by ntonnaett** [comment]
We need messaging also for other things such as dynamically adding and removing channels, changing buffer size or compression capabilities. So I think we should talk about a generic way of doing this. If this needs too much time to implement we could just send a magic header.

**Comment by psiborg112** [comment]
If we need messaging for other things too then it's probably worth taking the time to do it right and agreeing on a sensible protocol.

**Comment by psiborg112** [comment]
The qjacktrip branch now has an implementation of the magic packet approach if you're interested in testing it out.

**Comment by mikedickey** [comment]
Hi @psiborg112, is this magic packet implementation also included in your aaron branch (independent of the GUI work)?

**Comment by psiborg112** [comment]
Yes, it is. I'm trying to keep that branch as in sync with the qjacktrip branch as possible. (So it may occasionally lag by a day or two, but it's up to date at the moment.)

**Comment by mikedickey** [comment]
Hmm.. when I try a merge it has a lot of conflicts. Are you merging from master into your branch or copying changes manually?

**Comment by psiborg112** [comment]
Copying changes manually because it's been easier given the amount that's been altered in my branch (compared to the slower rate of change in master). Every time there's a commit I try to look for anything that applies and migrate it over.

**Comment by mikedickey** [comment]
That's why there are so many conflicts popping up when you try to do a proper merge. Keeping the merge points in sync avoids all kinds of problems with git. Might I suggest that you instead do a "git merge --no-commit", revert all the changes back with "git checkout HEAD ...", manually copy the changes over as you see best, and then commit the merge. This is way better because it at least keeps proper track of the merge points.

**Comment by mikedickey** [comment]
Hi @psiborg112 I tested aaron branch (commit 1ccc9e86df507f44068c1a4c93616c61ff8135b7) by shutting down hub server when a client is connected. It seems to have the same behavior as before where it just enters an unrecoverable infinite loop with a buzzing noise (even when using -z on the server).

One thing I did notice is that it prints "UDP WAITED MORE THAN 10 seconds" (which is new), but it doesn't seem to do anything about it. I think it should exit with error code.

```
Aug 06 17:52:39 20hz jacktrip[1898]: UDP waiting too long (more than 30ms) for 54.176.243.66...
Aug 06 17:52:39 20hz jacktrip[1898]: UDP waiting too long (more than 30ms) for 54.176.243.66...
Aug 06 17:52:39 20hz jacktrip[1898]: UDP waiting too long (more than 30ms) for 54.176.243.66...
Aug 06 17:52:39 20hz jacktrip[1898]: UDP WAITED MORE THAN 10 seconds.
Aug 06 17:52:39 20hz jacktrip[1898]: UDP waiting too long (more than 30ms) for 54.176.243.66...
Aug 06 17:52:40 20hz jacktrip[1898]: UDP waiting too long (more than 30ms) for 54.176.243.66...
Aug 06 17:52:40 20hz jacktrip[1898]: UDP waiting too long (more than 30ms) for 54.176.243.66...
```

**Comment by psiborg112** [comment]
Hi Mike,
Just a couple of questions:
Are you also running the client with -z? (-z on the server will prevent the sound of other clients dropping out from being passed on, but it won't zero the buffers on the client end if the server drops out.)
Is the hub server also running the aaron branch?
Was there much packet loss over the link?

But yes, probably should have the client disconnect on receiving the udp waited more than 10 seconds.

**Comment by mikedickey** [comment]
Ah ha! You got it! Adding -z to the client as well (not just server) took out the buzz!

If we could also get the client to just exit after 10 seconds, it will solve everything for me!

**Comment by psiborg112** [comment]
Yeah, I'll add that. Just wanted to check though whether the server was also running the aaron branch? (If it wasn't that would explain why there was no exit packet sent. Otherwise I might need to reconsider whether sending 1 redundant packet is enough.)

**Comment by psiborg112** [comment]
And added. (In aaron and qjacktrip.) Use the -t option (or GUI) to set jacktrip to stop after the 10 second timeout. (Works for server, client, and hub client modes.)

**Comment by mikedickey** [comment]
Sorry, yes I ran the same on both client and server. It’s a fiber connection with about 7ms ping between them, so I don’t believe much packet loss.

**Comment by psiborg112** [comment]
Thanks. Haven't been able to duplicate here. Does it always happen, or  just sometimes?

**Comment by psiborg112** [comment]
And just to check, how were you bringing down the server? Ctrl-C?

**Comment by mikedickey** [comment]
Confirmed that this does exactly what I needed. Thank you! This is going to help fix a lot annoying issues I've been dealing with.

With -t on client and non-aaron-branch jacktrip on server:
...
Aug 07 09:47:30 20hz jacktrip[5349]: UDP WAITED MORE THAN 10 seconds.
Aug 07 09:47:30 20hz jacktrip[5349]: Stopping JackTrip...
Aug 07 09:47:30 20hz jacktrip[5349]: JackTrip Processes STOPPED!
Aug 07 09:47:30 20hz jacktrip[5349]: ---------------------------------------------------------
Aug 07 09:47:30 20hz systemd[1]: jacktrip.service: Succeeded.

With aaron-branch-jacktrip on both client and server:

Aug 07 09:49:47 20hz jacktrip[5389]: Waiting for Peer...
Aug 07 09:49:48 20hz jacktrip[5389]: Received Connection from Peer!
Aug 07 09:49:54 20hz jacktrip[5389]: Stopping JackTrip...
Aug 07 09:49:54 20hz jacktrip[5389]: Peer Stopped
Aug 07 09:49:54 20hz jacktrip[5389]: JackTrip Processes STOPPED!
Aug 07 09:49:54 20hz jacktrip[5389]: ---------------------------------------------------------
Aug 07 09:49:54 20hz systemd[1]: jacktrip.service: Succeeded.

I'm using systemd to manage the processes, so based on docs I believe the default it uses for "stop" is a SIGTERM.

**Comment by cchafe** [comment]
Works great! (fedora - fedora, -S, -p1, -t)
Thanks for this, Aaron.

**Comment by psiborg112** [comment]
That would be why. I'd only set the handler to catch SIGINT so you would have needed to use kill -2. Have updated the branch to catch SIGTERM as well now. (So if you rebuild for both client and server and test again, you should get a "Peer Stopped" message in the console and it should quit out. Then you can just use -t as a backup in case any packet loss occurs and the exit signal doesn't make it through.)

**Comment by mikedickey** [comment]
Yes, I confirmed it stops right away when I shut down server running a service under systemd. Think it's ready to merge to dev?

**Comment by psiborg112** [comment]
Now that there is a dev branch, I think I can move features over to it more often. (There are a lot of additions to my branch.) There's a few conflicts that I'm going to have to resolve with the recent changes to dev, but then will make a pull request.

**Comment by mikedickey** [comment]
Hi @psiborg112 I just noticed a problem. When using -t on the client, it seems to run in "loopback mode" which is causing an audio feedback loop. From logs:

```
Aug 08 10:43:22 20hz jacktrip[3306]: ---------------------------------------------------------
Aug 08 10:43:22 20hz jacktrip[3306]: Running in Loop-Back Mode...
Aug 08 10:43:22 20hz jacktrip[3306]: ---------------------------------------------------------
```

Full command: `jacktrip -t -z -n 2 -C XX.XX.XX.XX`

**Comment by mikedickey** [comment]
This was resolved a while ago with the merge of @psiborg112 's updates
