### ISSUE TITLE
Jackmp.framework for MacOS?

### ISSUE THREAD

**Issue by jsl303** [jacktrip/jacktrip#88]
Where can I get the Jackmp.framework?
I' on MacOS 10.14.6, and I get the following when I try to run jacktrip.
```
dyld: Library not loaded: /System/Library/Frameworks/Jackmp.framework/Versions/A/Jackmp
  Referenced from: /usr/local/bin/jacktrip
  Reason: image not found
Abort trap: 6
```
I used brew to install qt5 and jack.

**Comment by dyfer** [comment]
It comes with the JackOSX package (JackOSX 0.92_b3)
https://jackaudio.org/downloads/

Cheers,
Marcin

**Comment by jsl303** [comment]
Thanks, that worked!

**Comment by jonbyler** [comment]
Hi,

I'm having this same problem in 2024.  I installed Jack using the OSX installer at the jack audio.org download page, and it does not load anything into the system/library/frameworks folder.  Can anyone help with this?
