### ISSUE TITLE
1.6.8 dependencies missing in Fedora

### ISSUE THREAD

**Issue by cchafe** [jacktrip/jacktrip#884]
I revved up Fedora 37 on a new machine and successfully did a
dnf install jacktrip

but trying to run it failed

**qrc:/vs/vs.qml:2:1: module "QtQuick.Controls" is not installed 
     import QtQuick.Controls 2.12** 

then did
sudo dnf install qt5-qtquickcontrols
but that wasn't enough

**qrc:/vs/vs.qml:2:1: plugin cannot be loaded for module "QtQuick.Controls": Cannot protect module QtQuick.Controls 2 as it was never registered 
     import QtQuick.Controls 2.12** 

sudo dnf install qt5-qtquickcontrols2

and that did the trick. Runs great.

**Comment by ntonnaett** [comment]
qtquickcontrols2 is listed as a dependency in [our documentation](https://jacktrip.github.io/jacktrip/Build/Meson_build/). So that's a downstream issue IMO.

**Comment by cchafe** [comment]
Perhaps we're missing something that maintainers can use to test their builds.
Is there a convention for that?

**Comment by ntonnaett** [comment]
Good point. If we had (unit) tests, they would probably run those after the build. We should ask distribution packagers, if there are other tactics.

**Comment by ntonnaett** [comment]
It's our fault. I'll create a PR.

**Comment by Enchufa2** [comment]
Downstream maintainer here. Two questions:

- Is QuickControls needed too?
- Jacktrip builds just fine without QuickControls2, which means that it doesn't link against libQt5QuickControls2, which means that this is a runtime dependency, right?

**Comment by ntonnaett** [comment]
What's probably happening is that the QML part is evaluated only at run-time. So we can't catch this at compile-time. But I was baffled by the fact too. Is QtQuick itself also just a runtime dependency? I don't know, but I'm not a Qt professional. However, I would handle both as build dependencies because the qt documentation says that you should add them to your used modules in your build system.

AFAIU @cchafe, Jacktrip doesn't run without the quickcontrols package. The CLI and classic GUI probably would.

**Comment by ntonnaett** [comment]
BTW, thank you for your packaging work! It is much appreciated that we always get the latest version on Fedora.

**Comment by ntonnaett** [comment]
We would have catched this with ahead of time compilation. But the Meson issue for this feature wasn't updated since 2020: https://github.com/mesonbuild/meson/issues/6988

**Comment by ntonnaett** [comment]
This issue is fixed in Fedora. So I'm closing this.

To completely avoid this kind of issues somebody needs to implement ahead-of-time compilation for qml in Meson. It doesn't look too complicated. Maybe I'll give it a try.
