### ISSUE TITLE
add installers to the releases page

### ISSUE THREAD

**Issue by omarcostahamido** [jacktrip/jacktrip#89]
It would be nice to add installers to the [releases page](https://github.com/jacktrip/jacktrip/releases).

O

**Comment by jtragtenberg** [comment]
Yes, the latest 1.2 version doesn't have the /bin folder

**Comment by omarcostahamido** [comment]
@jtragtenberg check out the new changes [here](https://github.com/jacktrip/jacktrip/commit/a2489d63795b3cc19db0bb8c0f38111e06522c46#diff-04c6e90faac2675aa89e2176d2eec7d8).

(yeah, @wholenotes could have cleared this issue with that, though I'd still think it's nice to have installers on the release page)
