### ISSUE TITLE
Distortion in PLC using FPP of 1024

### ISSUE THREAD

**Issue by cchafe** [jacktrip/jacktrip#896]
The symptom is robotic-sounding audio distortion. Bug discovered related to #846
The problem is in bufstrategy 3 when FPP = 1024.

mHist in Regulator.cpp gets set to 3 and that's causing the problem)
setting it to 1 fixes things
(more research needed before I create a PR)

A pipewire host can experience the problem because of the default FPP of 1024. The bug is not related to the choice of audio backend but rarely do hosts run FPP of 1024 these days, so this surfaced because of pipewire.

In debugging this it was noted that signalReceivedNetworkPacket is misleadingly named. It's actually emitted by the audio callback mechanism and would be better called signalTriggerPullPacket.

**Comment by cchafe** [comment]
The current theory is 
set mHist to 2
disable auto
use -q 100 
...............................
On the server I'm seeing the DSP process take about 55ms -- at 1024 a packet is 21ms
it seems we can get away with mCoeffs.resize(trainSamps/4 -2
and that fixes the bug

**Comment by cchafe** [comment]
recommending 
    mCoeffs.resize(trainSamps/8 - 2, 0.0);
and will create a bugfix PR

**Comment by cchafe** [comment]
there's another piece to this
the receiver needs to have greater tolerance when the transmitter is 1024
default -q auto3 is too tight, but -q auto40 works

**Comment by ntonnaett** [comment]
Is this fixed with #906 ?

**Comment by cchafe** [comment]
Yes, but related work is underway to generalize this. I'll "unbug" it for appearance's sake.

**Comment by cchafe** [comment]
I'll be adding to the record here as I get further (with setting pipewire FPP from inside JackTrip via rtaudio)

**Comment by ntonnaett** [comment]
I did some preparatory work / refactoring of the AudioInterface classes to make it easier adding more backends like Pipewire. The Pipewire API is complicated. I need some time to wrap my head around it, especially the threading part.

**Comment by cchafe** [comment]
I have a working "hacktrip" client which is entirely rtaudio/ALSA and sets FPP for pipewire. Code is in https://github.com/cchafe/hacktrip/tree/dev : Hapitrip class, largely undocumented, will try to do that and get it into JackTrip next. BTW, works with either rtaudio 5.2.0 from doc site or from latest github 6beta1 (distinguished by an ifdef in my code)

**Comment by ntonnaett** [comment]
Does this also work with RtAudio/JACK?

**Comment by cchafe** [comment]
I need to put that back in. Currently entirely aimed at pipewire.

**Comment by ntonnaett** [comment]
I meant RtAudio using the JACK backend of pipewire.

**Comment by cchafe** [comment]
Also, me. My previous version allowed multiple RtAudioAPI's and the future one should, too.

**Comment by cchafe** [comment]
see https://github.com/jacktrip/jacktrip/tree/rtaudioALSA for a working test version (ALSA only)
