### ISSUE TITLE
VS gui: missing "Refresh Devices" button

### ISSUE THREAD

**Issue by dyfer** [jacktrip/jacktrip#912]
This is relatively minor, but I noticed that in the VS gui, Settings -> Audio, there is no "Refresh Devices" button. The button is only present in the device selection dialog that shows up when JT starts, but not when going to Settings -> Audio, e.g. after disconnecting from the Studio.

<img width="606" alt="Screen Shot 2023-02-09 at 12 29 40" src="https://user-images.githubusercontent.com/1589177/217930870-5f542a9f-7862-4540-b52f-5d26ca740f00.png">

**Comment by ntonnaett** [comment]
I think that's fixed in 1.7.1. #913
