### ISSUE TITLE
Setting Up a Server To Let Multiple People To Jam?

### ISSUE THREAD

**Issue by jsl303** [jacktrip/jacktrip#92]
Is there a way to set up a server that lets multiple people to connect and jam together?
Server just needs to distribute audio without physically capturing/playing audio.
I built the Chris branch, and tried running on Google cloud with -S option. However, it only lets one person to connect at a time.

I ran the following on the server:
$ jackd -d dummy -r 48000 -p 256
$ jacktrip -S -p 4 --srate 48000 --bufsize 256

Then I ran the following on each client.
jackd -d coreaudio -r 48000 -p 256
jacktrip -C xxx.xxx.xxx.xxx

As soon as another client joins, it interrupts the sound for the current client and switches to the new client.
I tried all available -p (0-4) options on the server without luck.
Thanks for your help!

**Comment by ntonnaett** [comment]
Do both clients share the same IP address? Because I think jacktrip can't distinguish between those clients right now.
The -p options are just for the jack connections. If you want you can connect those manually with qjackctl.

I'm not sure if this works in hub mode but maybe you can use the port offset option (-o offset).

**Comment by jsl303** [comment]
Yes, I was just testing on two different computers in my house, so both get the same ip.
How do you use -o option? Just on server?
Which ports do you need to open if you use -o 10, and do you need to open a separate port per client?
Right now I have port 4464 and 61000 open on the server.
If I have 3 clients with -o 10, would I need to open: 4464, 4474, 4484, 61000, 61010, 61020?
Thanks!

**Comment by ntonnaett** [comment]
Client 1 uses -o 1 and gets port 4464 + 1 = 4465.
Client 2 uses -o 2 and gets port 4464 + 2 = 4466.

FYI If we get hole punching and unique client IDs (and in this case maybe mDNS) this will get much easier...

**Comment by jsl303** [comment]
Great, that worked!
Thanks!
