### ISSUE TITLE
Qt upstream bug comment still relevant?

### ISSUE THREAD

**Issue by ntonnaett** [jacktrip/jacktrip#927]
https://github.com/jacktrip/jacktrip/blob/ecce2b04094ea81031a56a9e664a066c4665554c/src/gui/virtualstudio.cpp#L900

The bug mentioned is fixed upstream. This is one of two similar places that break with Qt6. Do we still need to use setModifyParametersFunction()?

**Comment by ntonnaett** [comment]
@dyfer Still interested in working on putting #ifdefs for qt6 support?

**Comment by dyfer** [comment]
Actually, it seems it would be [cumbersome to support both Qt5 and Qt6](https://github.com/jacktrip/jacktrip/issues/767#issuecomment-1286294186) for the VS part. If others are interested in figuring out how to handle the QML part for both Qt5 and Qt6, then I'd be happy to add whatever else is needed. But if we decide to stay at Qt5 for compatibility a bit longer and just switch to Qt6 later, then there would be no point in adding an #ifdef for this.
(The last time I checked `novs` JT built with both Qt5 and Qt6)

**Comment by ntonnaett** [comment]
Oh, I somehow forgot about that comment. Some days ago I thought about working towards a qt5 LTS version that we could offer people with macOS High Sierra etc. and then do the switch to qt6.
