### ISSUE TITLE
QML issue

### ISSUE THREAD

**Issue by dyfer** [jacktrip/jacktrip#931]
When starting JackTrip (with gui) from the terminal, I'm getting the following message:
```
qrc:/vs/vs.qml:126:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
Log file location: "/Users/marcin/Library/Application Support/jacktrip/JackTrip/log.txt"
```
I can see this on both macOS and on Windows.
Moreover, the mentioned log file does not seem to get created.

EDIT: I can see this on both 1.6.8 as well as a recent `dev` build.

**Comment by ntonnaett** [comment]
If we change this, we can't support qt 5.12 anymore. We might want to silence the warning by adding `QT_DISABLE_DEPRECATED_BEFORE=0x060000` to our defines.

https://stackoverflow.com/questions/62297192/qml-connections-implicitly-defined-onfoo-properties-in-connections-are-deprecat

**Comment by dyfer** [comment]
I thought that after #888 we can't build with 5.12 anymore, isn't that true?

**Comment by ntonnaett** [comment]
Riiight… Oh, I confused 5.15.2 and 5.12. Opened a PR.
