### ISSUE TITLE
JACK handling regression in 1.8.0-beta1

### ISSUE THREAD

**Issue by cchafe** [jacktrip/jacktrip#947]
1.7.1 works fine (fresh build from source with qmake-qt5)
1.8.0-beta1  (built from current dev) hangs at mAudioInterface->setup

seems to lock up jackd
(top)

   3589 cc        20   0 2048504 259492 198940 R  96.7   0.8   1:53.99 qjackctl          
   3617 cc        20   0  287040 133304 113408 S  94.7   0.4   3:03.66 jackd             
   5921 cc        20   0  594252 139364 135608 S  13.3   0.4   0:01.43 jacktrip  
and requires a
killall -SIGKILL jacktrip

**(expected behavior)**

[cc@fedora jacktrip-1.7.1]$ ./jacktrip -C < favorite test server > -V
Verbose mode
Settings:startJackTrip before new JackTrip
Settings:startJackTrip before mJackTrip->startProcess
step 1
  JackTrip:startProcess before checkIfPortIsBinded(mReceiverBindPort)
  JackTrip:startProcess before checkIfPortIsBinded(mSenderBindPort)
  JackTrip:startProcess before setupAudio
  JackTrip:setupAudio before new JackAudioInterface
  JackTrip:setupAudio before mAudioInterface->setup
Setting JACK Process Callback...
SUCCESS

**(bug in beta)**

[cc@fedora jacktrip]$ ./jacktrip -C  < favorite test server > -V
Verbose mode
Settings:startJackTrip before new JackTrip
Settings:startJackTrip before mJackTrip->startProcess
step 1
  JackTrip:startProcess before checkIfPortIsBinded(mReceiverBindPort)
  JackTrip:startProcess before checkIfPortIsBinded(mSenderBindPort)
  JackTrip:startProcess before setupAudio
  JackTrip:setupAudio before new JackAudioInterface
  JackTrip:setupAudio before mAudioInterface->setup
Killed

**Comment by cchafe** [comment]
replicated the bug on another f37 machine with a fresh clone of the repo and building with meson

**Comment by psiborg112** [comment]
Can replicate here. Weirdly it gets further in the GUI: to step 5. And then there's an ASSERT: "n <= size() - pos" in file /usr/include/x86_64-linux-gnu/qt6/QtCore/qvarlengtharray.h, line 60. So I suspect this is related to the channel selection code.

**Comment by psiborg112** [comment]
It's because the number of channels is never set when using the JackAudioInterface. mNumInChans and mNumOutChans are uninitialised and filled with junk data.

**Comment by psiborg112** [comment]
Fixed in #948. (Although as mentioned in my comments on the pull request, we should maybe reconsider how the derived classes relate to the base class where channel selection is concerned. For the moment I just wanted to get this working again.)

**Comment by cchafe** [comment]
Thanks for the fix (#948) -- it should get merged for a beta2
