### ISSUE TITLE
predictable client names in Hub mode

### ISSUE THREAD

**Issue by riccardocagnasso** [jacktrip/jacktrip#97]
As far as I understand, in Hub mode, the Jack Client name of the client is the ip address of the server and the Jack Client of the server is the number of connected clients+1.

This makes impossibile to use jacktrip in a dynamic scenario in conjuction with some session manager like non-session-manager. 

The client (jacktrip -C) should have an option for the local Jack Client name and another option to request the server to use a certain Jack Client name

e.g.
```
jacktrip --clientname foo --remoteclientname bar -C 192.168.1.2
```
Will create a local Jack Client named "foo" and a Jack Client on the remote machine named "bar". (If "bar" is not available, it could create bar-1 or better, return an error).

**Comment by psiborg112** [comment]
There's already an option (--clientname) to specify the client name in all but the hub server mode. It's currently broken, but there's a fix for it in #93 which should hopefully be applied soon. Setting it on the server side is a slightly trickier issue and would need a change to the protocol. That said, we might be able to send it during the initial TCP connection in addition to the port number in a way that wouldn't break backwards compatibility. I should be able experiment with it in the next few days.

**Comment by riccardocagnasso** [comment]
> There's already an option (--clientname) to specify the client name in all but the hub server mode. It's currently broken, but there's a fix for it in #93 which should hopefully be applied soon. Setting it on the server side is a slightly trickier issue and would need a change to the protocol. That said, we might be able to send it during the initial TCP connection in addition to the port number in a way that wouldn't break backwards compatibility. I should be able experiment with it in the next few days.

Thank you. I think that this is paramount to the usefulness of Hub mode. If multiple clients can connect to a server, the server needs a way to know what connects to what.  If names cannot be decided programmatically, this software cannot be used if not manually.

IMHO even if you are forced to break backward compatibility, it's worth it (maybe you could add a flag for "previous protocol version" support)

**Comment by psiborg112** [comment]
I have an implementation of this working in the 'qjackctl' branch now if you want to test it out. (You can either set it in the advanced options of the GUI or on the command line using --remotename.)

**Comment by riccardocagnasso** [comment]
> I have an implementation of this working in the 'qjackctl' branch now if you want to test it out. (You can either set it in the advanced options of the GUI or on the command line using --remotename.)
It works perfectly
