### ISSUE TITLE
Reporting a vulnerability

### ISSUE THREAD

**Issue by igibek** [jacktrip/jacktrip#997]
Hello! 

I hope you are doing well! 

We are a security research team. Our tool automatically detected a vulnerability in this repository. We want to disclose it responsibly.  GitHub has a feature called **Private vulnerability reporting**, which enables security research to privately disclose a vulnerability. Unfortunately, it is not enabled for this repository. 

Can you enable it, so that we can report it? 

Thanks in advance! 

PS: you can read about how to enable private vulnerability reporting here: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by psiborg112** [comment]
Hi, one of the devs, but afraid I don't have admin access to the project, so can't change the necessary settings. (Not sure exactly who does, but I assume @cchafe or @mikedickey can probably help here?) In the meantime, are there any details that you'd be happy to email through to myself or one of the other devs? (Pretty sure my contact details are on my github page.) I understand if that's not possible.

**Comment by mikedickey** [comment]
Sorry, we added this to the README a while ago but I forgot to respond here and close the issue:

```
Please report any security concerns to [vulnerabilities@jacktrip.org](mailto:vulnerabilities@jacktrip.org)
```
